### ISSUE TITLE
graphical glitch in the apartment section 

### ISSUE THREAD

**Issue by Dizzydan015** [elishacloud/Silent-Hill-2-Enhancements#103] opened 2019-03-26 20:59 UTC
![Snapshot - 7](https://user-images.githubusercontent.com/48966949/55032874-c023a500-5009-11e9-9489-facac5a9eaac.png)
Whenever I go into this room it always gives me this. It results in the game being stuck like this resulting it being unplayable. The game is fine before entering this room with no error. Is there any way to fix this or do I have to uninstall the game?

**Comment by Polymega** [comment] 2019-03-26 22:41
Hi @Dizzydan015 , 

I don't believe this issue has to deal with the base game itself, so uninstallation is not needed. To start: Can you please ZIP package your `d3d8.log` and attach it to your response here?

**Comment by Dizzydan015** [comment] 2019-03-26 22:49
Hi @Polymega 
[Silent Hill 2.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3010742/Silent.Hill.2.zip)
I have both d3d8.log and d3d9.log in this ZIP package.

**Comment by Polymega** [comment] 2019-03-26 22:53
Thanks. I like to know what GPUs are being used when this bug happens. So you and I may be doing a lot of back-and-forth to troubleshoot this, using a process of elimination each step of the way. 

Very few people experience this bug, and looking back at another person who had the same issue as you, [they resolved the problem by downloading the DirectX 9 SDK](https://github.com/ThirteenAG/WidescreenFixesPack/issues/490#issuecomment-410545095). 

So to start things off: 

1. [Download the DirectX 9 SDK.](https://www.microsoft.com/download/details.aspx?id=35)
2. After installing this, ensure `d3d8to9 =` is set to `1` in the `d3d8.ini` file. 
3. Launch the game and see if the issue is resolved. 

Please let me know either way if this fixes things for you or not.

**Comment by elishacloud** [comment] 2019-03-27 03:29
This looks like the same issue as #40.

**Comment by Polymega** [comment] 2019-03-27 03:49
Someone else with the bug said installing the DirectX 9 SDK resolved it so I was curious to see if that would fix it before disabling d3d8to9. 

If that didn't work, I'm curious to know if the `PS2FlashlightBrightness` would have any positive results for the bug.

**Comment by Dizzydan015** [comment] 2019-03-27 09:52
Hi, sorry for the long wait I just woke up. Anyways I tried the DirectX method first. This also gave me the same error. However, when I changed the d3d8to9 = 0, I was finally able to go into that room with no glitches or errors. Thank you for your help. 
![image](https://user-images.githubusercontent.com/48966949/55066586-ff87db00-5075-11e9-8a14-f0e6aa13545e.png)

**Comment by AeroWidescreen** [comment] 2019-03-28 02:01
@Polymega I forgot: is there any point to d3d8to9 besides ReShade compatibility? Because if not, wouldn't it be better to have it off by default and make ReShade an optional step in your guide? No more odd shader bugs, and no more slow transitions for AMD users.

**Comment by Polymega** [comment] 2019-03-28 02:09
Oh? DX9 is also the cause for the AMD slow transition bug? I didn't realize (or remember) that. If that's the case, then yeah, I think that's a great idea. 

We can have that off by default, I can instruct users to enable it on the guide if they wish to use ReShade, and windowed mode for the mod will still be enabled by default as a redundant safety measure for AMD cards.

**Comment by elishacloud** [comment] 2019-04-30 07:00
@Dizzydan015, someone mentioned on the forum on YouTube that this graphical glitch in the apartment was fixed with the latest release.  Can you check with [v1.3.1340.0](https://github.com/elishacloud/Silent-Hill-2-Enhancements/releases/tag/v1.3.1340.0) and see if this issue still happens?

**Comment by elishacloud** [comment] 2019-12-18 03:07
Closing issue.  It can be reopened if there is still an issue.

**Closed by elishacloud** 2019-12-18 03:07 UTC
