### ISSUE TITLE
Application error (0x0000005)

### ISSUE THREAD

**Issue by retconn** [elishacloud/Silent-Hill-2-Enhancements#177] opened 2019-10-11 14:45 UTC
![image](https://user-images.githubusercontent.com/44321681/66661007-37223300-ec14-11e9-9ff0-90c1012bd420.png)

Getting this message immediately trying to run the game. It was working before I applied the latest versions of everything. Just copied the new folders to my game directory.

**Comment by retconn** [comment] 2019-10-11 15:00
![image](https://user-images.githubusercontent.com/44321681/66662162-4bffc600-ec16-11e9-9388-2cd49862327d.png)

**Comment by retconn** [comment] 2019-10-11 15:23
Ive had it modded prior to enhanced edition but when i removed that file it works now apparently which is weird since I had it working before.

**Comment by Polymega** [comment] 2019-10-11 15:26
You're likely to run into compatibility issues if you mix other mod packages/files that aren't part of our project with our project. 

So the single removal of `SH2.bat` is what fixed the problem?

**Comment by retconn** [comment] 2019-10-16 16:34
Sorry I just wanted to test a few times to see if that worked and it appears it has thank you.

**Comment by Polymega** [comment] 2019-10-16 17:25
Great! Glad to hear that fixed it.

**Comment by need-no-name** [comment] 2019-10-27 13:49
I have the same problem. I've just installed the game and had the "insert CD1" error and solved it with "Enhanced Executable" but after going through installation guide can't launch the game. 
![sh2err](https://user-images.githubusercontent.com/57065753/67635554-dd8d5a00-f8dd-11e9-8172-fc6fe67ac81b.png)
![logerr](https://user-images.githubusercontent.com/57065753/67635557-e2eaa480-f8dd-11e9-90a1-034e87a2d778.png)

**Comment by Polymega** [comment] 2019-10-27 17:02
Starting simple/easy: Does rebooting your PC solve the issue?

If that doesn't work, if you temporarily remove dsound.dll from the game's directory does it launch then?

**Comment by Polymega** [comment] 2019-10-27 23:55
I took a closer look at your `d3d8.log` image attachment. It appears you're trying to launch the game through `sh2pc.exe.bak.exe`? If so, that may be the cause of your issue. 

Under the "[Install Enhanced Executable](http://enhanced.townofsilenthill.com/SH2/#installEnhancedEXE)" step, you would be making a backup of your original executable by renaming it from `sh2pc.exe` to `sh2pc.exe.bak`. Then, you would download the new executable from that installation step and placing it in your game's directory, which would make it your new `sh2pc.exe`.

Ensure you are launching the game through the new executable (`sh2pc.exe`) and not your original executable, which you backed up (`sh2pc.exe.bak.exe` which should actually be `sh2pc.exe.bak`).

It looks like you renamed it correctly, so try rebooting your PC as well to see if that solves it first.

**Comment by need-no-name** [comment] 2019-10-28 04:52
Thanks for responding.
I removed dsound.dll from directory still got the same error.
Corrected the name sh2pc.exe.bak.exe to sh2pc.exe.bak still got the same error.
Just to be safe I removed sh2pc.exe.bak from directory still got the same error.
After running sh2pc.exe  multiple times d3d8.log didn't change even the timestamps stayed the same. clicking on sh2pc.exe doesn't make a new d3d8.log.
I don't know if restarting and rebooting are  same thing or different but I restarted my laptop several times.
![sh2err](https://user-images.githubusercontent.com/57065753/67652839-081df800-f95c-11e9-9f40-db69fb2ad03f.png)
![log err](https://user-images.githubusercontent.com/57065753/67652841-0b18e880-f95c-11e9-99c3-e51d0fb8a681.png)

**Comment by Polymega** [comment] 2019-10-28 05:10
> After running sh2pc.exe multiple times d3d8.log didn't change even the timestamps stayed the same. clicking on sh2pc.exe doesn't make a new d3d8.log.

Odd. It attempted to run one time under `sh2pc.exe.bak.exe` and didn't attempt after the naming correction? 

The error you're receiving can typically be due to the application expecting/needing the correct `.dll` files to run. For our project, that could be possibly be one of three things: 

1. DirectX 8 (what the base game runs on)
2. DirectX 9 (what ReShade runs on)
3. Visual C++ 2010 (what IndirectSound runs on)

Do you have these runtime libraries installed? 

Doing a Google search on the error, a Microsoft rep has suggest running system file checker to see if Windows 10 can pin-point the problem: 

- https://answers.microsoft.com/en-us/windows/forum/windows_10-performance/application-error-0xc0000005/6224ae45-a251-4f21-b076-74524618d00a
- https://support.microsoft.com/en-us/help/929833/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system

If SFC doesn't give us any leads we may need to get Elisha's input with this.

**Comment by elishacloud** [comment] 2019-10-28 05:22
> After running sh2pc.exe multiple times d3d8.log didn't change even the timestamps stayed the same. clicking on sh2pc.exe doesn't make a new d3d8.log.

If it is not logging anything it means that it crashes before the Silent Hill 2 Enhancement module is loaded.  Since this module is statically loaded it most likely means there is an issue with the exe file itself, or some other statically loaded dll that loads prior to d3d8.dll.

After trying everything from Polymega's thread above, if it still does not work then try removing all the Silent Hill 2 Enhancement files and get the game working natively before trying Silent Hill 2 Enhancement updates.

**Comment by need-no-name** [comment] 2019-10-28 13:43
> After trying everything from Polymega's thread above, if it still does not work then try removing all the Silent Hill 2 Enhancement files and get the game working natively before trying Silent Hill 2 Enhancement updates.

I've installed direct x 8 and Visual C++ 2010.
When I try to install direct x 9 it says that it detected a newer version installed already.

- https://support.microsoft.com/en-us/help/929833/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system
I ran SFC but I'm still getting same error.


Just want to clear 2 things:
1. I don't have real copy of the game and downloaded it from this website
https://www.myabandonware.com/game/silent-hill-2-restless-dreams-bgd#download

2. when I remove "d3d8.dll" from game directory I can launch the game (with like 10 fps and a lot of freezes) but when I put it back in the game folder error comes back.

**Comment by Polymega** [comment] 2019-10-28 18:20
@elishacloud 
Would **need-no-name** need to install a certain version of Visual Studio that our own project runs on? I looked at the read me and it says it's developed using Visual Studio Community 2017; is there a certain VS download that would be needed for this that may not already by installed for them?

**Comment by Polymega** [comment] 2019-10-28 21:51
@retconn 
Did you also obtain the game through the myabandnonware.com site?

**Comment by elishacloud** [comment] 2019-10-29 03:04
> Would need-no-name need to install a certain version of Visual Studio that our own project runs on?

No.  The Visual Studio runtime for the module is included in the dll.  The runtime is only needed for other modules, like the IndirectSound.

@need-no-name,
The first thing that the module does before logging is read the config file.  There could be an issue there.  Can you zip up the `sh2pc.exe`, `d3d8.dll` and `d3d8.ini` to a sinlge zip file and attach it to the thread?  I would like to check them out myself.

**Comment by need-no-name** [comment] 2019-10-29 05:41
@elishacloud 

Ok, here you go.

[sh2pc.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3781866/sh2pc.zip)

**Comment by elishacloud** [comment] 2019-11-02 06:43
Thanks @need-no-name!  I am not seeing anything wrong with your files.  Would you mind trying the latest update and see if that has the same issue?

Here is the download: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3800197/d3d8.zip)

**Comment by Polymega** [comment] 2019-11-02 06:49
Actually, @retconn ,
I saw some VODs on Twitch of you playing the Enhanced Edition the other week. Does that mean you figured out the solution to your error? If so, can you please share how you fixed it here?

**Comment by Polymega** [comment] 2019-11-02 06:56
@need-no-name 
I checked that abandonware site and they also link other fixes/patches on that download page. Did you by chance download/install any of the fix packages found there as well?

**Comment by need-no-name** [comment] 2019-11-07 09:00
@elishacloud 
I downloaded the file and replaced my current files with them but nothing changed. :(
@Polymega
Yes I downloaded the "nocd" patch so that I can run the game without the disk but I replaced it with your .exe file
.
It looks like I'm the only one with this problem so probably there is something wrong with my laptop.
Anyways just wanted to thank you guys for your time, trying to help me. If you have any ideas I'd love to try them.

**Comment by Polymega** [comment] 2019-11-07 19:47
If you uninstall/delete everything from the game's folder and reinstall **only the base game** (using none of our mods) do you still receive the error? I unfortunately still wouldn't have a solution for you, but at least it can be determined if the error is happening from the base game install or from our mods on top of it. 

I'm sorry you're getting that error and we don't have a ready solution for you. If you ever figure out how to fix it please do let us know so we can help others who might have the same error in the future.

**Comment by need-no-name** [comment] 2019-11-10 16:39
I don't need to delete or uninstall the game, I can play the game (with like 10 fps and a lot of freezes) with all the mod files in my game folder with the exception of "d3d8.dll". Because when I remove "d3d8.dll" from game directory I can launch the game  but when I put it back in the game folder error comes back. So I think either my laptop or "d3d8.dll" file are the issue and since you said you didn't find any problems with "d3d8.dll" then the problem has to be my laptop.

Again I appreciate you guys taking the time and helping me and if I can figure out what causes the problem I post it here.

**Comment by Polymega** [comment] 2019-11-11 00:49
Very silly question, but, have you attempted to run the game as adminstrator? Did that help/change anything?

**Comment by need-no-name** [comment] 2019-11-14 07:49
Yes I tried that but nothing changed.

**Comment by Polymega** [comment] 2019-11-14 08:11
Final-final suggestion to try: If you set `AutoUpdateModule = 0` in the `d3d8.ini` file does it run then? After this I'm fully out of ideas. :-/

**Comment by Polymega** [comment] 2019-11-17 19:46
@retconn @need-no-name 
Are you two using an antivirus solution? If so, what antivirus brand are you using?

**Comment by elishacloud** [comment] 2019-11-19 04:17
1. This could be the same issue as #190.  You may want to check your compatibility options.  All options should be disabled.  To do this right-click on the `sh2pc.exe` file and open the Properties page.  Then click on the `Compatibility` tab.

![image](https://user-images.githubusercontent.com/25625456/69116065-d02c4100-0a3f-11ea-91e9-f4a91c7b0000.png)

2. If that does not work you can try with the attached update:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3861875/d3d8.zip).  Just copy these into your Silent Hill 2 folder overwriting any existing files and then run the game.

3. If none the above works you can try renaming `sh2pc.exe` to `sh2pc1.exe` and see if that works.

**Comment by need-no-name** [comment] 2020-03-05 09:05
Hi
I just wanted to update my situation.
I found the American version of the game (previously I had the europian version). After installing the game, I went through the Enhanced Edition tutorial and the game works now. So the error was probably from my version of the game.
I also set my compatibility option to Windows XP service pack 2.

Thanks again.

**Comment by Polymega** [comment] 2020-03-05 19:08
Thanks for following up with us! I'm glad a different copy of the game fixed your issues.

**Comment by elishacloud** [comment] 2020-04-29 03:44
Closing this out.

**Closed by elishacloud** 2020-04-29 03:44 UTC
