### ISSUE TITLE
slow download or alternative download

### ISSUE THREAD

**Issue by cyph3rlunch** [elishacloud/Silent-Hill-2-Enhancements#628] opened 2022-10-22 05:56 UTC
Hi i would love to enjoy this classic with all the wonderful improvements you guys have made. However i think the downloader is either bugged or perhaps your servers are under heavy load. Is there an alternative link or way for me to download the latest release?

edit: I have tried the following: granted exclusions for all directories related to this for my antivirus, but its not blocking anything. My internet is over 100mbps normally. Also tried running as admin too, no change

![image](https://user-images.githubusercontent.com/41335504/197322958-eeea72cf-8674-4f6a-9b56-a2f21241577b.png)

**Comment by 0ogieBoogie** [comment] 2022-10-22 07:02
same for me. sad

**Comment by masterchan-777** [comment] 2022-10-22 12:05
it's almost impossible to download the latest releases atm, experiencing extremely slow download speeds and ending up with partially downloaded files. If someone can upload the latest packages to a new file host that would be really appreciated.

**Comment by cyph3rlunch** [comment] 2022-10-22 12:10
there are torrents but they are old. if someone could make their torrent public it could help (obviously without the iso). Just the MOD files.

**Comment by iMSh4d0w-Github** [comment] 2022-10-22 12:39
Check issue #624, #625 or #626

**Comment by Polymega** [comment] 2022-10-22 13:44
We're currently migrating the project site/files over to a dedicated server to help with the load of new users due to the recent SH announcements. As this migration is currently underway, there will be slowdown during this server transfer. Please be patient with us.

Check out Twitter page for server updates when they happen:
https://twitter.com/WhereAllBegins/status/1583624623752871936

**Comment by revblaze** [comment] 2022-10-23 15:15
@Polymega Any chance that you guys could temporarily upload the latest replacer files to MEGA, Dropbox or any other file sharing service in the meantime?

**Comment by RyuSeisuke1992** [comment] 2022-10-23 17:24
Maybe it helps if you download the files directly?
I have just made the experience that it is faster...

https://files.townofsilenthill.com/SH2EE/packages/SH2EE_XInputPlus_4.15.2.zip
https://files.townofsilenthill.com/SH2EE/packages/SH2EE_Image_Enhancement_Pack_1.1.1.zip
https://files.townofsilenthill.com/SH2EE/packages/SH2EE_Essential_Files_1.2.4.zip
https://files.townofsilenthill.com/SH2EE/packages/SH2EE_Enhancements_Module_2.0.2006.0.zip
https://files.townofsilenthill.com/SH2EE/packages/SH2EE_Enhanced_EXE_NA_v1.0.zip
https://files.townofsilenthill.com/SH2EE/packages/SH2EE_DSOAL_1.31a.02.zip
https://files.townofsilenthill.com/SH2EE/packages/SH2EE_FMV_Enhancement_Pack_1.5.3.zip
https://files.townofsilenthill.com/SH2EE/packages/SH2EE_Audio_Enhancement_Pack_2.0.4.zip

**Comment by cyph3rlunch** [comment] 2022-10-23 18:24
> Maybe it helps if you download the files directly? I have just made the experience that it is faster...
> 
> https://files.townofsilenthill.com/SH2EE/packages/SH2EE_XInputPlus_4.15.2.zip https://files.townofsilenthill.com/SH2EE/packages/SH2EE_Image_Enhancement_Pack_1.1.1.zip https://files.townofsilenthill.com/SH2EE/packages/SH2EE_Essential_Files_1.2.4.zip https://files.townofsilenthill.com/SH2EE/packages/SH2EE_Enhancements_Module_2.0.2006.0.zip https://files.townofsilenthill.com/SH2EE/packages/SH2EE_Enhanced_EXE_NA_v1.0.zip https://files.townofsilenthill.com/SH2EE/packages/SH2EE_DSOAL_1.31a.02.zip https://files.townofsilenthill.com/SH2EE/packages/SH2EE_FMV_Enhancement_Pack_1.5.3.zip https://files.townofsilenthill.com/SH2EE/packages/SH2EE_Audio_Enhancement_Pack_2.0.4.zip

ty for this. is this the latest release? also how to i install them?

**Comment by BeverlyBean** [comment] 2022-10-23 20:07
why didnt they just pack in all the enhanced files into the installer in the first place?

**Comment by coldwave0525** [comment] 2022-10-24 07:07
> > Maybe it helps if you download the files directly? I have just made the experience that it is faster...
> > https://files.townofsilenthill.com/SH2EE/packages/SH2EE_XInputPlus_4.15.2.zip https://files.townofsilenthill.com/SH2EE/packages/SH2EE_Image_Enhancement_Pack_1.1.1.zip https://files.townofsilenthill.com/SH2EE/packages/SH2EE_Essential_Files_1.2.4.zip https://files.townofsilenthill.com/SH2EE/packages/SH2EE_Enhancements_Module_2.0.2006.0.zip https://files.townofsilenthill.com/SH2EE/packages/SH2EE_Enhanced_EXE_NA_v1.0.zip https://files.townofsilenthill.com/SH2EE/packages/SH2EE_DSOAL_1.31a.02.zip https://files.townofsilenthill.com/SH2EE/packages/SH2EE_FMV_Enhancement_Pack_1.5.3.zip https://files.townofsilenthill.com/SH2EE/packages/SH2EE_Audio_Enhancement_Pack_2.0.4.zip
> 
> ty for this. is this the latest release? also how to i install them?

Maybe unzip the file to the game directory according to this 'https://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#directoryTree' ? I' m trying too

**Comment by RyuSeisuke1992** [comment] 2022-10-24 13:20
I am uploading the latest files to google drive. See here:
https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/633#issuecomment-1289020290

**Comment by Polymega** [comment] 2022-10-28 20:37
Server migration is done and distribution for the project's file packages has been changed to a more stable solution.

You can find the Setup Tool here:
https://enhanced.townofsilenthill.com/SH2/install.htm#usingEE

Please report back whether or not the download times out for you. Also, please let us know the average speed of the download. (Speeds may start off slow at the start of downloading each new package, but should pick up speed within seconds.)

**Comment by Polymega** [comment] 2022-10-28 21:40
Server migration is done and distribution for the project's file packages has been changed to a more stable solution.

I am going to close this ticket out . For sake of management/consolidation, if you run into any troubles still with the Setup Tool, [please report them here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/647).

**Closed by Polymega** 2022-10-28 21:40 UTC

**Comment by ronjouch** [comment] 2022-10-29 11:09
> Also, please let us know the average speed of the download. (Speeds may start off slow at the start of downloading each new package, but should pick up speed within seconds.)

Faster download speeds confirmed! Maxes my (modest) internet connection, at constant 1.6MB/s. Thanks for the fix.

**Comment by iMSh4d0w-Github** [comment] 2022-10-29 12:35
> Also, please let us know the average speed of the download. (Speeds may start off slow at the start of downloading each new package, but should pick up speed within seconds.)

Unfortunately, it only downloads at 640 KB/s but no longer times out, so it's stable. Thank you for all the work.
