### ISSUE TITLE
Audio Falls out of sync halfway through game

### ISSUE THREAD

**Issue by Umbrellaspy** [elishacloud/Silent-Hill-2-Enhancements#314] opened 2020-09-10 08:11 UTC
Howdy all, I've encountered a sort of weird bug with the Enhanced Edition.

The audio in the cutscenes falls out of sync, and only seems to grow further detached as it plays out.
but what is odd to me is that this issue does not start until quite late into the game! Everything works perfectly until
the scene with Maria in the Labyrinth, where things are just ever so slightly off. However syncing really begins to show
issues during the Eddie sequence shortly after, and hits rock bottom during the Angela scene on the staircase. I'm not sure
what causes this and why it only becomes a problem so deep into the game, but I'm hoping it won't be too crazy of a fix :) 
Thanks in advance for any feedback!

note: This does not affect the audio during the actual gameplay. Only during the cutscenes. Log is posted below.

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5200116/d3d8.log)

**Comment by Badore90** [comment] 2020-09-10 12:11
So if you try the cemetery cut-scenes at game's beginning all is fine?

**Comment by Umbrellaspy** [comment] 2020-09-10 12:32
> So if you try the cemetery cut-scenes at game's beginning all is fine?

Yep! Everything seems fine to me up until the labyrinth section. If there was any sync issues before then, it was subtle enough not to notice for me.

**Comment by Polymega** [comment] 2020-09-10 17:17
Did you play the game in one sitting?
If you load a save file close to one of these later cutscenes and replay them, is it still out of sync?

I'm wondering if you played it in one session and, the further time went along, the more out of sync it became due to that. For reasons this may happen, I'm mainly thinking there might be another program/software running in the background that uses a lot of resources which is bogging down the game just enough to start desyncing it.

You can see if there's any software doing such a thing, [try setting the `SingleCoreAffinity` fix to use a different core](http://enhanced.townofsilenthill.com/SH2/config.htm#SingleCoreAffinity), or even try removing the ReShade files. ReShade has been known to cause some odd issues for people, and it might be the cause of your issues, here.

The ReShade files are:

```
d3d9.dll
d3d9.log
ReShade.ini
ReShade_sh2pc.ini
```

**Comment by Polymega** [comment] 2020-11-12 20:34
Closing ticket. Feel free to re-open this ticket if you'd like to follow-up with more information. Thanks.

**Closed by Polymega** 2020-11-12 20:34 UTC
