### ISSUE TITLE
Weird/Corrupt text

### ISSUE THREAD

**Issue by szbozso94** [elishacloud/Silent-Hill-2-Enhancements#176] opened 2019-10-05 20:50 UTC
Sometimes the game has weird texts during cutscenes and in game for items, messages or memos.
In the result screen there were no comprehensible text either.
Wonder what caused this.
![sh2pc 2019-10-05 22-35-53](https://user-images.githubusercontent.com/56206424/66260712-886c9580-e7c2-11e9-8335-c1e7c6ace948.png)

**Comment by Polymega** [comment] 2019-10-05 21:13
Does this happen to you even if you close the game and relaunch it?

Are you using a fan translation pack found elsewhere on the Internet, outside of our installation guide? 

If not, have you tried re-downloading the [Enhanced Edition Essential Files](http://enhanced.townofsilenthill.com/SH2/#installEssentialFiles) and replacing all the files in the appropriate folders?

**Comment by szbozso94** [comment] 2019-10-07 15:21
Yes, it still happened after a restart.
I did not use any translation pack the oiginal language is english.
I tried to replace all the files from the Enhanced edition but it did not work.
When I installed the game for some reason it has defaulted to russian but later reset the language to english, maybe that was what caused it.
It is not a big problem the strange thing about it that only like 10 lines, 1 whole description and like 5 item name had this issue (These item names were correct in the inventory menu though).
Nothing game breaking.
Thanks for the quick reply!

**Comment by Polymega** [comment] 2019-10-07 16:44
> When I installed the game for some reason it has defaulted to russian 

Hmm... The PC game was never released in Russia/n. Perhaps you downloaded an installer for the game that was modified for Russian players, and this is causing text corruption elsewhere in the game.

**Comment by szbozso94** [comment] 2019-10-12 05:54
Yes probably it was due to the addition of the cyrillic letters but I do remember that last year I did not have this issue.

Never mind, next time I will make sure that it stays english.
Thanks for the help.

**Comment by Polymega** [comment] 2019-10-12 06:00
Last year we didn't implement high resolution fonts. Chances are, when we added this feature it might have made the Cryllic text pack incompatible. 

You can try setting `UseCustomFont = 0` in the `d3d8.ini` file to see if that restores the missing characters. But note that in doing so, you won't be able to use the high resolution fonts.

**Comment by elishacloud** [comment] 2019-12-18 03:11
Closing issue.  It can be reopened if there is still an issue.

**Comment by MountainDukkake** [comment] 2019-12-18 04:21
I can confirm that disabling high resolution fonts does not fix the corrupt text. What's weird is that if the text is corrupt on something that's saved as a memo afterwards, it's completely readable from in the menu. Unfortunately, I didn't think to take screenshots of that.
It also happened while picking up a healing item or bullets, but only once.
My installer was also in Russian so maybe that's the issue. Here's some screenshots of a couple examples.

![sh2pc 2019-12-16 19-40-23](https://user-images.githubusercontent.com/59004007/71055217-ca9b4700-2122-11ea-913d-d6438fa387eb.png)

![sh2pc 2019-12-16 19-08-56](https://user-images.githubusercontent.com/59004007/71055234-dd158080-2122-11ea-8956-999474e06212.png)

**Comment by Polymega** [comment] 2019-12-18 04:32
> My installer was also in Russian so maybe that's the issue.

That's likely it. 

Are you using our executable? 
http://enhanced.townofsilenthill.com/SH2/#installEnhancedEXE

Are you using our language files from the Enhanced Edition Essential Files download?
http://enhanced.townofsilenthill.com/SH2/#installEssentialFiles

**Comment by MountainDukkake** [comment] 2019-12-18 05:00
Double yes. Made 200% sure to completely follow the guide during the installation as well. If the only solution is to find a version of the game with an English installer, would I be able to at least backup my saves? I'd hate to have to start over completely as it's my first time playing the game.

**Comment by Polymega** [comment] 2019-12-18 05:07
I'd see no reason for your saves to not carry over. They're held as separate files under `Silent Hill 2\data\save\Folder 01\`, so make a back up of them.

Beyond the binary (main executable), I'm not sure what else could've been modified to create the text errors?

**Comment by Polymega** [comment] 2019-12-18 05:15
Can you share what is inside your `language.ini` file?

**Comment by Polymega** [comment] 2019-12-18 06:07
Yup. Either 1 or 0 is for English (can't remember which and can't check atm, but I think it's 1).

So is everything fixed for you, text-wise?

**Comment by MountainDukkake** [comment] 2019-12-18 06:58
Oh, I edited that .ini file yesterday and it only seems to have fixed the menus.

So far it hasn't effected anything important, it's just a little immersion breaking.

**Comment by Polymega** [comment] 2019-12-18 07:27
The text/subtitles are held in `data\etc\message\` and, if using our project, our edited text files would be in `sh2e\etc\message\`.

Can you take a snapshot of the contents in both of these folders for me?

**Comment by MountainDukkake** [comment] 2019-12-18 16:59
Just to confirm, you want to see the entire contents of both folders? I took nearly 20 screenshots at less than 1080p due to my monitor breaking, so, I highly suggest a magnifying glass. There's also significantly less files in the sh2e folder than the unmodded folder.
 Would it be easier to PM them to you if possible, or should I just dump the whole lot of 'em here? 'Cause there's a lot.

**Comment by Polymega** [comment] 2019-12-18 19:40
Sorry, I should've been more specific. Just a single snapshot of each folder to show just some of the files in each; I don't need to see them all.

And while you're doing this, can you also take a snapshot of the game's main directory? For this one, please snapshot all the files/folders in this directory.

**Comment by MountainDukkake** [comment] 2019-12-18 20:21
Hopefully this is what you meant. Here's the message folders for both.

The unmodded message folder
![SH2V folder](https://user-images.githubusercontent.com/59004007/71119916-44761380-21a9-11ea-88b1-a14e733c9e1c.png)

The modded message folder
![SH2E folder](https://user-images.githubusercontent.com/59004007/71119968-5d7ec480-21a9-11ea-8a6a-2ab7f2eb5782.png)

Here's the game's main directory:

Part 1
![SH2 folder layout 1](https://user-images.githubusercontent.com/59004007/71119997-71c2c180-21a9-11ea-9b9f-e7b6d8d486b4.png)

Part 2
![SH2 Folder Layout 2](https://user-images.githubusercontent.com/59004007/71120035-83a46480-21a9-11ea-83a6-178ad8271ea7.png)

And again, sorry for the poor photo resolution. I've resorted to using an old TV as computer screen.

**Comment by Polymega** [comment] 2019-12-18 22:14
No worries and thank you for the screenshots. Everything looks to be correct in your directories. I have one last-ditch effort. Try replacing your files with these ones in the game's main directory:

[device.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3980773/device.zip)

If this doesn't work, I'd recommend deleting the game/files (but make a backup of your save files at `data\save\Folder 01\`) and finding a new copy that wasn't modified for Russian use. I'm thinking whoever modified that installer might have changed other things we're not aware of.

**Comment by MountainDukkake** [comment] 2019-12-18 23:13
No luck with replacing those files, unfortunately. I just finished the game (first time, and wow.) and the results screen was all messed up just like szbozso94's. I'll find a different version of the game and load up my end-game save, see if that fixes it. I'll let you know ASAP.

**Comment by MountainDukkake** [comment] 2019-12-21 15:37
Alright, I can confirm that it was the Russian version being a dingus. I'm doing a 2nd play-through just to make sure. The results screen wasn't glitched out. I was able to just load a save and look at it.
Anyway, some of the corrupt dialogue I saw in-game is now fixed, but I'll keep playing it to make sure that it's ALL fixed, and that I didn't just get lucky.

**Comment by Polymega** [comment] 2019-12-21 20:21
Great! Glad that seems to have fixed it. Yeah, chances are [the modified installer changed something elsewhere that was causing the text issues.](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/97)

If I were to guess, that modified installer was probably made before the birth of this project, hence the incompatibilities. Since then, [we've had a Russian fan assist us in making a high resolution language pack to work alongside our project,](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/144) so a modified installer would not longer be needed.

**Comment by elishacloud** [comment] 2020-04-29 03:44
Closing this out.

**Closed by elishacloud** 2020-04-29 03:44 UTC
