### ISSUE TITLE
Strange wave while playing

### ISSUE THREAD

**Issue by solidcrash** [elishacloud/Silent-Hill-2-Enhancements#148] opened 2019-07-09 22:31 UTC
Hi, when i'm moving there is a wave (line) like a disturb that appears in the screen, but only when i'm moving.
![IMG_20190710_003011](https://user-images.githubusercontent.com/52722657/60927369-faa80980-a2a9-11e9-932b-0d5917dd8a5a.jpg)
![IMG_20190710_003008](https://user-images.githubusercontent.com/52722657/60927370-faa80980-a2a9-11e9-8ce7-eec4fb8859f8.jpg)

**Comment by Polymega** [comment] 2019-07-09 22:41
Hi, 

That is a result of the game being played at 30 FPS and your monitor being at a different refresh rate (for example: 60 Hz, or 60 FPS). If, by chance, you're streaming the game (or capturing video on general) you will *not* see this "wave." It's only visible on your monitor screen.

We recommend you play the game at 30 FPS as there are noted audio/visual issues if you change the frame rate. This is because the game was only ever designed to be played at 30 FPS.

**Comment by solidcrash** [comment] 2019-07-09 23:01
Thank you. How can i change the frame rate?

**Comment by elishacloud** [comment] 2019-07-09 23:08
Are you sure this is frame rate related?  It looks like standard screen tearing caused by having v-sync disabled.  If you enable v-sync does the issue go away?

Note: it would be quite easy to make an option to enable v-sync for this project.

**Comment by Polymega** [comment] 2019-07-09 23:10
It might be? I enabled v-sync but it never worked. But looking back, that might be because I run the game in windowed mode and Nvidia control panel only makes it work for fullscreen? In any case, when I play the game on 60 FPS I have no tearing.

**Comment by solidcrash** [comment] 2019-07-09 23:36
I've checked the .ini file in the game folder and the fos limit is set at 30fps. Where can i change the fps in my pc?

**Comment by Polymega** [comment] 2019-07-09 23:57
You can change the FPS for the game to something higher like 60 in the meantime. The most obvious issue in doing this is that the shell casings from spent bullets will repeat very quickly. There's some other audio/visual anomalies from increasing the frame rate, but try increasing the FPS in the meantime to see if that resolves your screen tearing.

Remember you must close, make your INI edits, then relaunch the game to see the changes take effect.

**Comment by solidcrash** [comment] 2019-07-10 23:38
I've changed the value fps limit from 30 to 60 but nothing changed. The line still appear when i'm moving.

**Comment by Polymega** [comment] 2019-07-11 20:47
Hi @solidcrash,
We're gonna take a look into this some more and report back. Please allow us some time to research this. 

In the meantime, I'd recommend putting the game back at 30 FPS and tolerating the screen tearing for the time being.

**Comment by Polymega** [comment] 2019-07-16 20:34
@solidcrash 
Can you tell me what version of Windows (7, 8, 10?) you're using when playing the game?

**Comment by solidcrash** [comment] 2019-07-17 07:44
Windows 10

**Comment by elishacloud** [comment] 2019-07-18 01:53
@solidcrash, try setting `EnableWndMode = 0`.  This will allow the game to run fullscreen mode, which should have v-sync enabled.

**Comment by solidcrash** [comment] 2019-07-28 13:37
Tryed but no changes. Maybe even worst. Also, even when wndmode was = 1 the game was running in fullscreeb mode

**Comment by elishacloud** [comment] 2019-07-28 22:48
By default we set this to fullscreen windowed mode.  In windowed mode and fullscreen windowed mode vertical sync is controlled by the Windows Desktop Manager (WDM), so we have no control of it.

However, in exclusive fullscreen mode DirectX has control of vertical sync.  You should not be getting any screen tearing in exclusive fullscreen mode.  Your video card driver may be forcing vertical sync off.  I recommend checking your video card settings.

**Comment by solidcrash** [comment] 2019-07-30 22:26
I don't know if this is a problem but i've skip the directx 8 installation step, since I have a more update version already installed. However, I have a gtx 1080, can you tell me wich setting I need to change in my videocard? Is it called vertical sync?

**Comment by Polymega** [comment] 2019-07-31 17:53
Yup, it's called vertical sync. There's two places you can check to see if this is enabled/disabled through your GPU's control panel. I'll take screenshots of my Nvidia CP below, but your's may look a little different than mine. 

**1)** First, check to see if you disabled v-sync specifically for sh2pc.exe. In the control panel navigate: 

**Manage 3D Settings (link on left bar) > Program Settings (tab) > Select a program to customize: (dropdown list)**

Scroll through this dropdown list and see if sh2pc.exe is in this list. If it is, confirm v-sync is enabled for the game: 

![image](https://user-images.githubusercontent.com/27395260/62235135-4413e200-b39a-11e9-9ffb-18fcb1ef5680.png)

**2)** If you do not have a profile setup specifically for sh2pc.exe you could a) do that and force enable v-sync like in the picture above or b) confirm that v-sync is enabled _globally_ for your applications. Navigate: 

**Manage 3D Settings (link on left bar) > Global Settings (tab)**

![image](https://user-images.githubusercontent.com/27395260/62235229-7de4e880-b39a-11e9-8f92-5edd87366cf4.png)

You could change "User the 3D application setting" to "On" to force v-sync on all your apps. I'd recommend making a specific profile for sh2pc.exe first to see if that helps.

**Comment by solidcrash** [comment] 2019-08-02 15:38
Did everything, but nothing has changed. 
This problem only appears in the videoprojector. If I use my pc monitor, it's fine. Is it possible that this glitch, is in the screen because it's a lot bigger than the classic pc monitor?

**Comment by elishacloud** [comment] 2019-08-02 18:32
It should not have anything to do with the size of the screen/projector.

Vertical sync requires communication between the monitor and the video card.  For a normal monitor there is a slight delay of 1ms to 2ms for applications to write to the display before it starts showing the new image on the screen.  During this 1ms to 2ms is typically where you would do the flip/blt to show the new image and avoid screen tearing.

I don't know much about monitor technology, but it might be possible that either your projecter is unable to tell the video card when it is in vertical sync or the vertical sync time is too short and there is not enough time for the image to get switched before it starts showing the image.

I can create a build with some debug logs enabled to find out if we can get any vertical sync timing from the projector.  This would probably rule out at least some of these issues.

Are you seeing screen tearing from other games on this projector?

**Comment by solidcrash** [comment] 2019-08-02 19:57
I usually use the vpr only with ps3 and ps4. In that case, everything is perfect. I never play games with pc. This with Silent Hill is the first game i play connecting the pc with vpr

**Comment by elishacloud** [comment] 2019-08-03 03:03
@solidcrash, it's also possible that the drivers in Windows are not correct for your vpr.  You might need to install the Windows drivers for your vpr.

In the meantime, can you try with the attached module and then post your log file?  This will let me know if you can get the vertical sync information from your hardware.

Module: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3463335/d3d8.zip)

**Comment by Badore90** [comment] 2019-09-17 20:05
> I usually use the vpr only with ps3 and ps4. In that case, everything is perfect. I never play games with pc. This with Silent Hill is the first game i play connecting the pc with vpr

Have you checked the refresh rate on your control panel, where's the resolution setting??

I'm asking that 'cause it happened frequently to me when I connect my laptop to a Tv the first time. It set the refresh at 59p. So I change it to 60hz manually (I have to do it only the first time for any tv, since the PC remember the settings separately for each of them).

**Comment by elishacloud** [comment] 2020-04-29 04:04
Closing this out.

**Closed by elishacloud** 2020-04-29 04:04 UTC
