### ISSUE TITLE
Lock Speaker Config. Option (similar to screen resolution)

### ISSUE THREAD

**Issue by Polymega** [elishacloud/Silent-Hill-2-Enhancements#287] opened 2020-06-05 21:17 UTC
@belek666 
[Similar to your feature that locks the Screen Position option](https://github.com/elishacloud/Silent-Hill-2-Enhancements/pull/211), may I ask if the same can be done to lock the Speaker Config. option?

`01DBBFFB byte (speaker config selection)`

The idea is to show the _current_ selection within the Speaker Config. option, but prevent the player from changing this selection. In addition to this, also have a custom description at the bottom (same as what was done for the custom screen resolution fix).

Mock-up:

![image](https://user-images.githubusercontent.com/27395260/84081211-868b4f80-a9ab-11ea-87cf-051aeca6ae28.png)

----------------------------

The reason for this request is because, after Windows XP, [you can no longer change your speaker setup through a game.](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/287#issuecomment-640455970) It must be done through Windows' control panel. 

So if you play this game on Windows Vista or newer and change the Speaker Config. option in the game's menu, this selection will revert back to its original preset. This creates player confusion as the player does not understand why their selection change isn't saving.

Thank you!

**Comment by matt8928** [comment] 2020-06-07 16:20
I can use the 5.1 option and it doesnt revert back. I connect my pc to a av receiver and i use windows 10, it worked on windows 7 too.

**Comment by Polymega** [comment] 2020-06-07 17:26
Thanks for responding here. I believe you're the first person whose confirmed this setting can be changed and stay changed.

1. Do both your Win7 and Win10 PCs have dedicated audio cards?
2. How are you connecting your PCs to your AV receiver?
3. Is there a noticeable change in sound presentation when switching to 5.1? As in, does it actually present the sound in surround sound when you change it to that?
4. In the game, can you also switch the Speaker Config. to something like "Mono" or "Headphones" and those selections also stick?

Thanks

**Comment by matt8928** [comment] 2020-06-07 19:13
Wait, I remembered wrong, it is affected by the audio setting i choose in windows. If i set it to stereo before starting the game, its locked to stereo and same with 5.1. I can't change it in game so it must be broken for me to, because its supposed to overide the setting

Is it an issue for many to use 5.1, 7.1 even if its set to that in windows?

No they don't have a separate soundcard, i can use the audio from my graphics card or motherboard
I'm using the hdmi port on the graphics card directly to the receiver

Well almost every sound comes out of the rear speakers too except music and dialog.
footsteps, james panting or grunting, weapon sounds, enemy sound, radio static...

I'm using IndirectSound

**Comment by Polymega** [comment] 2020-06-07 22:03
> Is it an issue for many to use 5.1, 7.1 even if its set to that in windows?

I wouldn't think so, but I'm not sure. I've never been able to change it and having the setting stick. I've also never seen anyone else successfully change it.

>it is affected by the audio setting i choose in windows. If i set it to stereo before starting the game, its locked to stereo and same with 5.1

What setting are you changing in Windows to have the game automatically change its default Speaker Config?

> Well almost every sound comes out of the rear speakers too except music and dialog.
footsteps, james panting or grunting, weapon sounds, enemy sound, radio static...

I see. My AMD PC is hooked up to my living room setup, which uses 5.1. Even though I can only set the Speaker Config. in the game to "Stereo", I still hear sounds out of all my speakers. And like you, the dialogue and such only comes out of the front. So I don't know if changing the Speaker Config. in the game's options menu is making a difference? It might be IndirectSound helping out here.

In any case, I'm currently testing DSOAL and will also use DSOAL for my living room PC (with 5.1 surround) to see if it works correct here, too (even when the game sets the Speaker Config. to "Stereo"). I see no reason for this not to work, which means we'd still be okay to lock this option down to "Stereo" only. (Besides, a person can always disable this feature in the INI if they wish.)

**Comment by elishacloud** [comment] 2020-06-08 08:00
> I see no reason for this not to work, which means we'd still be okay to lock this option down to "Stereo" only.

What if we can fix the option so it works correctly?  Now that we have a full DirectSound wrapper, we should be able to add a fix for this.

**Comment by elishacloud** [comment] 2020-06-08 08:36
Microsoft's documentation on [this page](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/ee418050(v=vs.85)) says:

> In Windows Vista and later versions of Windows, SetSpeakerConfig is a NOP. For Windows Vista and later versions, the speaker configuration is a system setting that should not be modified by an application. End users can set the speaker configuration through control panels.

So, it seems that it is not possible for us to actually set this setting using DirectSound in the application on Vista or newer.  However, I can fake this API call so that the option will get remembered.  The advantage here is that this will still work on Windows XP.  However, on newer operating systems this option will appear to work, but it won't actually work.

Testing build: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4744754/d3d8.zip)

**Comment by matt8928** [comment] 2020-06-08 17:14
@Polymega
I configure it right here in control panel, see pics
Have you configured the audio in control panel to output 5.1, or some other software?
You might be right but i can't remember if i got sound out of the rear speakers before i started to use IndirectSound 

![audio setting](https://user-images.githubusercontent.com/25330261/84060176-0faa8280-a9bc-11ea-8430-762efab7ad90.jpg)
![audio setting2](https://user-images.githubusercontent.com/25330261/84060277-38327c80-a9bc-11ea-930a-ddbba506442c.jpg)

**Comment by Polymega** [comment] 2020-06-08 19:31
Thanks for the info, @matt8928.

I was able to test this myself. For me, switching my speakers to Quadraphonic and 5.1 Surround worked... these changes were reflected in the game's options menu. However, it did not work for me when I switched it to 7.1 surround.

![image](https://user-images.githubusercontent.com/27395260/84071032-11178300-a99b-11ea-97fa-d82e850aff24.png)

So thanks to both your's and Elisha's notes, we do know this feature still works in some capacity. It's just that, after WinXP, you must set this through Windows and not the game.

> However, I can fake this API call so that the option will get remembered. The advantage here is that this will still work on Windows XP. However, on newer operating systems this option will appear to work, but it won't actually do anything.

Thanks Elisha! But I think this would just further confuse players if they can change it but it doesn't actually affect the sound output. What do you think? I also think we shouldn't aim for WinXP compatibility (that, and someone could just disable the fix in the INI if they wish to play on XP).

Since we know more info about this now, I think we can approach this in a couple different ways:

## 1. Lock--but don't gray out--the Speaker Config. selection
For the screen resolution, we lock out the ability to change it (but don't gray it out) and use a custom string at the bottom that says, "Set screen resolution in d3d8.ini file"

Maybe we do the same for the Speaker Config. option? Lock it out (but don't gray it out) and use a custom string below that says something like "Change speaker config. in Windows"

This approach would still allow a user to properly change the Speaker Config., if they know what they are doing. (WinXP users could just disable the fix.) If someone doesn't know what they're doing, it can still lead to confusion.

![image](https://user-images.githubusercontent.com/27395260/84071432-b03c7a80-a99b-11ea-8a17-4cff7e82de85.png)

## 2. Fully lock out the Speaker Config. option
The original request of this ticket. Fully lock it (and gray it out) with the selection preset to "Stereo." This is the most straight-forward solution to prevent player confusion as to why their selection isn't sticking or why they hear no audio changes upon changing it in the game's options menu (if we were to fake it).

However, we limit the choice of what a user can change it to, assuming they know how to change the speaker configuration through Windows. (How common knowledge is this among the Windows user base? I didn't even know it myself till just now.)

Also, once we use DSOAL, the Speaker Config. selection in the game's options menu _might_ become a moot point?

## 3. Fake the selection change
Allow the user to change the selection and have the game remember it as you've done in the test build Elisha, but it doesn't actually do anything. I'm not a big fan of this one as it'd be fooling the player into a change that isn't actually happening.

-------------------------

Which approach should we go for? I favor # 1 or # 2. Maybe leaning more towards # 2 if DSOAL makes this selection irrelevant.

**Comment by elishacloud** [comment] 2020-06-08 20:40
> For me, switching my speakers to Quadraphonic and 5.1 Surround worked... these changes were reflected in the game's options menu. However, it did not work for me when I switched it to 7.1 surround.

I fixed this issue.  The problem is described in the [Microsoft documentation](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/ee418050(v=vs.85)).  The issue is that Windows is returning some value for 7.1 audio that the game cannot handle.  I just detect that value and change it to a value the game can understand.  Note: 5.1 audio may have the same issue so I put a fix in for that also.

New build:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4748441/d3d8.zip)

As far as the options, I agree that it may confuse the user to allow them to set an option that does not actually do anything.  However, I also think it is just as confusing to hard code this to "Stereo".  Instead, I recommend we show the correct value here and then prevent the user from modifying it.

I personally like option 1, we allow the user to see the option, similar to resolution, but not change the option.  Then we can add text to tell the user they can change the speaker setting in Windows.

**Comment by Polymega** [comment] 2020-06-08 20:59
> I personally like option 1, we allow the user to see the option, similar to resolution, but not change the option. Then we can add text to tell the user they can change the speaker setting in Windows.

Yeah, I think this one is the best, too. It still gives the user the option to change it (through Windows), but prevents them from unsuccessfully trying to change it through the game's options menu.

Okay! I'll update my original post/request for Belek666!

**Comment by elishacloud** [comment] 2020-06-08 21:23
@Polymega, while testing this I noticed another weird issue.  If I set the speaker to "Surround" on my computer than the game hangs on load.  All other speaker options work fine.  This only happens when using the DSound to OpenAL module.  Are you seeing the same issue?

**Comment by Polymega** [comment] 2020-06-08 21:29
Hmm... the game launched for me with 5.1, 7.1, and quadraphonic.

Try using [DSOAL 1.31a](https://www.nexusmods.com/newvegas/mods/65094?tab=files). Later builds of DSOAL [render the radio static incorrect](https://youtu.be/sLn98E16qCQ) so we will have to use this build in our project.

**Comment by elishacloud** [comment] 2020-06-08 21:34
> Hmm... the game launched for me with 5.1, 7.1, and quadraphonic.

Yes, 5.1, 7.1, and quadraphonic all work fine for me.  It is only "Surround" that has the issue.

![image](https://user-images.githubusercontent.com/25625456/84082487-c7c43500-a994-11ea-9041-43bff22076a8.png)

**Comment by Polymega** [comment] 2020-06-08 21:44
I see. I unfortunately don't have that option for my speaker config to test. [My options are limited for this selection.](https://user-images.githubusercontent.com/27395260/84071032-11178300-a99b-11ea-97fa-d82e850aff24.png) I'll test my AMD PC soon and see if I have the "Surround" option there.

**Comment by Polymega** [comment] 2020-06-09 00:23
I don't have the option to set any of my three PC's speakers to use "Surround."

**Comment by belek666** [comment] 2020-06-11 12:39
Hi
Something like that:
[Release.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4764753/Release.zip)
Description text is read from 'exe_str.txt' file.

**Comment by Badore90** [comment] 2020-06-11 13:08
> I personally like option 1, we allow the user to see the option, similar to resolution, but not change the option. Then we can add text to tell the user they can change the speaker setting in Windows.
> 
> Yeah, I think this one is the best, too. It still gives the user the option to change it (through Windows), but prevents them from unsuccessfully trying to change it through the game's options menu.
> Okay! I'll update my original post/request for Belek666!
> Edit: 7.1 surround selection now works/sticks in the game. Thanks Elisha!

When you select quadraphonic or 5.1 surrond can you actually hear the difference in game's audio?
It improves the directionality or sounds remains the same?? Obviously without using DSOAL.

Since sounds are recorded in MONO (and some in STEREO I think) they should remain the same, unless the game engine do something else to render a surround sound.

**Comment by Polymega** [comment] 2020-06-11 19:36
Thank you, Belek! Tested on all binaries with different INI features enabled/disabled and found no issues.

@Badore90 
> When you select quadraphonic or 5.1 surrond can you actually hear the difference in game's audio?
It improves the directionality or sounds remains the same?? Obviously without using DSOAL.

I'm not sure. I don't have a legitimate surround sound setup on my PC or TV. My PC uses stereo speakers and my TV uses a sound bar.

And while I can definitely hear an improvement with DSOAL while using headphones (as that's what DSOAL is meant for; binaural audio through headphones), I am by no means an audiophile, so I probably wouldn't be the best to answer this, anyways.

**Comment by Badore90** [comment] 2020-06-11 23:00
> Thank you, Belek! Tested on all binaries with different INI features enabled/disabled and found no issues.
> @Badore90
> 
> When you select quadraphonic or 5.1 surrond can you actually hear the difference in game's audio?
> It improves the directionality or sounds remains the same?? Obviously without using DSOAL.
> 
> I'm not sure. I don't have a legitimate surround sound setup on my PC or TV. My PC uses stereo speakers and my TV uses a sound bar.
> And while I can definitely hear an improvement with DSOAL while using headphones (as that's what DSOAL is meant for; binaural audio through headphones), I am by no means an audiophile, so I probably wouldn't be the best to answer this, anyways.

Ah ok, I thought you had a 5.1 set or something like that, because I can't even change those options (I have only stereo on Speaker setup screen if using PC speakers or head/hearphones).

![image](https://user-images.githubusercontent.com/44087144/84447388-1fd69200-ac48-11ea-8992-1220e59fdb67.png)

**Comment by Polymega** [comment] 2020-06-11 23:09
> Ah ok, I thought you had a 5.1 set or something like that,

I see why you'd think that. I have no clue why my Windows allows me to switch between stereo, quadraphonic, 5.1, and 7.1, because all I'm using is stereo speakers! 

My stereo speakers do include a sub woofer, so maybe Windows thinks I'm using a surround sound setup because of that? No idea...

**Comment by elishacloud** [comment] 2020-06-12 05:27
I will start out saying that I am not an audiophile either.  In fact, I play a lot of games with sound turned down so I can listen to other things (like an audio book, etc.) while I am playing some games.

However, I have a Denon AVR-2113CI configured with Polk Audio speakers in a 5.1 setup (my gaming room is not big enough for a proper 7.1 setup).  When I configure Windows to use stereo speakers Silent Hill 2 sounds somewhat flat, IMHO, and the rear speakers are never really used.  However, if I configure Windows properly to use 5.1 setup (there is more than one way you can configure a 5.1 speaker setup and you need to configure Windows to match your setup) then the sound in Silent Hill 2 sounds much fuller and I can hear sound from the rear speakers.

Note: I am using the latest testing build with DSOAL enabled.  The SFX still don't seem to be coming from any particular direction, like I think they should, but the overall sound quality is much better with 5.1 configured than with stereo.

**Comment by Polymega** [comment] 2020-06-20 23:28
@IlDucci @Badore90 
May I ask you two to translate the following line into your respective languages, using the least amount of words as possible?

> ### Set speaker config. through Windows

Thank you for your help

**Comment by IlDucci** [comment] 2020-06-21 10:00
Sure, in Spanish that would be:

> Configurar altavoces a través de Windows.

**Comment by Polymega** [comment] 2020-06-21 17:23
Thanks, IlDucci. Any chance to make it shorter?

![image](https://user-images.githubusercontent.com/27395260/85231067-3906dd80-b3c2-11ea-8cbb-7b5d2c384d17.png)

Maybe if we use a more generic line such as "Change setting through Windows" or "Change this setting in Windows"?

**Comment by IlDucci** [comment] 2020-06-21 17:59
Damn...

Nope, your first version would make things longer. The best way to shorten this would be "Configurar a través de Windows" or "Configurar en Windows".

**Comment by Polymega** [comment] 2020-06-21 18:22
That one will work!

![image](https://user-images.githubusercontent.com/27395260/85231747-c862bf80-b3c7-11ea-93ff-c6878c833449.png)

Given our limitations, do you think this is suitable for the Spanish version?

PS - This text string will be added to the external `ext_str.txt` file, so you won't have to worry about updating anything in your `.mes` files.

**Comment by IlDucci** [comment] 2020-06-21 18:28
That should be more than enough. Thank you!

**Comment by Badore90** [comment] 2020-06-22 12:51
> @IlDucci @Badore90
> May I ask you two to translate any of the following lines into your respective languages, with whichever version makes the shortest translation?
> 
> * Set speaker config. through Windows
> * Set in Windows sound control panel
> * Change setting through Windows
> 
> Thank you for your help

Configura attraverso Windows

**Comment by Polymega** [comment] 2020-06-22 20:06
Thanks, Badore90!

![image](https://user-images.githubusercontent.com/27395260/85330422-60cd7280-b4a2-11ea-88fc-88a881e8dc7c.png)

**Closed** 2020-06-22 20:07 UTC
