### ISSUE TITLE
Steam Link and Controller's Triggers Not Responding In-Game.

### ISSUE THREAD

**Issue by KojiKenshiro** [elishacloud/Silent-Hill-2-Enhancements#249] opened 2020-03-22 19:37 UTC
As the title says I'm trying to play the Silent Hill 2: Enhanced Edition via the Steam Link and my Wii U Pro Controller's triggers aren't responding in-game. I'd very much like to play this and Silent Hill 3/Silent Hill 4: The Room (and other Steam Games) via the Steam Link if possible? Any help on this matter will greatly be appreciated. Thank you and have a good day! :)

Edit: I did a bit of testing and I'm also unable to get the Triggers to respond in-game with a XBOX 360 or XBOX One controller that I have. Both are official Microsoft brand. They do function outside of the game just not once it is launched. You guys have done an amazing job at fixing/updating Silent Hill 2 on PC. You and the rest of the team have managed to bring Silent Hill 2 on PC to a level that makes it the definitive way to play this game and if you guys manage to implement the remaining fixes that you have planned, it will be THE way to play this great game. Thanks again and any help will be greatly appreciated and welcomed. Cheers! :) 👍

Edit: Upon further testing I can get the Triggers on my XBOX 360 and XBOX One controllers to function on my Desktop with a little configuration in the Controller Settings. I'd really like to be able to play it on the Big Screen instead of having to sit at my computer when I want to play Silent Hill 2 PC. I'm willing to help you guys troubleshoot the problem and possibly find a solution. Cheers!

**Comment by FluffyCake** [comment] 2020-04-06 03:28
I am also running into this issue.

Were you able to get the triggers working at all through launching via Steam with any controller?

I've tested it with Xbox One, PS4, and Nintendo Switch Pro controllers all to no avail.

It only seems to be the triggers for some strange reason too.

I've been tinkering with Steam's controller options to try to figure it out.

It's odd, running directly from Desktop (without Steam) seems to work just fine.

**Comment by Genroa** [comment] 2020-05-12 12:59
Same problem here, but I'm not using Steam. I'm starting the game with the executable. Xbox One controller triggers do not respond. They are mapped to stuff by default, but don't seem to work and if you unbind them you can't bind them to anything else because they aren't recognized.

**Comment by Teapsalm** [comment] 2020-05-12 23:37
I've also been waiting for a fix for this for a while now. My controller doesn't respond at all when launched through Steam Link, but works perfectly fine when launched on the PC itself.

**Comment by Polymega** [comment] 2020-05-13 05:29
I don't launch SH2 through Steam, so I can't test this myself. I'm not sure how many/if any others in the team launch it through Steam, either.

If I get a good break in the future from other tasks with the project (I'm not sure when that'll be), I can try and see if there's anything I can do to hopefully help/alleviate the issue.

**Comment by cesardt** [comment] 2020-06-08 03:04
I ran into this issue today and was able to solve it with GloSC (Was trying to setup a Steam Controller with a Link). This only happens when the any controller goes through Steam's Xinput emulator. With the workaround you'll lose the overlay, but will be able to play the game through the Link.

**Comment by nuckable** [comment] 2021-05-23 18:16
Just figured I'd chime in for people who struggle with this. I can confirm what @cesardt said and add a little more info.

The game initially ran perfectly fine with the Xinput Plus fix in standalone mode but once I added it to Steam and ran it through that, my triggers wouldn't work anymore (and the button mappins were all weird).

I was able to solve my problems by (closing the game) going into Big Picture Mode, opening the Controller Options for my custom Silent Hill 2 entry and setting the Steam Input Per-Game Setting to "Forced Off". After that I closed Big Picture mode and ran the game and it worked just as before.

So yeah, it seems like Steam's Xinput emulator conflicts with the one offered by the Enhanced Edition.
Oh and I didn't lose the overlay doing this either. If you tried to reconfigure the controls while in Steam you may want to overwrite the keyconf.dat file in the SH2 folder with the one from the Xinput Plus fix that EE offers.

Hope this helps!

**Closed** 2024-10-08 03:43 UTC
