### ISSUE TITLE
Flashlight shining through surfaces in Apartment Complex

### ISSUE THREAD

**Issue by SilentastheWinds** [elishacloud/Silent-Hill-2-Enhancements#318] opened 2020-09-30 20:48 UTC
I was loading a save from room 2F in the Apartment Complex, and noticed that some these walls were having the light from the flashlight passing through them
[Ex1](https://gfycat.com/meagerwelldocumentedhadrosaurus)
[Ex2](https://gfycat.com/likelyfaroffbobcat)
This issue was present during the encounter with Pyramid Head in the stairwell, where the light of the flashlight would be reflected by the water under the floor, noticeable when you can get the camera at the right angle.
[Ex](https://gfycat.com/angelicgargantuanchimpanzee)

**Comment by Polymega** [comment] 2020-09-30 21:08
Hi there, 

This is a limitation of the game engine, which is present on all versions of SH2 (except the HD Collection). It might be less noticeable on PS2 due to it using per-vertex lighting for the flashlight, which makes it harder to tell which polygons are affected by the flashlight.

This is most noticeable at the end of the Alternate Hospital chase sequence. When James gets up off the floor from the Hospital elevator, as he turns his body around, you'll see his light shine walls beyond the elevator walls.

Coincidentally, despite HD Collections _countless_ flaws, [this is one thing they managed to address](https://twitter.com/theRatiocinator/status/1186839931399954432). They added a custom shader to the game in an attempt to improve this problem. And while it managed to fix the flashlight shining through walls, it introduced other flashlight problems with it.

I'm going to close this ticket since it's not a bug/issue with our project, but an engine-wide limitation.

**Closed by Polymega** 2020-09-30 21:08 UTC
