### ISSUE TITLE
Invisible James on Resolution Change with `DynamicResolution`

### ISSUE THREAD

**Issue by Polymega** [elishacloud/Silent-Hill-2-Enhancements#455] opened 2021-08-27 16:57 UTC
I've had this happen to me one time before but could never figure out how to replicate it, so thanks to my friend Jack for figuring this out. There is a bug with `DynamicResolution` where, if you change the game's resolution through its options menu to any other resolution, James will be invisible ~~for this room only (Alternate Hotel Bar Kitchen)~~ in the Alternate Hotel Bar Kitchen and Stairway:

![Screenshot 2021-08-27 12-50-07](https://user-images.githubusercontent.com/27395260/131161742-28abfdc0-3572-496c-bc4b-95dc950e03a7.png)

[Video of it in action](https://youtu.be/H9Xc8IKYakU)

As far as we're aware, it's only in this room that this happens in.

We've disabled all other fixes we could think of that relate to this room, in the thoughts that maybe `DynamicResolution` is breaking another fix, but it appears to be something specifically with `DynamicResolution`.

**Comment by AeroWidescreen** [comment] 2021-09-04 18:57
Okay, I believe I know what the problem is. The [Widescreen Fix is programmed to read and subtract 0x10](https://github.com/ThirteenAG/WidescreenFixesPack/blob/c9b50fb5fc0457993130135f422d29bc9a5e5526/source/SilentHill2.WidescreenFix/dllmain.cpp#L570-L574) from two pointers for the original `LightingFix` code. It was done this way for compatibility reasons.

Because of the changes Elisha made to the Widescreen Fix for `DynamicResolution`, this code changes the pointer _each time_ the resolution is updated, making them invalid. 

Before Updating Resolution:
![Before](https://i.imgur.com/FJrz5nM.png)
![Before](https://i.imgur.com/7YBR2hA.png])

After Updating Resolution:
![After](https://i.imgur.com/uqptPMa.png)
![After](https://i.imgur.com/RVckOjC.png)


This issue could potentially affect other parts of the game as well. It needs to be  fixed as soon as possible. I suggest that @elishacloud update the Widescreen Fix so that it only runs this [LightingFix code](https://github.com/ThirteenAG/WidescreenFixesPack/blob/master/source/SilentHill2.WidescreenFix/dllmain.cpp#L570-L574) once at game launch.

**Comment by elishacloud** [comment] 2022-03-25 02:28
Good catch @AeroWidescreen!  I think I fixed the issue.

Try this testing build out: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8346858/d3d8.zip)

**Comment by Polymega** [comment] 2022-03-25 17:36
@AeroWidescreen 
I tested this and the pointers no longer change on resolution change, but can you confirm it's initially loading up right? I only ask as in your previous post:
> Before Updating Resolution:
> ![Before](https://i.imgur.com/FJrz5nM.png)
> ![Before](https://i.imgur.com/7YBR2hA.png])

When I checked this I'm off by 0x10 from what you posted.

![image](https://user-images.githubusercontent.com/27395260/160172502-fb5a26ba-e6d6-45ed-be71-098f2659157a.png)
![image](https://user-images.githubusercontent.com/27395260/160172422-72e294d9-a2e7-41de-8268-e8bd71b87d70.png)

PS - Aero_: With Elisha currently on this, are there any other fixes/features from WSF that may also have similar issues when changing the resolution or such? Or are we good after fixing this one thing?

**Comment by AeroWidescreen** [comment] 2022-03-29 02:21
Hey, didn't know Elisha was back already! Let's see...

> When I checked this I'm off by 0x10 from what you posted.

I checked the pointers without any mods installed and they look like this:
```
005036CB - mov ecx,[01F7D6AC]
004FFCFA - mov ecx,[01F7D6A8]
```
And now the pointers look like this with Elisha's new build.

```
005036CB - mov ecx,[01F7D69C]
004FFCFA - mov ecx,[01F7D698] 
```

So yes, it's working correctly. It's possible the pointers were already off by 0x10 in the older builds because of that  aforementioned coding error. Or maybe it was my own mistake.  Doesn't matter, it's fixed now.

> PS - Aero_: With Elisha currently on this, are there any other fixes/features from WSF that may also have similar issues when changing the resolution or such? Or are we good after fixing this one thing?

We're good.

**Comment by ThirteenAG** [comment] 2022-03-29 16:48
Merged!
Btw, on a totally unrelated note, I am now working on a possibility to have game plugins in pcsx2, so if you wanted to do something with PS2 version of the game and didn't want to deal with pnach and other limitations, you can now have custom code: https://github.com/ThirteenAG/PCSX2PluginInjector

**Closed as completed** 2022-03-29 16:56 UTC

**Comment by elishacloud** [comment] 2022-03-29 17:14
Thanks @ThirteenAG!

Here is the latest build with all the updates: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8373612/d3d8.zip)
