### ISSUE TITLE
0xc000007b error when trying to open game.

### ISSUE THREAD

**Issue by kje32** [elishacloud/Silent-Hill-2-Enhancements#286] opened 2020-05-31 03:37 UTC
I've tried everything now and no matter what I do I cant get the game to open. Just keep getting this error non stop. My DirectX is up to date as well as my C++.

**Comment by Polymega** [comment] 2020-05-31 03:46
Can you share a snapshot of the game's directory?

**Comment by kje32** [comment] 2020-05-31 03:59
![Capturesh](https://user-images.githubusercontent.com/66192188/83344212-9f23a780-a2d1-11ea-82ce-fc31aa99028f.JPG)
@Polymega

**Comment by kje32** [comment] 2020-05-31 04:01
@Polymega 
![Capture112](https://user-images.githubusercontent.com/66192188/83344236-e6119d00-a2d1-11ea-9252-095bab72ae53.JPG)

**Comment by Polymega** [comment] 2020-05-31 04:14
Thank you. To start, move the `sound\` folder to `sh2e\`. The Audio Enhancement Pack files should be stored in `Silent Hill 2\sh2e\sound\`.

Then, try doing the following, one-at-a-time with game launches in between, to see if the game will launch for you:

- Set `d3d8to9 = 0` in the `d3d8.ini` file
- Temporarily remove the `dsound.dll` file

**Comment by kje32** [comment] 2020-05-31 04:20
> 
> 
> Thank you. To start, move the `sound\` folder to `sh2e\`. The Audio Enhancement Pack files should be stored in `Silent Hill 2\sh2e\sound\`.
> 
> Then, try doing the following, one-at-a-time with game launches in between, to see if the game will launch for you:
> 
>     * Set `d3d8to9 = 0` in the `d3d8.ini` file
> 
>     * Temporarily remove the `dsound.dll` file

I started with the d3d8to9 = 0 and that didnt work. Then I removed the dsound.dll and it worked! Thank you! Should I change the d3d8to9 = 1 and try it? Also, is removed the dsound.dll file going to effect anything? Thanks for the help!

**Comment by Polymega** [comment] 2020-05-31 04:30
Great! I had a hunch it was `dsound.dll` but wanted to confirm.

The `dsound.dll` file is from IndirectSound. IndirectSound requires [the Microsoft Visual C++ 2010 Redistributable Package (x86)](https://www.microsoft.com/en-us/download/details.aspx?id=5555) to be installed to work. Ensure you have this package installed. If you didn't, install it then try putting the IndirectSound files back in the directory to see if the game launches.

We primarily use IndirectSound because, in the game, if a sound file ends prematurely the game doesn't fade out the audio, so you'll hear a "click" or "pop" when the audio ends early. IndirectSound fixes this for the sound effect (SFX) files in the game.

However, we are making an integrated fix for this that covers _all_ audio in the game, and is planned to be released in our next project update.

In the meantime, let me know if installing the Microsoft Visual C++ 2010 Redistributable Package fixes that error for you when placing the IndirectSound files in the game's directory.

**Comment by Polymega** [comment] 2020-05-31 04:33
Sorry, forgot to mention:

> Should I change the d3d8to9 = 1 and try it?

For now with our project, you only need to enabled d3d8to9 if you plan to use ReShade. ReShade requires the game to be ran in DirectX 9, which is what d3d8to9 (converts the game from DirectX 8 to 9).

**Comment by kje32** [comment] 2020-05-31 04:36
> 
> 
> Great! I had a hunch it was `dsound.dll` but wanted to confirm.
> 
> The `dsound.dll` file is from IndirectSound. IndirectSound requires [the Microsoft Visual C++ 2010 Redistributable Package (x86)](https://www.microsoft.com/en-us/download/details.aspx?id=5555) to be installed to work. Ensure you have this package installed. If you didn't, install it then try putting the IndirectSound files back in the directory to see if the game launches.
> 
> We primarily use IndirectSound because, in the game, if a sound file ends prematurely the game doesn't fade out the audio, so you'll hear a "click" or "pop" when the audio ends early. IndirectSound fixes this for the sound effect (SFX) files in the game.
> 
> However, we are making an integrated fix for this that covers _all_ audio in the game, and is planned to be released in our next project update.
> 
> In the meantime, let me know if installing the Microsoft Visual C++ 2010 Redistributable Package fixes that error for you when placing the IndirectSound files in the game's directory.

![Capture77](https://user-images.githubusercontent.com/66192188/83344577-a6997f80-a2d6-11ea-8e0d-eb684230cbc6.JPG)

I have a bunch of them installed due to another game I was having an error with. Not sure why it isn't working. All the files are in the correct place in the directory right?

**Comment by Polymega** [comment] 2020-05-31 04:45
> All the files are in the correct place in the directory right?

Upon moving `sound\` to the `sh2e\` folder everything in your game's main directory looks good. I'm not sure about the structure within your `sh2e\` folder as I can't see it, [but it should look like this.](http://enhanced.townofsilenthill.com/SH2/install.htm#directoryTree)

Since IndirectSound isn't playing nice for you, try out a test build of our project that incorporates our built-in audio click/pop fix:

1. Remove the IndirectSound files from the game's directory (`dsound.dll` and `dsound.ini`)
2. Download project test build with built-in audio click/pop fix: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4680183/d3d8.zip)
   - Place files in game's main directory
   - Edit settings within the `d3d8.ini` file like normal

**Comment by kje32** [comment] 2020-05-31 19:22
> 
> 
> > All the files are in the correct place in the directory right?
> 
> Upon moving `sound\` to the `sh2e\` folder everything in your game's main directory looks good. I'm not sure about the structure within your `sh2e\` folder as I can't see it, [but it should look like this.](http://enhanced.townofsilenthill.com/SH2/install.htm#directoryTree)
> 
> Since IndirectSound isn't playing nice for you, try out a test build of our project that incorporates our built-in audio click/pop fix:
> 
>     1. Remove the IndirectSound files from the game's directory (`dsound.dll` and `dsound.ini`)
> 
>     2. Download project test build with built-in audio click/pop fix: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4680183/d3d8.zip)
>        
>        * Place files in game's main directory
>        * Edit settings within the `d3d8.ini` file like normal
@Polymega 
Hey thanks again! I re enabled d3d8to9 to = 1 again and downloaded the files from the link you posted and put them in the directory and the game is still booting up without an error! Haven't tried playing yet, gonna do that tonight. But so far everything seems to be good. One more thing when I boot the game up it tells me in the top left corner that Reshade has an update available. Is that something I should look into or...? Thanks again!

**Comment by Polymega** [comment] 2020-05-31 21:16
> One more thing when I boot the game up it tells me in the top left corner that Reshade has an update available. Is that something I should look into or...?

You can ignore the update message for ReShade. We plan to integrate our own shaders into the project (what ReShade currently does for us) and hope to release it in our next update, which will fully remove ReShade from the installation process at that time.

**Comment by kje32** [comment] 2020-05-31 22:13
> 
> 
> > One more thing when I boot the game up it tells me in the top left corner that Reshade has an update available. Is that something I should look into or...?
> 
> You can ignore the update message for ReShade. We plan to integrate our own shaders into the project (what ReShade currently does for us) and hope to release it in our next update, which will fully remove ReShade from the installation process at that time.

@Polymega 

Okay. Should I wait for the next release you guys have before starting a game? Is there gonna be any really noticeable changes and stuff or just some under the hood changes? And if so, when are you guys expecting to release around? Thanks!

**Comment by Polymega** [comment] 2020-05-31 22:56
There's never a set time until the week of for releases, because we all work on this on our spare times when able.

And you're good to play the game now, especially as we don't know when the next release will be. We don't know everything that's planned to be included in the next release, but most things prepared so far are under the hood things or minor quality-of-life changes.

**Comment by onoderaSecurity** [comment] 2020-06-20 15:14
Can confirm and reproduce that IndirectSound is also being bad for me, having it installed never let the game launch. I had it along with other SH2E components installed and it played nice, but somewhere along the line it broke. May be related to Windows 10 updates (currently running 2004 build 19041.329).

**Comment by Polymega** [comment] 2021-03-24 21:15
Hi all,
We've switched from IndirectSound to DSOAL for the project. If you haven't already, try using this new audio solution. I'll close this ticket. Feel free to make a new one if DSOAL is also giving you troubles.

**Closed by Polymega** 2021-03-24 21:15 UTC
