### ISSUE TITLE
Game breaking FPS and stuttering

### ISSUE THREAD

**Issue by CousinV** [elishacloud/Silent-Hill-2-Enhancements#137] opened 2019-06-16 18:09 UTC
Just installed SH2 and the Enhancements and went to start a new game only to find that the FPS is game-breakingly low with some stuttering. Any ideas for a fix?

**Comment by Polymega** [comment] 2019-06-16 18:12
Hi @CousinV,

Try some of the recommended solutions under the Troubleshooting section titled, "_The game runs slow only during outside segments (while in the town)_" and "_The game runs slow in general_":
http://enhanced.townofsilenthill.com/SH2/#troubleshooting

If you're still experiencing stutter after trying these solutions then please attach your `d3d8.log` and `d3d8.ini` files in your response. 

Thanks

**Comment by CousinV** [comment] 2019-06-16 18:24
Much thanks for the quick response. I've tried what the troubleshooting guide suggests but it still runs very slowly. The lag seems to occur immediately after pressing the new game button and the cutscene starts.

**Comment by CousinV** [comment] 2019-06-16 18:55
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3294468/d3d8.log)
[d3d8.txt](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3294469/d3d8.txt)

Here's my LOG and my INI. INI being converted to text for ease of upload.

**Comment by CousinV** [comment] 2019-06-16 19:15
Finally! Found a fix. It was the single core affinity all along. I may be subjected to some looping, but at least it's playable.

**Comment by Polymega** [comment] 2019-06-16 19:44
Glad you pin-pointed the source. Do not the sound looping is very prevalent and will make for a bad time while playing. Also, once you start hearing the looping that typically means the game will crash/freeze upon trying to fully exit the game. 

It's strongly advised to run the game on a single core. If you're experiencing issues with our single core affinity fix through the project, you can disable it like you did and manually set the core _after_ game launch through Windows' Task Manager. 

Here's how to do that in Windows 10: https://www.windowscentral.com/assign-specific-processor-cores-apps-windows-10

**Comment by Polymega** [comment] 2019-06-17 18:36
@CousinV 
Interestingly, I [updated my Windows 7 machine](https://www.laptopmag.com/articles/nsa-update-windows-bluekeep) today and now experience the same problem. When I disable single core affinity through the d3d8.ini file it also runs smoothly again.

**Comment by Polymega** [comment] 2019-06-18 00:09
@CousinV 
It may not necessarily be the single core affinity. I thought this was the cause for me, too. And sure enough, if I disable that fix it runs smoothly (until it inevitably crashes due to thread locking). 

**But I set sh2pc.exe's priority to "high"** (instead of normal) in the Task Manager's "Processes" tab and things seem to be fine. I haven't done a full play through with it yet, but FMVs that were _constantly_ stuttering/lagging were fixed. 

@elishacloud could setting the program's priority to "high" be something that can be integrated into the project, so the common user wouldn't have to worry about that?

**Comment by elishacloud** [comment] 2019-06-18 04:27
> @elishacloud could setting the program's priority to "high" be something that can be integrated into the project, so the common user wouldn't have to worry about that?

Yes, I created a build to set the process priority to high.  You can download the build here: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3299750/d3d8.zip)

**Comment by elishacloud** [comment] 2019-06-18 06:07
> If you're experiencing issues with our single core affinity fix through the project, you can disable it like you did and manually set the core after game launch through Windows' Task Manager.

This should not be needed.  Users should not need to update the affinity after the game is running.  I created a build that will simulate this for the user.  This build should be the same as manually setting the option via the Windows Task Manager.

You can download the updated build here: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3299986/d3d8.zip)

**Comment by Polymega** [comment] 2019-06-18 18:04
> Yes, I created a build to set the process priority to high. You can download the build here:

Thank you, Elisha! So I did a more thorough play test and setting the game to run at high process priority results in audio lag/stuttering/skipping throughout regular gameplay. So while it helps with FMV playback, it hurts audio just about everywhere else. 

For that reason, I'd recommend **not** including such a fix in the project's package. Thank you for allowing me to experiment more with this.

@CousinV 
I have a very important question to ask you with your issues of stuttering/lag: When you launch the game from a fresh PC reboot, does the game launch for you the first time? Or do you typically have to try and launch the game twice before it'll boot up?

**Comment by CousinV** [comment] 2019-06-20 03:17
Sometimes i have to relaunch it to get it booting up, but other than that it works fine.

**Comment by Polymega** [comment] 2019-06-20 03:30
Okay, we had the same problem then. It's a fault with a Windows Update. I made Elisha aware of this so he may try to find a built-in solution for our project. But to fix this in the meantime: 

1. Ensure the game (and probably no other game is currently running). 
   - To be sure, open your Task Manager and make sure "sh2pc.exe" isn't running under the "Processes" tab (or Windows 10 equivalent). End the process if you see it. **To play things safe, you could restart your computer and run the BAT before opening any game.**
2. Download the BAT script from this website: http://ubeogesh-things.blogspot.com/2012/08/resolve-it-finally-game-explorer-aka.html
3. Run the BAT script as adminstrator.
4. Press any key within the script.
   - This will rename `gameux.dll` to prevent it from launching/running when booting up SH2 PC. `gameux.dll` is the cause of our problems. It makes the game run slow/stutter, prevents it from booting on first attempt, and also maxes out CPU cores.
5. If you ever want to restore the `gameux.dll` file, ensure Step 1 is done and re-run the BAT script as admin again. Every time you run the BAT script it'll toggle from renaming/restoring the `gameux.dll` file.

**Comment by Polymega** [comment] 2019-06-20 03:31
Oops, bad typo on Step 1: Ensure the game (and probably no other game) is **NOT** currently running.

**Comment by elishacloud** [comment] 2019-06-22 02:06
@CousinV, I put a fix in for this issue.  Try with this update: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3316444/d3d8.zip)

**Comment by otherveteran** [comment] 2019-06-23 04:40
I just updated the last reshade updates on the enhancements project, and while previouslly I could use a high value of fog resolution and had normal gameplay and cinema playbacks, now I had to lower the resolution on the fog, so I could play at 30 fps.
Akso, i have to use coreafinnity=0 to eliminate the stutter on the cutscenes.
On the other hand, since I updated the enhancements, the first time I boot the gane it wont start I have to close it from the task manager and launch it again.
Lastly I wanna express my thanks and admiration for the great project you guys have.

**Comment by Polymega** [comment] 2019-06-23 07:24
Hi @otherveteran, 

We believe this is an issue caused with a Windows Update. Would you try downloading the latest test build of our project and tell us if this fixes the lag/stuttering you're experiencing? 

https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3316444/d3d8.zip

You can keep all normal settings as they are (enable SingleCoreAffinity, ReShade, Fog Fix, etc).

**Comment by otherveteran** [comment] 2019-06-23 19:29
After downloading the test build and installing it, I rebooted my pc, left the settings as they were, booted the game and it launched at the first try. 
The cinemas run smoothly now and the fps during gameplay seems stable ocasionally droping one frame (aparently when I press the esc key and just as the cinema starts but only for a sec).
Next I tested with a much higher vaule of fog resolution (2560) and the cutscenes and gameplay ran just fine.
Thanks again for the great work, also, should I keep using this test build, or wait for the official release?

**Comment by Polymega** [comment] 2019-06-23 19:35
Great! Keep using the test build for now. The test build has everything the latest public release has, but with the added benefit of the lag/stuttering fix. 

We plan to release an official, public update that includes this fix in the upcoming days. The next update won't have any additional game improvements as we're pushing this one out ASAP solely to alleviate the lag/stuttering problem that's only going to get worse as more people update their Windows.

**Comment by Polymega** [comment] 2019-06-24 16:59
@otherveteran can you tell me what version of Windows you're using?

**Comment by otherveteran** [comment] 2019-06-24 18:36
Windos 7 pro, latest updates, but I have disabled some older ones.

**Comment by otherveteran** [comment] 2019-06-27 19:55
@Polymega I have encountered another issue with the cinemas playback, I dont know if it is a known issue or not.

I started playing the game with the last public build of the enhancement pack you released, thats when I encountered the issues I described in my previous post, what I had also discover is that sometimes at the end of a cinema the game would just hang, and I had to close it via the task manager. **I am using the North AMerican executable of the game.**

Now, with the test build you so kindly provided I started playing some cinemas through the movies options and during gameplay, but I still get the occasional hang. As I mentioned before the low fps and the cinema stuttering issues were solved, but I still encountered this one.

I dont know if they are related or if it is a known issue from past builds (I just started playing the enhanced version this past weekend) but I felt I had to let you know so you can continue improving this amazing project.

**Comment by Polymega** [comment] 2019-06-28 05:53
@otherveteran 
The next time is freezes/hangs on you can you send us a dump file? 

1. Open Task Manager.
2. Go to the Details tab.
3. Right-click on the sh2pc.exe process.
4. Select the "Create dump file" option.

![test](https://user-images.githubusercontent.com/25625456/49752770-33c1c200-fc66-11e8-8866-fee87f12b3eb.png)

**Comment by Polymega** [comment] 2019-06-28 05:55
Also, before you mentioned **disabling** the SingleCoreAffinity fix. To be sure: Did you **re-enable** that feature? It's important that you do.

**Comment by otherveteran** [comment] 2019-06-28 06:29
@polymega 

Windows 7 Ultimate, yes, I have enabled singlecoreaffinity (used the default settings you provided).

I'll get you the dump file, the hang always happens just as the cinema ends.

**Comment by elishacloud** [comment] 2020-04-29 04:03
Closing this out.

**Closed by elishacloud** 2020-04-29 04:03 UTC
