### ISSUE TITLE
The game doesn't launch

### ISSUE THREAD

**Issue by Voromsira** [elishacloud/Silent-Hill-2-Enhancements#232] opened 2020-02-26 23:47 UTC
Hello !
I just updated the latest files and I now find myself unable to launch the game.
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4258752/d3d8.log)

I would gladly give more details but I'm not sure what to say. It's 100% repeatable, and I never had issues with the previous version of the mod. I followed the instuctions with attention but no luck.

In one of my attempts I did this : installed the "vanilla" game, launched just to check if it works normally (I did), then dragged and dropped the US 1.0 .exe just to see if the game worked (again, it would launch)...

...however, putting the d3d8 files made the game unable to launch.

**Comment by Polymega** [comment] 2020-02-27 00:32
Thanks for testing some things out early.

1. Can you share a screenshot of your game's main directory? 

2. When you placed the [SH2 Enhancements module ](http://enhanced.townofsilenthill.com/SH2/install.htm#installSH2Enhancements)files in your game's directory, you said that is when the game no longer launched. Can you place those files back in the game's directory, open the `d3d8.ini` file, set the following, and then see if the game launches?

   - `d3d8to9 = 0`
   - `AutoUpdateModule = 0`

3. Did you already install [IndirectSound](http://enhanced.townofsilenthill.com/SH2/install.htm#installIndirectSound) as well when you started experiencing troubles?

**Comment by Voromsira** [comment] 2020-02-27 01:06
Hello Polymega, thank you for your assistance.

1) Here's the screenshot :
![Sans titre-1](https://user-images.githubusercontent.com/61523827/75402213-8f787980-5904-11ea-8998-0f690b19ef4e.jpg)

2) Correct, the game launched successfully when only the vanilla files were in, or when only the recommended .exe had been added. Deactivating d3d8to9 and AutoUpdateModule, as suggested, did work, and the game launched normally !

3) No, IndirectSound wasn't installed yet.

After the success of your suggestion, I tried proceeding with the installation, checking every step to see if the game would work. So, as per the official guide, the next step was putting the essential files (sh2e folder, settings.ini, local.fix and device.fix) in the main folder. After that, I tried launching the game again, and it wouldn't start.

Just like before, when it would fail to launch seemingly because of the d3d8 enhancement files, the .exe or process doesn't appear in my task bar, however I am unable to move it or delete it, and Windows tell me the .exe is currently in use.

**Comment by Polymega** [comment] 2020-02-27 06:06
> Deactivating d3d8to9 and AutoUpdateModule, as suggested, did work, and the game launched normally !

`d3d8to9` requires you to have the DirectX 9 SDK. Can you ensure you have this SDK installed?
https://www.microsoft.com/download/details.aspx?id=35

> If I attempt to launch the game and it fails, nothing seems to happen.

The `AutoUpdateModule` will bring up a message box saying there's an update for the SH2 Enhancement module (if an update is available). If you click Cancel on this window the game will still launch. To be sure: Do you still have `AutoUpdateModule` enabled and are sure this window isn't up somewhere and/or making an instance of the game already run for you?

> So, as per the official guide, the next step was putting the essential files (sh2e folder, settings.ini, local.fix and device.fix) in the main folder. After that, I tried launching the game again, and it wouldn't start.

Hmm... I don't know why the game would launch with _just_ the SH2 Enhancements module, but not when also using the Essential Files. To be sure: You didn't **de**activate fixes such as `EnableSFXAddrHack` or `EnableTexAddrHack`, correct?

**Comment by Voromsira** [comment] 2020-02-27 10:56
> `d3d8to9` requires you to have the DirectX 9 SDK. Can you ensure you have this SDK installed?
> https://www.microsoft.com/download/details.aspx?id=35

Yes, it is already installed.
 
> The `AutoUpdateModule` will bring up a message box saying there's an update for the SH2 Enhancement module (if an update is available). If you click Cancel on this window the game will still launch. To be sure: Do you still have `AutoUpdateModule` enabled and are sure this window isn't up somewhere and/or making an instance of the game already run for you?

I've never seen the AutoUpdateModule window, even when the mod used to work, so I'm not sure what I am supposed to see. As far as I know, you'd just click the shortcut and the game would launch. No launcher window, no updater. I deactivated AutoUpdateModule (as per your suggestion) for the sake of troubleshooting but I will enable it again.

> Hmm... I don't know why the game would launch with _just_ the SH2 Enhancements module, but not when also using the Essential Files. To be sure: You didn't **de**activate fixes such as `EnableSFXAddrHack` or `EnableTexAddrHack`, correct?

Nope, I didn't deactivate those. I'm not sure where they are and I would have no reason to do so.
I'm reinstalling fresh for the 20th time now and I'll await further instructions. I hope you can help me solving this.

**Comment by Polymega** [comment] 2020-02-27 19:29
I'm really scratching my head on this one. Your log file doesn't show any errors... it just stops at `4764 00:40:26.124 Silent Hill 2 Enhancements module loaded!`

The files in your game's install directory look to be fine, and you've also stopped adding files upon the SH2 Enhancements module step where you're having launch issues.

You've ensured you've installed the DirectX 9 SDK and are not using IndirectSound yet.

The directory in which the game is installed (`D:\Silent Hill 2\`) is a clean file path so there should be no issues there, either.

The game launched when you disabled `d3d8to9` and/or `AutoUpdateModule` but stopped launching again upon placing the Essential Files package in the directory.

We'll definitely need @elishacloud's opinion on this one...

**Comment by Voromsira** [comment] 2020-03-01 18:28
> 
> 
> I'm really scratching my head on this one. Your log file doesn't show any errors... it just stops at `4764 00:40:26.124 Silent Hill 2 Enhancements module loaded!`
> 
> The files in your game's install directory look to be fine, and you've also stopped adding files upon the SH2 Enhancements module step where you're having launch issues.
> 
> You've ensured you've installed the DirectX 9 SDK and are not using IndirectSound yet.
> 
> The directory in which the game is installed (`D:\Silent Hill 2\`) is a clean file path so there should be no issues there, either.
> 
> The game launched when you disabled `d3d8to9` and/or `AutoUpdateModule` but stopped launching again upon placing the Essential Files package in the directory.
> 
> We'll definitely need @elishacloud's opinion on this one...

I'm willing to run more tests if that can help you or if that can ensure I'm not doing something stupid that prevents the game and mods from working.

Should I contact elishacloud somehow or just hope he comes and becomes interested in my issue ?

...also, is there any way I can put my hands on the previous version of the files so I can resume playing in the meantime, and hope it gets fixed in the future ?

**Comment by Polymega** [comment] 2020-03-01 23:46
> Should I contact elishacloud somehow or just hope he comes and becomes interested in my issue ?

No worries there. He's taking a well-deserved break at the moment, after working his tail off at the final hour to launch the latest release of the project.

In the meantime...

> ...also, is there any way I can put my hands on the previous version of the files so I can resume playing in the meantime, and hope it gets fixed in the future ?

You can use the previous public release of the SH2 Enhancements module here:
https://github.com/elishacloud/Silent-Hill-2-Enhancements/releases/tag/v1.3.1365.0
(Download the d3d8.zip package)

If you do this, you'll need to use older versions of files found within the Essential Files package. So try this download, as well: 
http://www.igotaletter.com/temp/sh2pc/temp_files_2020-03-01.zip

This is because you can't use the new, high res main menu/save screen textures when using an older build of the SH2 Enhancements module, as the older builds of the module don't support the high res textures.

**Comment by Polymega** [comment] 2020-03-01 23:48
Before you do all this... by chance, are you force enabling anti-aliasing through your GPU's control panel? Either as a specific forced anti-aliasing for SH2 PC, or perhaps as a global setting for all your PC games?

**Comment by Voromsira** [comment] 2020-03-02 09:53
> 
> 
> Before you do all this... by chance, are you force enabling anti-aliasing through your GPU's control panel? Either as a specific forced anti-aliasing for SH2 PC, or perhaps as a global setting for all your PC games?

No, I never set up profiles in my GPU control panel, I always use the application settings (except some rare cases where I need to force vsync or something but it rarely works out anyway.

Thanks a lot for the files. At least I can resume playing.

I will gladly run more tests if you guys are interested in solving it for more users (hoping I'm not the only one it'll benefit)

**Comment by elishacloud** [comment] 2020-03-08 08:30
@Voromsira, can you try with this update: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4302984/d3d8.zip)

**Comment by Voromsira** [comment] 2020-03-08 11:11
> @Voromsira, can you try with this update: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4302984/d3d8.zip)

Hello @elishacloud , thank you for your attention. I have tried, it still doesn't work.

1) I made a fresh install and launched the vanilla game, just to check -> the game launches normally.
2) I replaced the .exe with the 1.0 NA version provided -> the game launches normally.
3) I put the d3d8 files you provided today -> nothing happens. The game doesn't launch, this [d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4303102/d3d8.log) is created.

4) After rebooting, I try again, this time after setting _d3d8to9_ and _AutoUpdateModule_ to 0. Nothing happens, and this [d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4303103/d3d8.log) is created.

**Comment by elishacloud** [comment] 2020-03-09 01:08
Try disabling the following settings:
* D3d8to9
* AutoUpdateModule
* UseCustomModFolder
* Nemesis2000FogFix

If that does not work, try using this ini file: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4304207/d3d8.zip)

**Comment by Voromsira** [comment] 2020-03-09 14:40
Deactivating those settings didn't help. This [d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4307210/d3d8.log) was created.

**Comment by BakiVernes** [comment] 2020-03-24 18:01
I'm having the same problem as @Voromsira and I tried all the steps mentioned above.

**Comment by Polymega** [comment] 2020-03-24 19:15
Can you run down the list of these troubleshooting steps:
http://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#the-game-freezeshangs-upon-launch

Where did you obtain your copy of the game?

**Comment by Voromsira** [comment] 2020-04-07 11:02
> 
> 
> Can you run down the list of these troubleshooting steps:
> http://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#the-game-freezeshangs-upon-launch
> 
> Where did you obtain your copy of the game?

Hello, Polymega. Sorry I couldn't reply earlier - life happened and I got distracted by other games.

I did follow the troubleshooting steps. As for the two prerequisite, they both were already installed or told me I already had a more up-to-date version installed.

As for where my SH2 copy comes from, I can't say I remember where it came from. All I know is I've had it for a while and it worked perfectly with previous versions of the Enhanced Edition packages.

**Comment by elishacloud** [comment] 2020-04-09 06:54
Hello @Voromsira, try with this ini file.  This just disables all the none critical settings to see if the issues is related to one of these settings:

[d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4454503/d3d8.zip)

**Comment by comus777** [comment] 2020-04-21 11:16
Had this issue as well. The disabled .ini file posted by @elishacloud worked so I went into the .ini file to try and see exactly which setting was causing problems. It seems like (for my case at least, which mirrors the OP's problem) the "Uses custom files in the 'sh2e' folder" and the "Enables the Nemesis2000 Fog Fix module" are the root of the problem, and disabling them causes the game to launch properly. Kinda sucks about not being able to use those features though.

**Comment by elishacloud** [comment] 2020-04-21 18:07
@comus777, the reason that Nemesis2000 Fog Fix is not working is because it requires "Uses custom files in the 'sh2e' folder".  I believe the real issue here is the API hooking module used to support the sh2e folder.

I would like to troubleshoot this more.  I will send you an updated debug logging build later.

**Comment by comus777** [comment] 2020-04-21 23:13
What you're saying might be right because I experimented with manually transferring all the files in the sh2e folder into the data folder and that runs flawlessly. So it seems like the problem is with the sh2e folder rather than any of the content in it.

**Comment by elishacloud** [comment] 2020-04-23 00:45
Ok, I created an update that has a bunch of extra logging.  Can you try this build and send me the log file?

Updated build:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4519616/d3d8.zip)

**Comment by jondelara** [comment] 2020-04-23 04:04
Hi @elishacloud, I was having a similar issue as the others where I had to disable both **d3d8to9** and **UseCustomModFolder** . The updated build you just posted appears to have resolved the issue with the game launching. Thank you.

**Comment by elishacloud** [comment] 2020-04-23 04:09
@jondelara, That build should not be used for extended periods of time.  It does too much logging.  That is just for debugging.  Please use this build instead.

New build: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4520174/d3d8.zip)

**Comment by Polymega** [comment] 2020-04-23 04:32
Elisha always working his awesome magic! 

@Voromsira and @comus777 
If you guys wouldn't mind trying Elisha's test build above as well to also see if it fixes the problem for you, that'll help us get a bigger testing pool to help ensure all is well.

**comus777:** Remember to place the "sh2e" files back into the `sh2e` folder, and restore the original files back into the `data` folder, if/when you test.

**Comment by comus777** [comment] 2020-04-23 12:51
Yep, this works. Thanks for that.

**Comment by Voromsira** [comment] 2020-04-30 23:15
> 
> 
> Hello @Voromsira, try with this ini file. This just disables all the none critical settings to see if the issues is related to one of these settings:
> 
> [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4454503/d3d8.zip)

Hello @elishacloud, I apologize for not replying earlier, I was pretty busy with the quarantine and also moved on onto other games because of my frustration. I have just tried this latest d3d8.ini in conjunction with the normal .dat and .dll, and this time, the game does launch.

However, none of the improvements brought by the mods are applied, as if the game was just the vanilla trainwreck - I assume that's the point of this .ini, deactivating all that's brought by the enhancement suite ?

I'm ready to resume troubleshooting if you guys still have time to spare for this issue.

**Comment by Polymega** [comment] 2020-05-01 16:47
The download Elisha posted 20+ days ago indeed was just disabling things in the INI file. The goal was to determine what parts of the module might be causing the game to not launch for you.

So if you can, try the test build Elisha shared a few posts above. Everything should be enabled again and, more importantly, should work/launch for you now.

**Comment by Voromsira** [comment] 2020-05-01 18:20
> The download Elisha posted 20+ days ago indeed was just disabling things in the INI file. The goal was to determine what parts of the module might be causing the game to not launch for you.
> 
> So if you can, try the test build Elisha shared a few posts above. Everything should be enabled again and, more importantly, should work/launch for you now.

Thanks. I did one attempt yesterday, and again, the game didn't launch. I will make one more test - making sure I'm on a clean install - and gather the logs in the process.

Can you remind me if this is the best way to proceed :

1) Launch vanilla .exe
2) Replace with Enhanced exe NA 1.0 and launch
3) Put in the newest d3d8.dll, .ini and .dat and attempt ?

**Comment by Polymega** [comment] 2020-05-01 18:34
> Can you remind me if this is the best way to proceed :

That's a good/safe way to do it. You can launch the vanilla .exe just to make sure the game launches. If it does, then replace it with the .exe provided on our site. If it still launches, then place the SH2 Enhancement module files in and see if it still launches.

Here is the test build that Elisha made that does a lot of extra logging:
https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4519616/d3d8.zip

If the game doesn't launch after placing those files in the game's directory, please attach the `d3d8.log` file it makes.

If the game does launch for you, you can then use this version of the build. It's the same, except it doesn't do all the ton of extra logging:
https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4520174/d3d8.zip

**Comment by Chalo-Oficial** [comment] 2020-05-16 06:33
Hello Everyone,

I am having the same issue as Voromsira and using the files sent by Elisha 23 days ago, the same issue occured as soon as the game starts it just stops responding. I was able to play the previous update without any issue (the one showcased in the youtube video from 02/13/2020) and today I updated to the files in the last version and the game no longer works, I tried uninstalling and reinstalling and similarly to Voromsira the vanilla version works, even using the mod exe but when I copy the whole thing it does not work.

Attached you can find my [d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4637932/d3d8.log)

I tried installing a previous version again but at this point I have a total mess in my files so sadly I was not able to get it to work even when placing previous files on the games folder.

If you could give my case a look I would really appreciate it, I will try to follow up on any further instructions from your end as soon as possible (I have this tab pinned).

Thank you very much for all the effort you guys put into this project.

Best regards,
Chalo

**Comment by Polymega** [comment] 2020-05-16 06:40
Hi Chalo,

Quick response as I think I see what the issue is. Thanks for the detailed post and your attached log file. Looking at the log file, you're using an older version of the SH2 Enhancements module; most likely an old version that had the launching issue.

Try manually downloading and replacing the module files by going here: 
https://github.com/elishacloud/Silent-Hill-2-Enhancements/releases/latest

Replace the files in the game's directory with these new ones. That should hopefully fix the launch issues for you.

**Comment by Chalo-Oficial** [comment] 2020-05-16 08:39
Hello Polymega,

Thank you so much for the quick follow up.

I tried using the files that you sent in the above correspondence and it worked, I have not tried all the features but so far everything looks fine.

Thank you very much for the assistance, have a great weekend.

Regards,
Daniel A.

**Comment by orangeringo** [comment] 2020-05-19 00:40
Hi All. 

I recently updated my version to the newest files posted on the Enhanced Edition homepage. I now am unable to start the game, though my error seems to be related to the reshader pack. It prompts me, saying a new version is available, but the version I downloaded from the Enhanced Edition hompeage still doesn't let me open the game. 

Here's my error code:

"Loading...4 Effects remaining...this may take a while and the game may stop responding"

It never starts responding. Hangs immediately. I tried setting EnableWndMode = 0) but that didn't help me either. 

Anyone have any ideas? I'm hardly a computer savant and trying to fully re-install this entire thing would be...unfortunate to say the least.

**Comment by Polymega** [comment] 2020-05-19 02:30
Hi orangeringo, 

Could you please attach your `d3d8.log` file after trying to launch the game then force closing it down?

**Comment by Voromsira** [comment] 2020-05-20 14:16
Even with a completely clean install (as with each and every attempt I've made), still no luck. The game doesn't react at all.
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4657386/d3d8.log)

(I'm just missing the latest Enhanced FMV Pack because I'm currently redownloading it, as I've decided to go clean slate on all the downloads, just in case)

**Comment by orangeringo** [comment] 2020-05-20 16:45
So, this is highly bizarre- but when I opened the game yesterday to get you the log, it opened with no problems whatsoever. 

Today I tried to play, and it once again would not run. SO I opened the d3d8 log to send to you, and once again, that made the game work? I have no idea how the two could be correlated, but my game only seems to run while the d3d8 log is physically open on my computer, otherwise it just hangs and crashes..

This is a fine workaround for now...but any idea why this is happening? Here is my log for reference. 
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4658196/d3d8.log)

**Comment by Polymega** [comment] 2020-05-20 20:13
Hmm... it's hard to say. It sounds like it might have been a read/write permissions thing going on with your directory, but looking at you log file, you're running the game through your `.\Documents\My Games\` folder so that shouldn't be the issue. 

Also, looking at the log, your directory for the game is perfect--you don't have any foreign/odd files in there.

I'm wondering if there's something running in the background that might be preventing the game from launching? Does it normally run after a fresh restart of your PC? If you set `AutoUpdateModule = 0` in the `d3d8.ini` file does that alleviate the issue?

**Comment by Polymega** [comment] 2020-05-20 20:15
@Voromsira 
You'll want to use the latest build of the SH2 Enhancement module (v1.5.1750.0), which should fix the launch issues: https://github.com/elishacloud/Silent-Hill-2-Enhancements/releases/latest

@orangeringo
Hmm... it's hard to say. It sounds like it might have been a read/write permissions thing going on with your directory, but looking at you log file, you're running the game through your `.\Documents\My Games\` folder so that shouldn't be the issue. 

Also, looking at the log, your directory for the game is perfect--you don't have any foreign/odd files in there.

I'm wondering if there's something running in the background that might be preventing the game from launching? Does it normally run after a fresh restart of your PC? If you set `AutoUpdateModule = 0` in the `d3d8.ini` file does that alleviate the issue?

**Comment by Voromsira** [comment] 2020-05-20 21:28
> @Voromsira
> You'll want to use the latest build of the SH2 Enhancement module (v1.5.1750.0), which should fix the launch issues: https://github.com/elishacloud/Silent-Hill-2-Enhancements/releases/latest

I've tried it. In my previous message, the first log is output by the latest Enhancement module.

The second log is made by the "extra logging" version.

Here's a third attempt (with version 1.5.1750.0) : [d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4659370/d3d8.log)

> If that doesn't work, can you try moving the entire `SILENT HILL 2` folder to a different drive (such as `C:\`) just to see if it'll launch on that drive? You shouldn't have to uninstall/reinstall to do this; just relocate the files.

I already tried this as well since until now SH2 was installed on D:\ (my SSD dedicated to games) and my current attempts are made with the game installed on E:\ (a HDD).

**Comment by Polymega** [comment] 2020-05-20 21:43
Thanks for trying those things. 

This is really random, and a _complete_ long-shot, but I noticed you have a `device.7z` file in the directory. I know the game will detect and read the `device.fix` file, but maybe it's conflicting itself when it finds another file type with the same name? Try removing `device.7z` to see if that does anything. (Maybe try removing both `device.fix` and `device.7z`)

@elishacloud, Voromsira attached a log from the build that outputted a bunch of additional information, if it helps: [d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4657450/d3d8.log)

**Comment by Voromsira** [comment] 2020-05-20 22:13
> Thanks for trying those things.

No, thank **you** guys for your patience with me.

> This is really random, and a _complete_ long-shot, but I noticed you have a `device.7z` file in the directory. I know the game will detect and read the `device.fix` file, but maybe it's conflicting itself when it finds another file type with the same name? Try removing `device.7z` to see if that does anything. (Maybe try removing both `device.fix` and `device.7z`)

I removed both device.fix and device.7z. Also, this time, I moved the game folder to the root of C:\. Still nothing...here's the log of this latest attempt : [d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4659535/d3d8.log)

**Comment by elishacloud** [comment] 2020-05-24 21:04
@Voromsira, can you try using the debug build from the [release](https://github.com/elishacloud/Silent-Hill-2-Enhancements/releases/tag/v1.5.1750.0) page and then zip the logs and upload them?

**Comment by Voromsira** [comment] 2020-05-26 13:22
> @Voromsira, can you try using the debug build from the [release](https://github.com/elishacloud/Silent-Hill-2-Enhancements/releases/tag/v1.5.1750.0) page and then zip the logs and upload them?

Sure thing, here they are : 
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4682469/d3d8.log)
[d3d9.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4682470/d3d9.log)

**Comment by Voromsira** [comment] 2020-06-12 11:01
Here is an update. I formatted my PC (for unrelated reasons - I upgraded my GPU and also wanted a fresh start) and now the game launches without issues.

...so it seems something in my previous, bloated system might have prevented the game from launching. But why _only after that recent update_ ?

I consider my issue solved, even if the resolution had to be a format. I'm grateful for the help you guys attempted to provide, and I hope I did not _just_ wasted your time, and that at least some data collected will somehow help you. I apologize for the loss of time if it turns out my system was at fault.

I'm not closing this - so you guys can see this last reply - but feel free to mark it as solved and close the issue. If you're unable to do it, tell me and I'll close it myself.

**Comment by Polymega** [comment] 2020-06-14 02:54
No need to apologize whatsoever, Voromsira. We're happy to help in whatever capacity we're able. Sorry we couldn't pin-point the issue down for you but we're happy you ultimately resolved it (albeit through the nuclear option of reformatting your system!). 

Now, time to enjoy the game without all the headaches! :beers:

**Closed by Polymega** 2020-06-14 02:54 UTC
