### ISSUE TITLE
The game freezes while playing with audio through HDMI

### ISSUE THREAD

**Issue by Hunier16** [elishacloud/Silent-Hill-2-Enhancements#179] opened 2019-10-18 13:10 UTC
![screenshot](https://user-images.githubusercontent.com/56727021/67097000-8985c580-f1b9-11e9-82a2-f664ca340b22.jpg)
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3744013/d3d8.log)

Hi!

My problem is as follows: 

the game freezes when I play it with the digital output (HDMI > TV) being the only available audio output. If any other output is available (e.g. my USB Focusrite interface), the sound plays there (even if HDMI is selected as the primary output in the system settings) and the game does not crash. 

The freeze occurs when booting the game, and the ReShade popup claims 1-3 effects remain to be loaded in. I tried setting d3d8to9 = 0, SingleCoreAffinity = 0, deleting dsound, reinstalling everything (I have everything mentioned [here](http://enhanced.townofsilenthill.com/SH2/index.htm) installed as described). 

Is there any way to make the game output audio to HDMI? I tried turning all other outputs DURING gameplay and it just freezes the game right then and there.

Thanks in advance for any advice,

Piotr

**Comment by Polymega** [comment] 2019-10-18 20:05
Hi @Hunier16, 

Sorry you're running into some issues. 

> Is there any way to make the game output audio to HDMI? I tried turning all other outputs DURING gameplay and it just freezes the game right then and there.

This will be hard for me to troubleshoot as I don't have an HDMI **Out** on my PC. 

I know that El Gato PCI capture cards have both input and output (pass-through) connections. And these capture cards also come with their own software called "El Gato Sound Capture." This software, if you allow it, can override your Windows settings for which devices output sound. 

This is a long way of asking if the Focusrite Scarlett might have a similar piece of software that is overriding your sound output settings? You might want to double-check there to see if it's creating conflict with trying to output sound via HDMI. 

Also, if using audio output from your GPU (such as Nvidia's "HD Audio" component), disable it and use your motherboard's onboard audio output instead.

-------------------------

> I tried setting d3d8to9 = 0, SingleCoreAffinity = 0, deleting dsound, reinstalling everything (I have everything mentioned here installed as described).

I had the following typed up and ready to post before I noticed you updated your post! You can **ignore** the following below, since it seems you've already tried these things, but I'll keep them in my post in case they might help anyone else in the future. You might want to read them over anyways, just in case.

Based on your description of the problem I can think of three things to try: 

> the game freezes when I play it with the digital output (HDMI > TV)

Are you playing in fullscreen mode (`EnableWndMode = 0`)? If so, perhaps your TV is a different resolution than your PC's screen resolution, and the game is launching using the PC's resolution which is creating conflicts with your TV's resolution. 

If you were playing in fullscreen mode, try setting `EnableWndMode = 1` and set `ResX =` and `ResY =` to your desired resolution (leave both at `0` to inherently size to your display's resolution). 

> being the only available audio output.

I'm not sure why this would be an issue, but perhaps IndirectSound is creating conflicts when trying to hook to output sound to your TV. If the above suggestion doesn't work, trying temporarily removing `dsound.dll` from the game's directory and see if it launches then. 

If it still doesn't launch, you can place `dsound.dll` back in the game's directory. 

> The freeze occurs when booting the game, and the ReShade popup claims 1-3 effects remain to be loaded in.

It might have to do with ReShade, then. Try setting `d3d8to9 = 0` and see if the game launches then. This will disable ReShade entirely.

**Comment by elishacloud** [comment] 2019-10-18 21:07
I believe the issue may be related to these lines in the log file:

```txt
10024 15:07:55.888 InstallFileSystemHooks Error: 'ConfigPath' incorrect! C:\Pobrane\Silent.Hill.2.Directors.Cut.PC.Game(djDEVASTATE")\Silent.Hill.2.Directors.Cut.PC.Game(djDEVASTATE")\d3d8.ini
10024 15:07:55.888 InstallFileSystemHooks Error: 'strModulePath' incorrect! C:\Pobrane\Silent.Hill.2.Directors.Cut.PC.Game(djDEVASTATE")\Silent.Hill.2.Directors.Cut.PC.Game(djDEVASTATE")\d3d8.dll
```

What path do you have Silent Hill 2 installed to?

**Comment by Polymega** [comment] 2019-10-18 21:19
Oh! Didn't see he edited a log file there, too. Nice catch, Elisha. :)

**Comment by elishacloud** [comment] 2019-10-18 23:19
If I had to guess, I blieve the problem is with the path he has the game installed to:

```txt
C:\Pobrane\Silent.Hill.2.Directors.Cut.PC.Game(djDEVASTATE™)\Silent.Hill.2.Directors.Cut.PC.Game(djDEVASTATE™)
```

More specifically he is using a double-byte character in the path, namely this:  ™ 

I believe when `UseCustomModFolder` converts the path to ASCII it breaks the path.  Until I can get this fixed, he will either need to remove the double-byte characters (there are two in his path) or disable the `UseCustomModFolder`.  The former is recommended.

_Note: I need to convert the path to ASCII because that is the format the game uses.  But I never tested double-byte characters before._

**Comment by Hunier16** [comment] 2019-10-19 06:07
Thank you for your quick and thoughtful replies!

> This is a long way of asking if the Focusrite Scarlett might have a similar piece of software that is overriding your sound output settings? You might want to double-check there to see if it's creating conflict with trying to output sound via HDMI.

Focusrite is disconnected when I'm playing through HDMI, so there should be no conflict.

> Also, if using audio output from your GPU (such as Nvidia's "HD Audio" component), disable it and use your motherboard's onboard audio output instead.

I had already searched for it, and found nothing like that on my PC.

> Are you playing in fullscreen mode (EnableWndMode = 0)? If so, perhaps your TV is a different resolution than your PC's screen resolution, and the game is launching using the PC's resolution which is creating conflicts with your TV's resolution.

Yeah, the thing is the game plays without any problems on my TV when any other audio output is enabled in the system audio settings. It just does not want to send audio to the TV, even when it is selected ans the primary output, and when I disable all other outputs while playing, I can hear the audio for a second, after which the game freezes. The PC is a laptop, and I have no outside speakers near the TV, so the audio just flows from the laptop speakers which is not ideal. I can live with it, but this just keeps bugging me, you know the feeling :)

> I believe when UseCustomModFolder converts the path to ASCII it breaks the path. Until I can get this fixed, he will either need to remove the double-byte characters (there are two in his path) or disable the UseCustomModFolder. The former is recommended.

I have deleted both characters, it did not help.

**Comment by elishacloud** [comment] 2019-10-19 17:49
Interesting.  Most things appear to work correctly with double-byte characters in the path on Windows 10.  However, `Nemesis2000FogFix` will be broken.  On Windows 7 or Linux there may be other things that are broken.

I am using both HDMI and DVI ports and both ports work fine for me.

First of all, try this updated build:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3747005/d3d8.zip)

Secondly, try updating the driver of the card that you are using for HDMI.  This is probably your video card.  Some machines have a secondary video card used only for HDMI.  Make sure this driver is updated to the latest.

Third, if those two don't work try playing the game using HDMI without any of the Silent Hill 2 Enhancements.  Make sure HDMI is running well natively with the game before installing any of the Silent Hill 2 Enhancements.

**Comment by Hunier16** [comment] 2019-10-20 17:09
So... I guess I KINDA fixed it?

As I've said, the game would crash if I tried to "cheat" it and disable the main audio output while playing. Well, now, I guess after updating both video cards' drivers (Intel and Radeon, but it seems HDMI is going out of Intel), it does not. I just have to boot the game with sound through the laptop speakers, and then disable them in the settings, and voila, I have working audio from my TV and the game does not crash. What do you know :) It still freezes if I try to start it with the output disabled, but I can live with this workaround for this playthrough.

Oh, and I did check it all with a fresh game with no Enhancements, and... yup, it seems to be the game's fault. It would crash the same way. So I probable started a ticket at the wrong forum, but nevertheless: thanks for all your responses, they eventually led me to the fix (well, I think?). 

Cheers!

**Comment by Polymega** [comment] 2019-10-20 21:38
I'm happy to hear you've found a work-around! Sometimes a driver update can be what the doctor ordered. :) Thanks for helping with this, Elisha!

**Comment by Polymega** [comment] 2019-10-21 22:52
Hi Elisha, 

From build 1.3.1418 and up my game crashes upon exit if d3d8to9 is enabled. It launches and plays fine; it only crashes as the game is closing (when I choose EXIT on the main menu).

**Comment by elishacloud** [comment] 2019-10-22 02:03
Try this one.  I was a bit too aggressive on the cleanup (which is probably not needed anyways): [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3753562/d3d8.zip)

**Comment by Polymega** [comment] 2019-10-22 07:21
Thanks, Elisha! I did a quick test and no crashes to report.

**Closed** 2019-12-18 02:57 UTC
