### ISSUE TITLE
The game freezes randomly [SH2]

### ISSUE THREAD

**Issue by Storm3000** [elishacloud/Silent-Hill-2-Enhancements#44] opened 2018-09-11 16:06 UTC
I have a problem with the new Enhanced Edition of Silent Hill 2. The game freezes randomly when a new audio it's loading. For example, if I open a door that triggers a cutscene, when the audio must begin, the game freezes and it won't work again until I close it with Task Manager. This happened to me two times after updating the game.

This never happened to me before the new update.

I have another question, which update should I use? The Aero's SH2 Widescreen Fix or the Elisha's Enhancements?

**Comment by Polymega** [comment] 2018-09-11 16:32
[This may be the same issue that BinariGuy is facing.](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/39#issuecomment-420163043) We'll need to get @elishacloud 's input on this one. 

Elisha won't be able to help with troubleshooting very much this week so please allow some time for us to look into this.

**Comment by Polymega** [comment] 2018-09-11 16:39
@Storm3000 the next time it crashes would you want to try and figure out what caused it to crash through the [Windows Event Viewer](https://www.howtogeek.com/123646/htg-explains-what-the-windows-event-viewer-is-and-how-you-can-use-it/)? This may help to determine what's causing the issue.

**Comment by AeroWidescreen** [comment] 2018-09-11 18:54
@Polymega  If it's freezing and not crashing, then I don't know if Event Viewer will have anything to show.

@Storm3000 
This sounds like a problem with the audio enhancement, so I would start by disabling `UseCustomModFolder` and see if the random crashes stop.

> I have another question, which update should I use? The Aero's SH2 Widescreen Fix or the Elisha's Enhancements?

If you're asking if you should use SH2E or the widescreen fix, then the answer is SH2E. The enhancement project contains the widescreen fix, along with the fog fix. There's no reason to use one over the other unless you're troubleshooting.

**Comment by Polymega** [comment] 2018-09-11 19:06
> If it's freezing and not crashing, then I don't know if Event Viewer will have anything to show.

This is why you and Elisha are the brains of this operation. :) 

@Storm3000 when it froze both times did it happen at the beginning of the _same_ cutscene? As in, can you immediately replicate it each time? 

And as Aero_ mentioned: Try temporarily setting `UseCustomModFolder = 0` and see if that alleviates the issue, especially if you can easily replicate the freezing each time.

**Comment by BinariGuy** [comment] 2018-09-12 00:04
@Polymega You right man my game freezes anytime not crash my bad sorry :(

**Comment by Polymega** [comment] 2018-09-12 00:09
Does it happen immediately upon entering a new room/area? Can you try what we suggested above and see if that fixes it? 

Try temporarily setting `UseCustomModFolder = 0` and see if that alleviates the issue, especially if you can easily replicate the freezing each time.

**Comment by Storm3000** [comment] 2018-09-12 17:20
The game freezes, not crash. Both times happened at the beginning of some cutscene. It happens randomly. For example, everytime you trigger any cutscene, there's a little moment (let's call it stuttering) when the audio will load. I noticed this because always the game freezes 1 milisecond and then I can hear the audio of the sequence. For example, you can notice this when James sees the dead body on the couch in front of the TV. You'll notice a very little stuttering or freezing inmediately before the audio of the sequence begins or loads.

In my case, the game freezed when James opens the emergency door at the Woodside Apartments that connects with the Blue Creek Apartments. And freezed again when James meets Laura in the hospital.

I'm not sure if the problem has something to do with the audio, but it's a possibility. I'll install the game again, because I didn't make a fresh install to use the new Elisha's enhancements. Instead, I erased everything I was using before (scripts folder, Aero Widescreen fix, etc.) and I added all the new files found on the Silent Hill 2: Enhanced Edition web site. I made sure to check that everything was fine, but maybe the game really needs a fresh installation.

**Comment by Storm3000** [comment] 2018-09-14 20:02
I installed the game again. I followed every steps on the installation of the enhanced edition. The game still freezes randomly, but this time it wasn't during a cutscene. It happened when I came out of the elevator in the hospital. Maybe it's not the audio, after all. I'll try erasing the reshade files and see what happens. I think it's the only new file, the others it seems to be updates of previous files.

**Comment by Polymega** [comment] 2018-09-14 20:39
> I'll try erasing the reshade files and see what happen. 

Thanks for reminding me. Someone else opened a ticket here mentioning that updating ReShade to a newer version than what's provided in the package downloads messed up their game. 

I haven't had a chance to look into this yet myself, with other going-ons, but definitely try removing ReShade and see what that does then.

**Comment by Storm3000** [comment] 2018-12-08 00:43
I'm amazed what you, guys, have done with this game. The game works really fantastic now.

Sadly, I still has the freezing problem. That's my only issue. The game freezes randomly, so I cannot detect where's the problem come from. I know it has nothing to do with ReShade. I think the problem is related to d3d8.dll or maybe the "sh2e" folder.

**Comment by Polymega** [comment] 2018-12-08 02:40
Unfortunately without a crash report we can't pin-point what the issue may be. The only thing I can suggest right now is disable features, using a process-of-elimination, until you can determine what, if any, fixes are causing the issues. I'm sorry I can't give a more direct solution to your problem. :-/

**Comment by elishacloud** [comment] 2018-12-09 22:53
I am about 90% sure this is a deadlock between two threads.  There are a number of known thread issues with this game.  As I understand it, they were supposed to be fixed in [patch v1.1](https://www.fileplanet.com/archive/p-31498/Silent-Hill-2-Patch) but even with v1.1 I can see some issues.  This is why we added the `SingleCoreAffinity` feature.

I very much doubt this is caused by the Silent Hill 2 Enhancements module, however it may exacerbate the problem.  Specifically the enhanced audio files, since they change the thread timing because it takes the thread longer to load a large audio file vs a small audio file.  The game does not do proper thread synchronization, so subtle timing changes like that can lead to this type of problem.

Note: these thread issues can be seen either by audio glitches (like looping the same sound over and over) or by the game totally freezing.  Both are symptoms of the same thread deadlock.

Try deleting the enhanced audio files from the `sh2e` folder and see if it still happens.

**Comment by Storm3000** [comment] 2018-12-10 16:39
I moved yesterday all the files stored on the sh2e folder back to the original folders. I played almost all the game and it worked fine. I'll continue checking if the issue appears again, but it's working fine for now. Besides, I disabled the UseCustomModFolder option in d3d8.ini.

**Comment by TomasVIA** [comment] 2020-02-13 20:43
Hi. I have a similar problem. Game freezes during audio or video cutscenes turning into a loop. Also crashes sometimes when I want to exit.  Next time I start the app, it changes all my graphic options and resolution to the lowest.

**Comment by Polymega** [comment] 2020-02-13 20:45
> Next time I start the app, it changes all my graphic options and resolution to the lowest.

This means the project files weren't installed/placed directly in the game's directory. Can you please send a screenshot of the game's installation directory on your computer?

**Comment by TomasVIA** [comment] 2020-02-13 21:08
https://ibb.co/qC0xyhF

**Comment by Polymega** [comment] 2020-02-13 21:17
Thank you. You are missing the [SH2 Enhancements Module package](http://enhanced.townofsilenthill.com/SH2/#installSH2Enhancements), which is the "brains" of our entire project to make everything run and work. 

Download the latest release of this package from the link below, and place the files from the ZIP package into the game's main directory:
https://github.com/elishacloud/Silent-Hill-2-Enhancements/releases/download/v1.3.1365.0/d3d8.zip

**Do note:** In under six hours we will be releasing the next major update to our project, which will require you to download updated packages for the:

- SH2 Enhancements Module
- Enhanced Edition Essential Files
- FMV Enhancement Pack

Keep an eye on our [YouTube](https://www.youtube.com/user/WhereAllBegins) and/or [Twitter](https://twitter.com/WhereAllBegins) page to know when this release goes live. Once it goes live, you will only need to download the updated packages listed above, and replace files/folders from these downloads in the game's directory, if prompted. 

Stay tuned.

**Comment by TomasVIA** [comment] 2020-02-14 01:56
Wow!

Thanks a lot. Yeah, you were right. I forgot to download that package from github. That's amazing! I am just going to play the game after several years. Wish you all the best with your project and all your hard work!

**Comment by Polymega** [comment] 2020-02-14 02:03
Great! We should be releasing the next update within the hour. It might be worth waiting to update these packages before playing, as this upcoming update will include restored soft shadows, special effects, and much more!

If you want to, periodically check our Twitter/YouTube page throughout the hour.

**Comment by elishacloud** [comment] 2020-04-29 04:02
Closing this out.

**Closed by elishacloud** 2020-04-29 04:02 UTC
