### ISSUE TITLE
Cutscene borders, "Black Bars", don't completely cover the vertical portions of the screen when re-enabled. 

### ISSUE THREAD

**Issue by UwUapple1** [elishacloud/Silent-Hill-2-Enhancements#495] opened 2022-03-06 16:53 UTC
Hello and good day.

I was wondering if anyone could assist me in rectifying a problem with how the cutscene borders or "black bars" are displayed when setting _"DisableCutsceneBorders"_ to "0". When re-enabled, the borders don't quite reach the very top (sometimes bottom) of the screen, resulting in a tiny portion of the full image bleeding through; becoming extremely noticeable when in Fullscreen. 

![sh2pc exe Screenshot 2022 03 06 - 08 46 32 15](https://user-images.githubusercontent.com/101050238/156927152-8f5cafc1-79e0-49a1-ad78-a086a2e66dd5.png)

I've tried finicking around with _"FMVWidescreenMode"_ and _"ReduceCutsceneFOV"_ to try fixing it and even playing in 4:3 (1280x960), but the problem seems to persist. Any help would be greatly appreciated, and my apologies if this issue has already been addressed.

![sh2pc exe Screenshot 2022 03 06 - 08 50 28 66](https://user-images.githubusercontent.com/101050238/156933035-66faf97f-0eba-4088-b877-2e950744df9a.png)

Thank you for your time.

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8193056/d3d8.log)

**Comment by Polymega** [comment] 2022-03-06 17:59
It's been so long since I've used the cutscene borders I hadn't noticed this. 

This seems like a similar situation Eilsha fixed a few years back where he shifted the vertex position of the post-processing bloom layer (among other things) by something small like `0.5f` and it fixed the issue of the bloom leaving a 1 pixel artifact along the left and top edges: https://github.com/elishacloud/Silent-Hill-2-Enhancements/commit/0f320a15de5c43cba979229ca9112c3f5599dfed

We can ask him if he thinks this is the same situation going on. I'd be willing to bet it is. Here's what he said about the "bloom bleed" issue a while back:

> Elisha wrote: Yes, I believe this is because the vertexes used for some locations are not very precise.  This may also be a similar issue to the geometry line issues we have.  The original authors were not very precise in their vertexes and this causes bleeding all over the place, though maybe bleeding in a horror game is ok...LOL. 

`009423BC byte` - Cutscene letter trigger

**Comment by Polymega** [comment] 2022-03-06 18:36
For testing purposes, nop'ing sh2pc.exe+76A5D will display the letterboxes at all times in the game.

I found some relevant addresses to move letterbox positions (below), but it doesn't help to remove the 1 pixel line on the left and top edges. This is likely due to the overall vertex **container** for the letterboxes being off and would require Elisha to address this as he's done for other/similar issues.

**Note:** These addresses/values might be used elsewhere throughout the game!
- 006A1484 float - Vertical position of top letterbox bar
- 0069DB64 float - Vertical position of bottom letterbox bar
- 00A33484 4 byte - Overall game height for letterboxing position

**Comment by UwUapple1** [comment] 2022-03-06 18:53
After further messing about with the _"d3d8.ini"_ file, I finally managed to have the Borders be placed properly. All I did was change _"ScreenMode"_ to 3 (Fullscreen mode) from 2 (Windowed fullscreen mode) and after that, the Black bars display correctly: the issue is possibly a side effect with "2" and I'm not sure if this can be considered a fix or workaround.

Nonetheless, thank you very much for responding promptly and providing your insight. You have my gratitude and praise for all the work put into maintaining the **_"Enhanced Edition"._** Cheers!

**Comment by Polymega** [comment] 2022-03-06 19:01
Thanks for the kind words. It only being fixed in fullscreen mode would be a workaround and not a fix, so hopefully we can fix it up regardless of the display mode. Interestingly, those lines are still present in fullscreen mode when playing the vanilla version of the game.

**Comment by UwUapple1** [comment] 2022-03-10 18:43
Upon further testing, this issue seems only present when Nvidia anti-aliasing is enabled. 

Disabling this in **_"NVIDIA Control Panel"_**, will correct the cutscene borders when using _"Windowed fullscreen"._

**Comment by elishacloud** [comment] 2022-04-02 00:53
I am not able to reproduce this on the latest build: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8401453/d3d8.zip).  I am not sure if I am doing something wrong.

I have tried the following and different combinations of each:
* nop'ing sh2pc.exe+76A5D
* Setting DisableCutsceneBorders = 0 in the INI
* Enabling Nvidia anti-aliasing
* Setting ScreenMode = 2 in the INI

Is there some deterministic way to see this issue?

I was also, at the same time, going to look into the issue where the noise filter is displayed on the pillar boxes, but I was unable to reproduce this also.

**Comment by Polymega** [comment] 2022-04-02 01:22
I still see the pixel line artifact. In this image, I placed the game image behind a bigger black area to better show it:

![image](https://user-images.githubusercontent.com/27395260/161358156-409a771f-d82d-49c4-8bc6-9c6e7463ddf6.png)

@UwUapple1 looks to be correct in that Nvidia antialiasing is the cause (this may also happen with an enabled setting through AMD, as well). These settings are what's causing it: 

**Antialiasing - Mode**: Override any application setting 
**Antialiasing - Setting**: Any value other than Use global setting (Application-controlled)

**Comment by elishacloud** [comment] 2022-04-02 01:27
Just for testing, can you try setting the following:

* EnableSoftShadows = 0
* FixGPUAntiAliasing = 0

**Comment by Polymega** [comment] 2022-04-02 01:32
With those Nvidia settings I mentioned enabled, toggling any combination of `EnableSoftShadows` and `FixGPUAntiAliasing` does **not** fix this issue.

> I was also, at the same time, going to look into the issue where the noise filter is displayed on the pillar boxes, but I was unable to reproduce this also.

Happily, I believe you already addressed this. You fixed this so that noise grain wouldn't appear beyond the boundaries of the FMVs when they're playing. [I remember making a tweet about this a long time ago.](https://twitter.com/WhereAllBegins/status/1400223264350347265) I don't believe noise appears for pillarboxes anywhere else as the use of pillarboxes anywhere else is for maps/full screen images, which disable the noise altogether when they appear.

**Comment by elishacloud** [comment] 2022-04-02 02:06
Ok, I still cannot see this on my computer.  But it appears that the vertex for the pillar box is not quite right.  I updated them, which might solve the issue here.

Here is a testing build: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8401591/d3d8.zip)

**Comment by Polymega** [comment] 2022-04-02 02:14
This looks to be the right track. It fixes the exposed 1 pixel line at the top and left, but places a 1 pixel black line on the right now (zoom in on image to see):

![image](https://user-images.githubusercontent.com/27395260/161361750-8159da7c-31a5-49f1-944b-887a4517091c.png)

Can this be tweaked any more to really dial in the position?

**Comment by elishacloud** [comment] 2022-04-02 02:19
That black bar is not related to the pillar boxes.  That is a completely different vertex and the issue should have been there before the pillar box vertex fix I just did.  In fact if you look at the pictures at the top of this thread you can see the black line in those pictures.

**Comment by Polymega** [comment] 2022-04-02 02:30
Ah, you're right, that's always been there when the game creates its own letterboxes for in-game cutscenes. This was a case where I only now noticed it upon this discussion, so I made a wrong assumption. My apologies. In any case, that 1 pixel black line is no where near as noticeable as the exposed lines you just fixed, so if you're happy, then I'm happy.

**Comment by elishacloud** [comment] 2022-04-02 02:56
No problem.  I think fixing that 1 pixel black line would be a lot harder as it seems to effect all indexed vertexes.  It might be easier to figure out the flow in the games code and fix it there.  I recommend just leaving it unless it is really a big issue.

For the letterbox issue, I have finished the code.  Can you check this one more time before I submit it?  I added this to the `FixGPUAntiAliasing` option.

[d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8401662/d3d8.zip)

**Comment by Polymega** [comment] 2022-04-02 05:01
Yup, everything still seems fine. 

> I recommend just leaving it unless it is really a big issue.

Nah, it's not a big issue at all. No one has ever mentioned this quirk before in the project, and I'd be willing to bet it's never been mentioned in the history of SH2 PC's existence. Hell, I never knew of it until tonight and you know I've been picking this game with a fine-tooth comb over the past years.

Thanks for fixing this, Elisha!

**Comment by Polymega** [comment] 2022-04-02 05:05
PS - Out of genuine curiosity I booted the PS2 version and, check out the right edge. 😎 

![gsdx_20220402010359](https://user-images.githubusercontent.com/27395260/161367252-94912339-7e73-4376-829e-706a2c6deb61.png)

**Closed** 2022-04-02 05:09 UTC
