### ISSUE TITLE
Another unable to launch scenario 

### ISSUE THREAD

**Issue by ResilentSlasher** [elishacloud/Silent-Hill-2-Enhancements#303] opened 2020-07-26 19:16 UTC
![Load Screen](https://user-images.githubusercontent.com/68823013/88487246-f5ffd300-cf48-11ea-9673-38cc02cbecfe.PNG)
This is the main issue I am having, but I tried what some of the others have tried in other tickets, such as temporary removing temporary removing dsound.dll (Closed Issue #92) and changing the autoupdater from 1 to 0. I also tried the installation process from scratch to no avail since I got someone's files from reddit, and then decided to do it myself thought myabandonware.  

Could it be my SingleCoreAffinity? It's currently set to 2. 

Tried multiple things, but first here is my d3d8.log: 
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4978212/d3d8.log)

Firs things first, here are my specs:
16gb ram
i7 intel processor
gtx 1650

Here is the game's main directory, which is in my D drive (HDD):
![Directory](https://user-images.githubusercontent.com/68823013/88487145-3579ef80-cf48-11ea-82d5-9ae6a1e9391e.PNG)
By the way, I also followed the directory on the website by taking out the "Silent Hill 2 ISO" and the "_MACOSX" folders. 

I already checked for the Microsoft Visual C++ 2010, and it's there! However, I tried to get the DirectX, only to get the bottom photo stating that the installation is unnecessary. 
![DirectX Dilemma](https://user-images.githubusercontent.com/68823013/88487146-3579ef80-cf48-11ea-8922-1d45eb8febb0.PNG)

Please send help! I just beat Silent Hill 1 and was looking forward to playing this. If any further information is needed, please tell me, so we can try to resolve this issue together with ease!

P.S. This is my first time officially using GitHub :)

**Comment by Polymega** [comment] 2020-07-26 19:30
Hi there, 

Looking at your log file, this is likely the problem: 

`22736 13:55:12.514 "Intel(R) UHD Graphics 630"`

The game is using your integrated graphics card (IGP) to run the game, as opposed to your GTX 1650. IGPs will usually hang on launch when trying to use ReShade, as ReShade is too demanding for IGPs.

This is a typical issue with laptops in that you need to instruct your computer to use your Nvidia GPU for an application (`sh2pc.exe`, in this case) instead of your IGP.

[Following these instructions](https://www.techadvisor.co.uk/how-to/pc-components/how-set-default-graphics-card-3612668/), you can tell your PC to use your GTX 1650 for SH2 PC instead.

**Comment by ResilentSlasher** [comment] 2020-07-26 20:19
I feel dumb now that I didn't notice that lol! This is most likely the issue, and I tried what you said. Unfortunately, it didn't work. 
![High-Performance](https://user-images.githubusercontent.com/68823013/88488368-80990000-cf52-11ea-9c6d-b3df23fd5a97.png) 

I checked the log again. It still showed my integrated card, which is weird since I ran it with the GTX 1650, and I already had it activated in the PhysX Configuration section within the NVIDA Control Panel. 

I am try to rewrite the line from "Intel(R) UHD Graphics 630" to my other graphics card. 

If this fails, then I guess I can also try to take out the "ReShade" and "Shaders" folder to see if it executes properly. I'll let you know what happens!

**Comment by ResilentSlasher** [comment] 2020-07-26 20:30
Alright, altering the text within the log caused nothing to happen. The reason for this is that it just reverts back to my integrated card instead. Then, I decided to play with the shader just out of curiosity, but it just still had the same black screen.

**Comment by Polymega** [comment] 2020-07-26 20:44
Instead of telling telling your PC to run with the Nvidia processor by right-clicking the shortcut, what if you permanently set it to run with the Nvidia process[ through the instructions on this page](https://www.techadvisor.co.uk/how-to/pc-components/how-set-default-graphics-card-3612668/)? Would that make the game correctly run with your GTX card?

**Comment by Polymega** [comment] 2020-07-26 20:45
> Alright, altering the text within the log caused nothing to happen. 

PS - The log file doesn't affect settings in anyway; it's a passive file generated each time you launch the game for use with troubleshooting. Only the `d3d8.ini` file can adjust settings.

**Comment by ResilentSlasher** [comment] 2020-07-26 20:45
Yes, I tried it that way, but no luck. I'm try to redo the installation process again. I probably overlooked something.

**Comment by Polymega** [comment] 2020-07-26 20:51
Perhaps the first thing to try is to remove the ReShade files just to see if the game will launch/run with your IGP. That will at least tell you that the installation of the game and our project files was successful. Remove these files/folders from the game's directory:

```
\reshade-shaders\
d3d9.dll
d3d9.log
ReShade.ini
ReShade_sh2pc.ini
```

(Note that IGPs will typically lag/stutter during outdoor areas when using the Fog Fix.)

If the game launches after removing the ReShade files, that's a good indicator that your installation of the game is fine.

**Comment by elishacloud** [comment] 2020-07-26 21:11
> Looking at your log file, this is likely the problem: `22736 13:55:12.514 "Intel(R) UHD Graphics 630"`

Unfortunately, that line may not show the correct value.  That just shows the default graphics card on the system.  It does not show which card is being used.  In this case it will likely always show "Intel" even if the game is using the Nvidia GPU.

Below is an update that will show which video card the game is using.  The entry is now toward the end of log file, but it should accurately show what video card is being used.

Here is the update:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4978539/d3d8.zip)

**Comment by ResilentSlasher** [comment] 2020-07-26 21:31
I think we are making progress! Now it says that there is only 1 item left to load. Also thank you for providing me with the new d3d8 because it does in fact display the correct video card now.

**Comment by ResilentSlasher** [comment] 2020-07-26 21:36
By the way, I tried taking out the shaders after inserting the new d3d8 file that you guys provided, but it only leads to a pitch black screen. Does this mean I have to reinstall all the files or just the game itself through the myabandonware ISOS?

**Comment by Polymega** [comment] 2020-07-26 21:44
Sorry for the misinformation on which graphics processor it was using. Elisha to the rescue as always!

> Does this mean I have to reinstall all the files or just the game itself through the myabandonware ISOS?

By chance did you also run that "Silent Hill 2 Processor Affinity Fix" file that came with the "MyAbandonWare" copy of the game? If so, that might be the cause. [Someone else ran this and it was causing launch issues for them.](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/301)

**Comment by ResilentSlasher** [comment] 2020-07-26 21:53
No, I did not.

**Comment by Polymega** [comment] 2020-07-29 04:40
If you remove the following files will the game launch for you then?

```
dsound.dll
dsound.ini
dsound.log
```

**Comment by valtielfilms** [comment] 2020-08-02 00:13
I was having the same issue just a few moments ago and by following your last comment to remove the dsound files, I was able to get the game to run finally. I also ran into the issue where I was not able to install Microsoft Visual C++ 2010  due to the error message saying that a more recent version was already installed. Everything runs fine so far, just unable to take advantage of the IndirectSound for now.

**Comment by Polymega** [comment] 2020-08-02 00:36
The easiest solution for now is to play the game without IndirectSound. We use IndirectSound to fix audio "clicking/popping" for SFX audio that ends prematurely (but it doesn't address clicking/popping for BGM or dialogue that ends early). In the next update for our project, we will have an integrated audio click/pop fix that'll fix it for _**all**_ sounds, and will also drop our need to use IndirectSound.

The obvious downside is you won't have a SFX click/pop fix for the time being, but it'll allow you to still play the game in the meantime.

**Comment by Polymega** [comment] 2020-11-12 20:39
Closing issue. We've released the next update which officially drops IndirectSound in favor of DSOAL. You can get the DSOAL files here: http://enhanced.townofsilenthill.com/SH2/install.htm#changelog

**Closed by Polymega** 2020-11-12 20:39 UTC
