### ISSUE TITLE
Game freezes when reading a memo or anything else that causes the screen to go black

### ISSUE THREAD

**Issue by PCF13** [elishacloud/Silent-Hill-2-Enhancements#150] opened 2019-07-11 18:08 UTC
Hello all,
I am playing the game with the latest patch. However, whenever opening a memo or anything else that causes the screen to go black (such as the Trick or Treat Box), the game will freeze, rendering the player unable to escape the screen. The player still has access to the options menu and can load a previous save to escape. This seems to be random, as I could not replicate the glitch more than once with the Trick or Treat Box. I am in the Otherworld section of the Brookhaven hospital. I will include my d3d8 log file.
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3383347/d3d8.log)

**Comment by Polymega** [comment] 2019-07-11 19:22
Hi @PCF13,
Thanks for the log file. Did you game crash/freeze again before sending over this log file? Did also ever experience any sound looping? Like a record player that keeps skipping the same few notes over and over?

**Comment by PCF13** [comment] 2019-07-11 22:56
> Hi @PCF13,
> Thanks for the log file. Did your game crash/freeze again before sending over this log file? Did you also ever experience any sound looping? Like a record player that keeps skipping the same few notes over and over?

I was thinking and I thought that maybe it's because I was running the game at 60 frames per second. I didn't experience sound issues but I thought maybe that could be the issue.

**Comment by Polymega** [comment] 2019-07-11 23:09
Looking at your log file, the module stopped on setting the `SingleCoreAffinity` fix. If you launch and fully exited the game we'd get log notes past that (such as it saying you've successfully closed the game). 

Also, can you tell me what executable you are using? The North American and European one? Here's what they look like: 

### NA:
![main_menu_english_001](https://user-images.githubusercontent.com/27395260/61091256-740d3c80-a40f-11e9-9ab0-1534a697fb99.jpg)

### EU: 
![multilanguage_001](https://user-images.githubusercontent.com/27395260/61091260-77a0c380-a40f-11e9-9cd2-62009fa03c2d.jpg)

**Comment by PCF13** [comment] 2019-07-11 23:29
> Looking at your log file, the module stopped on setting the `SingleCoreAffinity` fix. If you launch and fully exited the game we'd get log notes past that (such as it saying you've successfully closed the game).
> 
> Also, can you tell me what executable you are using? The North American and European one? Here's what they look like:
> 
> ### NA:
> ![main_menu_english_001](https://user-images.githubusercontent.com/27395260/61091256-740d3c80-a40f-11e9-9ab0-1534a697fb99.jpg)
> 
> ### EU:
> ![multilanguage_001](https://user-images.githubusercontent.com/27395260/61091260-77a0c380-a40f-11e9-9cd2-62009fa03c2d.jpg)

I always exited the game using task manager. And EU

**Comment by Polymega** [comment] 2019-07-11 23:41
Please start using the North American executable. There have been noted stability issues with the European EXE, as reported by various people who were using it here on our GitHub project page. Typically, the European executable would simply crash the game at random spots/times with no real rhyme or reason. 

I made an announcement about this on our Twitter account, but the site seems to be down at the moment so I can't link to it. When the site comes back online, I'd suggest following us there for future announcements like this: https://twitter.com/WhereAllBegins

The European executable was hacked to become a "no CD" executable. The issue is, we have no idea who hacked this binary to turn it into a no CD EXE. In addition to removing the DRM from the binary, this person could have very likely tinkered/modified other things within the executable that creates conflicts with our project. 

While the North American 1.0 executable was also turned into a no CD EXE, it's incredibly stable between the two. Additionally, I also have copy of the North American 1.1 EXE that has its DRM **officially** removed through a Konami patch. 

Please use either one of these executables instead. Continue playing the game and see if you have performance improvements: 

**North American 1.0:** http://enhanced.townofsilenthill.com/SH2/files/SH2PC_Enhanced_EXE_NA_v1.0.zip
**North American 1.1:** [sh2pc_1.1.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3384352/sh2pc_1.1.zip)

**Comment by elishacloud** [comment] 2019-12-18 03:09
Closing issue.  It can be reopened if there is still an issue.

**Closed by elishacloud** 2019-12-18 03:09 UTC
