### ISSUE TITLE
Noise Filter overlay appears during FMVs

### ISSUE THREAD

**Issue by tjladuke5** [elishacloud/Silent-Hill-2-Enhancements#327] opened 2020-10-21 14:05 UTC
I had noticed that when playing with the noise filter enabled, the effect still appears over the FMVs both in-game and when played from the Movies menu. Depending on the selected noise filter resolution, the FMV can become more obscured and dark as it becomes more grainy (I selected the default 512 resolution in the demonstration photo). I wasn't sure if this was an intentional setting or a limitation of some kind. I don't remember seeing this in other versions of the game. Either way, I just wanted to point it out because I love playing with the noise filter in this game (albeit I normally use 1024 noise resolution when playing at 1440p) but I also enjoy seeing the FMVs with good detail.

Thank you so much for all the work that you do!

![noisefilterfmv](https://user-images.githubusercontent.com/20493920/96730268-00810b80-1384-11eb-9c74-b996b6fb7a0c.jpg)

**Comment by Polymega** [comment] 2020-10-21 22:21
Hi there,

This is normal/correct behavior for all versions of the game. :)

The noise grain only goes away for 2D, full screen image events such as pulling up your map, inventory, save screen, or inspecting a riddle/memo image.

I'm going to close this ticket since it's an intended behavior, but if you find something else going wrong with the noise grain feel free to open the ticket back up.

**Closed by Polymega** 2020-10-21 22:21 UTC
