### ISSUE TITLE
Mary's moth attack: moths are rendered behind transparency effect of broken glass

### ISSUE THREAD

**Issue by matheusvb3** [elishacloud/Silent-Hill-2-Enhancements#786] opened 2023-05-14 00:05 UTC
Around the stage where you fight Mary there are many windows with broken/damaged panes which use transparent textures. When the moths are in front of these panes, the transparency effect gets rendered on top of them.

<details>
  <summary>Images</summary>
  
![moth1](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/98937378/34f4aaba-b8cb-4286-be74-c972a1a08f6f)
![moth2](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/98937378/133b35f7-731f-4637-9fa1-04b1f09dd595)
![moth3](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/98937378/d6f01098-0226-4ac0-b221-dfbd5b94f8e0)
![moth4](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/98937378/22164fb0-79c9-41e6-a368-042c6e9115bb)
![moth5](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/98937378/5dd4fae5-d82f-41aa-ab8c-5bf9f2b7b497)
![moth6](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/98937378/dbcf7c6c-d0b4-409d-81e5-500529e07fbb)
![moth7](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/98937378/e5e74f1d-9ee4-4831-8148-08b7d1729897)
![moth8](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/98937378/6de74481-011d-47e9-a381-f7fc08b0a8d3)
  
</details>

<details>
  <summary>Random rambling</summary>
  
By the way Polymega, if you are reading this, last time I interacted with the team I was trying to get some issues solved for 60FPS and mouse support. As you know I'm a Linux nerd so I was having some issues that were pretty hard to diagnose, with you, Elishacloud and Mercury trying to figure out what was causing problems. Since you were so attentive I figure I owe to let you know that I was having a streak of bad luck and that was most likely just a random fluke, thankfully. I played SH2 this week with 60FPS and mouse and something must have changed in SH2EE or Wine, because it worked perfectly. My God, it feels like another game entirely!!! If only every masterpiece of a game could have such dedicated fans doing inspiring work to make it better than the developers could have ever conceived. Thank you so much for your hard work!! 
  
</details>

I would also appreciate if someone could verify this: if you get the "Maria" version of the rooftop conversation with Mary and skip the cutscene right at the beginning, there won't be any background music during the boss fight.

**Comment by Polymega** [comment] 2023-05-14 04:59
> Around the stage where you fight Mary there are many windows with broken/damaged panes which use transparent textures. When the moths are in front of these panes, the transparency effect gets rendered on top of them.

Yeah. This is something I noticed a long time ago as well. I first noticed it in this room:

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/f5e4e86b-a5ee-423a-a5d5-19babbd8943f)

This "bug" happened when Team Silent ported the game to Xbox, which then carried over to the PC version.

It has something to do with these mesh objects being classified as "decals" by the game. "Decal" objects don't really have proper depth sorting. @pmttavara and I were recently talking about this and how it appears to be a Z-fighting issue. Perhaps he could better explain this.

> I played SH2 this week with 60FPS and mouse and something must have changed in SH2EE or Wine, because it worked perfectly. My God, it feels like another game entirely!!! If only every masterpiece of a game could have such dedicated fans doing inspiring work to make it better than the developers could have ever conceived. Thank you so much for your hard work!!

Wonderful!! Very glad to hear that! Maybe I'm biased, but our team is the absolute best, and I'm always thankful for what we can accomplish. 😊 

> I would also appreciate if someone could verify this: if you get the "Maria" version of the rooftop conversation with Mary and skip the cutscene right at the beginning, there won't be any background music during the boss fight.

That's correct. I remember stumbling across this last year as well. I then compared it to the PS2 version. On PS2, if you skip this cutscene, there's like a 20-40 second gap of silence before the music starts to slowly start. I think the music starting after this particular cutscene may have been slightly bugged to begin with on PS2 and became fully bugged when ported over to Xbox/PC.

**Comment by elishacloud** [comment] 2023-05-14 21:45
> @pmttavara and I were recently talking about this and how it appears to be a Z-fighting issue. Perhaps he could better explain this.

Changing the zorder of a specific item is pretty easy.  We just need to be able to isolate the Draw function that is called to draw the moths.

**Comment by Polymega** [comment] 2023-05-15 03:51
> We just need to be able to isolate the Draw function that is called to draw the moths.

Is this information I could provide to you through something such as Intel's Frame Analyzer tool?

Image example:

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/b4edb091-a87c-44a0-b515-b3ea58232468)

**Comment by Polymega** [comment] 2023-05-15 19:13
Below are some details about the moths.

![001](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/d0850385-0034-4626-ac1d-2a0b00b2233b)
![002](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/8d612695-8238-4873-8b7e-f84051ab6a53)

They use "DrawPrimitiveUP(Tri List)" with a primitive count of 2. I wouldn't rely on the texture size for this as I increased it from 64x64 (vanilla) to 256x256 (our project).

The API log in the second image is just for a single moth; there are many that are spawned/used.

The moths are used in two rooms throughout the game: Room 0x16 (apartment butterfly room) and 0xBB (final boss room).

**Comment by elishacloud** [comment] 2023-05-15 22:33
> They use "DrawPrimitiveUP(Tri List)" with a primitive count of 2.

Thanks!  However, that is probably not enough information to uniquely identify this Draw function.  I guess there are other things in the room that use DrawPrimitiveUP(Tri List) with a primitive count of 2.

Is it possible for you to use [Microsoft PIX](https://github.com/elishacloud/dxwrapper/issues/184#issuecomment-1536732830) (from [Direct3D9 SDK](https://www.microsoft.com/en-us/download/details.aspx?id=6812)) to take a single-frame capture (F12) of the image when the moths are showing up behind the picture?  Also, if you could do the same for the moths in the stage where you fight Mary.  Then save the PIX data and attach it to this thread so I can evaluate it.

**Comment by Polymega** [comment] 2023-05-15 23:06
> I guess there are other things in the room that use DrawPrimitiveUP(Tri List) with a primitive count of 2.

Believe it or not, I don't think there is. Only the moths are identified as **DrawPrimitiveUP(Tri List)** in the captures I took.

Here are all the types in my capture list:

- Clear(Color)
- Cler(ColorZbuffStci)
- Clear(Stci)
- DrawIndexedPrimitive(Tri Strip)
- DrawPrimitive(Tri List)
- DrawPrimitive(Tri Strip)
- DrawPrimitiveUP(Tri List) **- Only the moths use this**
- DrawPrimitiveUP(Tri Strip)
- DrawPrimitiveUp(Line List)
- StretchRect()

The Z-fighting in question is when the moths are over semitransparent glass. The glass in both of these rooms are **DrawPrimitive(Tri Strip)**.

So you could do something like:

if Room 0x16 || 0xBB {
if DrawPrimitiveUP(Tri List) && PrimitiveCount == 2
Render [this] above DrawPrimitive(Tri Strip)
}

I can still get you PIX captures if you'd like, but I'm fairly confident only the moths use that identifier type in these rooms.

**Comment by Polymega** [comment] 2023-05-15 23:30
Here you go, Elisha. I think I captured these correctly with PIX for you:

[room_0x16.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/11482594/room_0x16.zip)
[room_0xBB.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/11482595/room_0xBB.zip)

**Comment by elishacloud** [comment] 2023-05-15 23:54
First of all, the issue doesn't appear to be a zorder issue.  From the PIX logs all polygons are drawn with the same zbias.  This appears to be a draw order issue.  The game draws the moths first and then later draws the frame of glass (or whatever that is).

Note: the reason all the zbias's are the same could be because the 2D fog fix is enabled messing with the bias.  You could try disabling that to see if it solves the issue.  If this works we could just disable the 2D fog fix when in these rooms.  In fact, it might make sense to add a more surgical fix for the 2D fog fix since this fix seems to disable zbias completely for vast parts of the game.

Also, there are quite a few draw commands that use DrawPrimitiveUP(Tri List) with a primitive count of 2 in the PIX log.  However, I created a build to just increase the zbias of all the draw functions that match the criteria.

You can try with this build: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/11482652/d3d8.zip)

**Comment by Polymega** [comment] 2023-05-16 00:32
Thanks, Elisha. Unfortunately that doesn't resolve the layering problem with the moths.

> the issue doesn't appear to be a zorder issue. From the PIX logs all polygons are drawn with the same zbias. This appears to be a draw order issue.

Apologies on the misinformation then. I'm going off of sleep deprived memory as of late. 😛 

> Note: the reason all the zbias's are the same could be because the 2D fog fix is enabled messing with the bias. You could try disabling that to see if it solves the issue. If this works we could just disable the 2D fog fix when in these rooms. In fact, it might make sense to add a more surgical fix for the 2D fog fix since this fix seems to disable zbias completely for vast parts of the game.

This was one of the first things I checked back when I first noticed it. The 2D fog fix _does not_ cause this to happen. This looks to be a vanilla PC bug that was carried over from the Xbox version.

**Comment by Polymega** [comment] 2023-05-16 00:50
If you'd like to see this first-hand for yourself, load the save **Apartments 2F (0:15)** (near the top), open your map, head to Room 202 (right near you where you spawn in), and go to the spot shown below.

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/f5e4e86b-a5ee-423a-a5d5-19babbd8943f)

When the moths go over this picture frame (red arrows), you'll see the layering error in effect. It may help to increase the game's brightness to better see.

**Comment by elishacloud** [comment] 2023-05-16 19:30
It looks like depth stencils are disabled just before the moths are drawn.  This means no zbias setting takes effect for the moths.

**Comment by elishacloud** [comment] 2023-05-16 21:06
Since depth stencils were not properly setup in either of these rooms I had to add code to set them up and enable them for both the moths and the glass/windows in both of these rooms.

I tested room 0x16 and it works there.  I could not test room 0xBB, but I used the PIX log you sent me to write the code for this.  Hopefully this works for you.

Here is the testing build:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/11492023/d3d8.zip)

**Comment by Polymega** [comment] 2023-05-16 21:49
Thank you! I ran some tests and found a couple issues:

### Room 0x16
These two glass panes aren't behaving correctly, making the moths render behind the glass still:

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/60dac503-4a11-4551-8e4d-fb042ec8474e)

This is a bit tricky to explain, but SH2 uses "fake ambient occlusion." They achieved this by using a simply black-to-transparent gradient texture and placed in on polygons that surround things like picture frames and tables. This gives it a fake, subtle "shadow" around its outside edges.

The layering issue also looks to affect this geometry as well. See GIF below as an example:

![Screenshot-2023-05-16-17-26-48](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/99b1c16d-45eb-4cb5-8b85-d705a0c820e9)

The moths are _always_ being rendered _behind_ James. For example, these two moths should be in front of him:

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/3d688aab-56dd-4449-b3d3-045f685b9f18)

# Room 0xBB
Sadly, this fix invokes a lot of layering issues. See images below for examples:

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/2a11c44f-096b-4d1b-ac02-4ef1c6e9bb29)

All of the stairs/scaffolding underneath this metal floor are being render above the metal floor and fog effects. Also, James' shadow is white-ish here:

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/2157ccba-29e3-40c9-b99e-c4f88e3d7cd1)

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/5920d146-0a11-480c-aba7-110acf4ae455)

It's hard to tell, but I believe the glass windows are also rendering above the fog effects:

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/a01f8d88-2691-4e48-b3b9-f34d30b69ea2)

And like the other rooms, James and Mary are _always_ rendered on top of the moths. These moths should be in front of them, as an example:

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/ffbb06a4-2a7b-4e91-8dc0-3282554060ea)

Referencing this same image, it looks to have the same alpha blending issue as what is seen for the "fake ambient occlusion" in the other room:

![002](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/2b4b3f32-020d-4532-a636-a3949130c453)

----------------

So thinking about this some more, the main issue is whenever the moths are rendered over glass and the "fake ambient occlusion" geometry. However, in both of these rooms, I don't believe the camera is _ever_ positioned in such a way to render James/Mary _behind_ the glass/fake AO.

Perhaps we shouldn't be focusing on rendering the moths _on top_ of these things, but rather the glass/fake AO _behind_ the moths? (If that makes sense?)

--------------

> I could not test room 0xBB, but I used the PIX log you sent me to write the code for this.

Yeah, this ones a little more time-consuming to test since you cannot save in the actual boss room. 

You can load **Hotel Alternate 1F (0:59)** (near bottom of save list), go through the door right in front of you, climb up all the stairs, initiate the cutscene of meeting Mary, skip the cutscene, then run away from her. With enough distance between you and her, she'll do her moth attack.

**Comment by Polymega** [comment] 2023-05-16 21:57
As a point of reference, here's how the moths alpha textures should be rendered:

![Screenshot 2023-05-16 17-56-05](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/09f11740-a9f6-4db1-b350-45995485f39c)

**Comment by elishacloud** [comment] 2023-05-16 23:28
> These two glass panes aren't behaving correctly, making the moths render behind the glass still

This is easy to fix.  I already put a fix in for this.  Just had to add those two draw functions.

> The layering issue also looks to affect this geometry as well.

Ok, this is hard to fix.  The issue is that the moths are drawn first and then the glass.  If I change the zorder and tell the game to draw the moths over the top of the glass then you have this effect where the glass is missing at the edge of the wings.

The right fix for this would be to draw the moths _after_ the glass/windows have been draw.  This means rearranging the game code.

The only other option would be for me to try and remember all the API calls for the moths and skip the calls and then replay them after the glass/windows have been drawn.

**Comment by elishacloud** [comment] 2023-05-16 23:52
> As a point of reference, here's how the moths alpha textures should be rendered:
> 
> ![Screenshot 2023-05-16 17-56-05](https://user-images.githubusercontent.com/27395260/238780722-09f11740-a9f6-4db1-b350-45995485f39c.png)

Can you send me a PIX single-frame capture of this screen?  I want to understand when and how the fog is drawn.

**Comment by Polymega** [comment] 2023-05-17 00:05
Sure thing. Here you go: [Run1.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/11492984/Run1.zip)

**Comment by Polymega** [comment] 2023-08-02 17:56
Check out the video below. Pay attention to the picture centered above the bed. When the camera is close to this wall/picture, the layering issue occurs. But if I step back far enough it no longer occurs.

https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/32c39673-0527-4c3a-9faf-e1d34525a05b

Maybe it's a distance-based thing relative to the camera? Not sure what to make of that, but something to point out...

**Comment by Murugo** [comment] 2023-08-17 08:38
Hi all, here is an attempted fix for this issue: [d3d8.dll.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/12366866/d3d8.dll.zip)
Working branch is [here](https://github.com/Murugo/Silent-Hill-2-Enhancements/tree/moth-draw-order).

Most transparent objects in the scene are sorted from back to front, including map decals, fog and other particle effects. The pointer to the start of this list is at `00942348`. The moths are depth sorted as well, but there is a bug in the function that calculates the sort index for each moth (`FUN_4A4B80`). As a result, the game thinks that the moths are farther into the scene than they actually are, causing most other objects to draw on top of them.

IIUC, the fix is to add a missing multiply operation which corrects the sort index based on the current draw distance, similar to how indices are computed for other objects.

<details>
<summary>Images</summary>
<br>

![moths-1](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/49109252/e78e010f-8f8d-4997-9763-7ade2ac631b7)
![moths-2](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/49109252/c2657caf-bdd3-4ae8-9604-1b8b7912b605)
</details>

**Comment by Polymega** [comment] 2023-08-17 18:23
Is there nothing you can't do?!? 

![were-not-worthy-waynes-world](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/01e26df0-edc3-4f94-9b11-2c769cf96aa4)

Simply amazing. I haven't done a full playthrough (not sure if it's needed?), but everything looks absolutely perfect.

**Closed** 2024-05-23 01:11 UTC
