### ISSUE TITLE
error files unavailable

### ISSUE THREAD

**Issue by nizcoz** [elishacloud/Silent-Hill-2-Enhancements#612] opened 2022-10-04 09:45 UTC
Hi! When i try to install the sh2eesetup.exe appears this message: Error files unavailable and i can't to continue the installation. What can i do? Thanks a lot!

**Comment by mercury501** [comment] 2022-10-04 15:18
Have you tried redownloading the setup tool, running it from the desktop and/or from the sh2 folder itself?

**Comment by Polymega** [comment] 2022-10-04 15:27
It's the same issue as here: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/563#issuecomment-1254280256

And, at this time, I have no idea what the problem is.

**Comment by Polymega** [comment] 2022-10-28 22:46
Server migration is done and distribution for the project's file packages has been changed to a more stable solution.

I am going to close this ticket out . For sake of management/consolidation, if you run into any troubles still with the Setup Tool, [please report them here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/647).

**Closed by Polymega** 2022-10-28 22:46 UTC
