### ISSUE TITLE
60 FPS: Sound Glitch for footsteps when running

### ISSUE THREAD

**Issue by wesker265** [elishacloud/Silent-Hill-2-Enhancements#733] opened 2023-02-25 21:43 UTC
In 60 FPS mode, there is a brief audio glitch when James begins running. It does not happen when walking in 30 or 60 FPS mode.

The footstep sound should go tap ..... tap .... tap .... tap ....tap .... tap (Like in 30 FPS)

But it goes tap....tap-tap-tap....tap .... tap .... tap .... tap (in 60 FPS)

This is most apparent in open areas like on the streets and not so much in closer quarters like the first floor apartment

**Comment by Polymega** [comment] 2023-02-26 00:28
Hmm, I am not hearing this. 

https://user-images.githubusercontent.com/27395260/221385826-2cdcae86-2f9d-425e-8450-22bfdee25f1e.mp4

Are you able to record video/audio of it happening?

**Comment by MarioTainaka** [comment] 2023-02-26 01:33
> In 60 FPS mode, there is a brief audio glitch when James begins running. It does not happen when walking in 30 or 60 FPS mode.
> 
> The footstep sound should go tap ..... tap .... tap .... tap ....tap .... tap (Like in 30 FPS)
> 
> But it goes tap....tap-tap-tap....tap .... tap .... tap .... tap (in 60 FPS)
> 
> This is most apparent in open areas like on the streets and not so much in closer quarters like the first floor apartment

Does this happen on dirt surfaces as well? for example during the first section when you encounter the line figure? Does it only happen when walking or when you turn?

**Comment by Polymega** [comment] 2023-02-26 01:39
I know that, if you time it _just right,_ you can make him "stutter step" whenever James goes from walking to running. I also think, on rare occasion, this can also happen when he transitions from the beginning of his run into full sprint (which he can do while in outdoor areas). The timing of the animation change can cause that to happen, which I'm pretty sure can happen on all versions of the game.

**Comment by wesker265** [comment] 2023-02-26 01:51
For me, it's either from walking to running, or full stop to running (with
running by default enabled instead of walking). It happens on the street
outside the trailer on Saul street, and pretty much any street.

It did not happen on the first floor of the apartment.

**Comment by Polymega** [comment] 2023-02-26 01:56
Is it what you hear near the end of the video below? If so, that's normal behavior exhibited in all versions of the game. As previously mentioned, it's the transition of his movement from one animation to another. 

https://user-images.githubusercontent.com/27395260/221388090-8a07b0ff-992d-42e8-bac4-b986a4ab57ba.mp4

**Comment by wesker265** [comment] 2023-02-26 02:05
No, I'll try to take a video of the issue later tonight.

**Comment by wesker265** [comment] 2023-02-26 08:41
https://user-images.githubusercontent.com/45540160/221400615-998a63b0-998c-4dee-bc69-db64d966735b.mp4

Here is the issue outside the apartment. I can confirm that this does not happen in 30 FPS mode.

Inside the apartment in 60 FPS, the issue does not occur. I can also confirm that this sound occurs when running down the dirt path after getting the map out of the car too.

I did try reinstalling the audio enhancement pack too, which did not fix the issue.

**Comment by MarioTainaka** [comment] 2023-02-26 15:25
> Here is the issue outside the apartment. I can confirm that this does not happen in 30 FPS mode.
> 
> Inside the apartment in 60 FPS, the issue does not occur. I can also confirm that this sound occurs when running down the dirt path after getting the map out of the car too.
> 
> I did try reinstalling the audio enhancement pack too, which did not fix the issue.

I think this might just be the animations transitioning. running at 60FPS speeds that up a tiny bit.. could be wrong tho.

**Comment by Polymega** [comment] 2023-02-26 16:39
> Here is the issue outside the apartment. I can confirm that this does not happen in 30 FPS mode.
> 
> Inside the apartment in 60 FPS, the issue does not occur. I can also confirm that this sound occurs when running down the dirt path after getting the map out of the car too.

Perfect. Thanks for the video. I understand now. We'll try and take a look into this.

The reason why this is only happening outdoors is because, while outdoors, James is allowed to run faster than he can while indoors. I'm not sure what the cause is, but I'm going to guess the transition of him changing from his "starting to run" animation to "running full speed" animation becomes slightly desynced at 60 FPS, allowing him one extra "footstep state" before the change in that animation happens.

**Comment by oozaru2020** [comment] 2023-02-26 18:51
i had this problem my pc is a potato but what i did was to put the fog on simple and i didn't hear the double step anymore i don't know if it works for others or if i am the weird one xd

**Comment by Polymega** [comment] 2023-02-26 21:06
I was able to replicate the video wesker265 shard above but, ever since, I cannot replicate it anymore.

**Comment by Polymega** [comment] 2023-02-28 00:46
[01FB10A8 float](https://github.com/JokieW/SilentHillDatabase/blob/master/SH2/SH2%20PC%20memory%20addresses#L285) is James' speed. When using a controller, more instructions are called/used. From the highlighted instruction downwards are exclusive to moving James forward with a controller.

![image](https://user-images.githubusercontent.com/27395260/221721766-e76ba926-3160-484d-b90b-c180847e1350.png)

Snooping around in this memory region, I found `sh2pc.exe+15837E - fcomp dword ptr [006CDDA0]`

`006CDDA0` has a default value of `3.5f`. I changed it randomly to `1` for fun and it fixed it. Obviously it's not safe to just change something willy-nilly, but maybe this could be a lead for something?

**Comment by Murugo** [comment] 2023-03-01 09:57
Thanks @Polymega for the references!

Here's a video showing what causes the extra footstep (easier to see with slowed playback at the end):

https://user-images.githubusercontent.com/49109252/222101248-0dd047b4-e666-4288-96c6-009758df187e.mp4

`FUN_0054AD50` is the handler which plays footstep sounds for James. The function has a switch statement which hard codes when to play a footstep sound depending on the current animation. For example, during a run animation (24 frames long), the right footstep plays at frame 5 and the left footstep plays at frame 17. The function uses two boolean flags to track whether each footstep has been played in the current animation loop, "Right Footstep" (`01FB8070`) and "Left Footstep" (`01FB8071`). Both reset to 0 when the animation loops around.

In the video above, notice what happens when James' animation switches from index 13 (fast run) to 14 (full sprint):
* Just before the switch, animation 13 has looped back to frame 0. Both footstep flags reset to 0.
* On the switch to animation 14, the current animation frame is now 23. The handler thinks that both footstep sounds need to be played since the current frame is greater than both 5 and 17. Both flags flip to 1, causing the "extra" footstep.

When using a controller (D-pad up), the animation change from 13 -> 14 happens to fall perfectly at the loop boundary that it will cause the extra sound every time. The reason why this does not happen with a keyboard (pressing W) is because for some reason, the starting move speed for James is higher using the D-pad (2.0f instead of 1.5f).

Two ideas for workarounds:
1. Set the initial run speed for controller movement to 1.5f, same as keyboard. This won't fix every possible case where an extra sound will play (e.g. could this happen when slowing down from a run to a walk at the right moment?).
2. Add ASM to the footstep handler: detect if both left and right footstep flags would flip from 0 -> 1 on the same frame (based on that switch statement, this shouldn't happen). If so, don't play any footstep sounds for the current frame.

**Comment by Polymega** [comment] 2023-03-01 14:21
Murugo, have I told you how much of a joy and interest it is to read your posts? I appreciate you taking them time to write things out, as I get to learn more about this game along the way. 😊 

> Two ideas for workarounds:

What do you feel is the better/safer solution? I ultimately trust your decision on this. I'll add some thoughts and opinions to your suggestions, though:

> Set the initial run speed for controller movement to 1.5f, same as keyboard. This won't fix every possible case where an extra sound will play, 

This sounds nice because it makes things consistent/"fair" among input devices. And if there ever came a day where people speedrun our project, a controller user wouldn't have this as an advantage over KB/M users. (Even if the starting animation only lasts half a second, that `0.5f` difference might shave off a second or two over the course of a full run?)

Side note: Why is it that this behavior isn't exhibited at 30 FPS? 🤔 While the issue isn't noticeable at 30 FPS, I can't help but to wonder if this discrepancy is also there at that framerate, to some extent. I mean, that `0.5f` speed difference is surely always there, regardless of framerate, yes?

> [...] e.g. could this happen when slowing down from a run to a walk at the right moment?

Yep. This behavior can be done/exhibited through normal character input use (in all game versions): https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/733#issuecomment-1445246000

So there's definitely other instances where his footsteps will "double up" if certain actions are done in certain ways.

> Add ASM to the footstep handler: detect if both left and right footstep flags would flip from 0 -> 1 on the same frame (based on that switch statement, this shouldn't happen). If so, don't play any footstep sounds for the current frame.

This sounds totally foolproof for all scenarios. A few questions come to mind with this approach:

- Are the ASM instruction you found _exclusively_ for character footsteps and nothing else?
   - Does this include Maria's footsteps in her BFaW campaign (if needed... I haven't tested for this issue on her campaign).
   - Does this include others' footsteps, such as Maria NPC or enemies? If it includes others' footsteps, does this help or worsen their footstep SFX behavior?
- Are there any instances in James' animation states where his footsteps would _purposefully_ "double up"? I don't think there is but I'm not sure at the moment.

**Comment by Murugo** [comment] 2023-03-03 10:03
I agree that different input devices should be consistent. I am leaning towards implementing both approaches unless there are any objections.

> Side note: Why is it that this behavior isn't exhibited at 30 FPS? 🤔 While the issue isn't noticeable at 30 FPS, I can't help but to wonder if this discrepancy is also there at that framerate, to some extent. I mean, that 0.5f speed difference is surely always there, regardless of framerate, yes?

At 30 FPS, animation 14 starts at frame 0 instead of jumping back to 23, avoiding the footstep bug. I think there is a small chance this can still happen at a lower framerate, but it is hard to say without better understanding how the game handles interpolation between animations.

https://user-images.githubusercontent.com/49109252/222680024-63fc812a-047b-4069-97d0-6a162405918f.mp4

> - Are the instructions you found exclusively for character footsteps and nothing else?

Yes, AFAICT the handler is for footstep sounds only.

>   - Does this include Maria's footsteps in her BFaW campaign (if needed... I haven't tested for this issue on her campaign).
>   - Does this include others' footsteps, such as Maria NPC or enemies? If it includes others' footsteps, does this help or worsen their footstep SFX behavior?

I was able to find different functions that play footsteps for each entity. Examples:
* James: `FUN_0054AD50`
* Maria (BFaW): `FUN_00549500`
* Maria (AI): `FUN_0052C660`
* Lying Figure: `FUN_004C40B0`
* Abstract Daddy: `FUN_004B66A0`

At minimum we can patch the first two, in case this issue also happens in BFaW. This shouldn't have any impact on NPCs or enemies.

>   - Are there any instances in James' animation states where his footsteps would purposefully "double up"? I don't think there is but I'm not sure at the moment.

Thankfully, I don't see any cases in either of James or Maria's handlers where both left and right footsteps play on the same frame.

**Comment by Polymega** [comment] 2023-03-03 18:48
> I am leaning towards implementing both approaches unless there are any objections. [...] At minimum we can patch the first two, in case this issue also happens in BFaW. This shouldn't have any impact on NPCs or enemies.

No objections here. I advocate whatever you think is best; you've already more than proven your judgment with this type of work! 

I also just tested Maria from BFaW and, yep, her footsteps double the same as when you play James with a controller at 60 FPS. I'm liking your idea of just patching James and Maria's (BFaW) footsteps, namely so as to not drive yourself too crazy over this.

**Comment by Murugo** [comment] 2023-03-12 02:52
Here is a build with just the double footstep fix (enabled automatically with `SetSixtyFPS`): [d3d8.dll.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/10949882/d3d8.dll.zip)

(I'm still testing the move speed adjustment to make sure it is accurate with PS2. I might send out a separate PR for this since the two are easier to test in isolation.)

**Comment by Polymega** [comment] 2023-03-12 20:37
Beautiful work, as always! Tested on all three binaries and everything looks ~~sounds~~ great.

**Comment by wesker265** [comment] 2023-03-13 09:12
I tested the file and it fixed the issue on my end. Thank you!

**Comment by Polymega** [comment] 2023-05-13 01:20
Thanks for reporting this! We have a fix in place for this which will officially be a part of our next project update.

**Closed by Polymega** 2023-05-13 01:20 UTC
