### ISSUE TITLE
Game running a little choppy while moving?

### ISSUE THREAD

**Issue by jreeds26** [elishacloud/Silent-Hill-2-Enhancements#282] opened 2020-05-24 19:01 UTC
I am not sure how to explain this, but when I am just sitting still, the game looks amazing. When I move like left to right for example, it kind of stutters or seems a tad choppy every second or so. It's just not completely smooth when moving to put it best.

I am using a 4k laptop with a nvidia 1080 (not sure if that matters). 

I installed all of the available mods, except the two audio ones. I checked some of the trouble shoots out on the page and nothing seemed to work. And my game is set to Core 1. I think there was like 8 options to choose for that.

I am not really tech saavy, and was hoping if anyone could possibly help me with this?

Thanks :)

**Comment by Polymega** [comment] 2020-05-24 19:19
Funny timing as I was testing something similar to this just last night. I notice it too; it doesn't happen frequently or consistently, but every once and a while there will be a little choppiness.

For my test, I simply ran James left-to-right, right-to-left at the observation deck while keeping an eye on the trees in the background to detect any choppiness.

![image](https://user-images.githubusercontent.com/27395260/82762809-21dbcc80-9dd1-11ea-9797-6987bc7b29c9.png)

Granted, my testing pool here is _very limited_ (as I only tested one spot in the game), but this was just a quick test for me, after all.

Anyway, I then decided to test other platforms last night and here is what I found:

**SH2:EE:** Some choppiness
**PCSX2:** Some choppiness
**PS2 (original hardware):** Smooth
**Xbox (original hardware):** Smooth

For PCSX2, I'm using OpenGL (Hardware) for the renderer, with 6x native resolution and 16x anisotropic filtering.

For PS2/Xbox original hardware, there _may_ be choppiness going on here that I can't easily see due to the low, 480 resolution.

For our project, the PC version is known for threading issues (which cause things like the sound looping problem). The choppiness _might_ have something to do with that. And, if that's the case, we'd like to rectify the threading issues sometime down the line which might also address any choppiness going on. We'd need to do some more tests with this down the line.

For now, it may just be inherent choppiness you're experiencing or, if it's worse, try setting `SingleCoreAffinity` in the `d3d8.ini` file to a value of 2, 3, or 4 and see if that helps any.

**Comment by jreeds26** [comment] 2020-05-24 19:36
Thanks,

Yeah thats what I have been doing. James himself seems to move fine, but it seems like the environment outside from him stutters/slighly freezes for a split sec every second or so. Like you, I also have my PS2 hooked up, and when I run around, its completely flawless. I've noticed on some Youtube videos of others show casing the enhanced edition, it seems to run perfect for them, which made me think it was on my end, who knows.

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4674256/d3d8.log)

**Comment by Polymega** [comment] 2020-05-24 19:40
Yeah, it's confusing me as well. On one hand, if I also experience this on PCSX2 I can't help but to wonder if it's something inherent to the game's code? But on original hardware it doesn't look to be an issue? 

I do know that `d3d8to9` will make characters (particularly Angela) very "jittery" during cutscenes. You can try setting `d3d8to9 = 0` to see if that helps any. For my tests, it helps with character animations, but I still get the choppiness in the environments (which makes me wonder if it's something inherent in the game's code when played at higher resolutions).

For now, I'm not sure what to make of it. But when the time comes and we look into fixing the threading issue, maybe a happy coincidence from it will be fixing any choppiness.

**Comment by elishacloud** [comment] 2020-05-24 20:43
A few other things you may want to test:

1. If you are using an Nvidia card you may want to try disabling `FixGPUAntiAliasing`.
2. Also, just for a test, try using the original PC sound files.  The enhanced sound files are much larger and may introduce a slight delay on loading them, depending on your drive speed.
3. Try removing all other dll's except `d3d8.dll`.  So remove `dsound.dll`, `dinput8.dll` and `d3d9.dll`.
4. Try disabling `AnisotropicFiltering`.
5. Try disabling `UseCustomModFolder`.

Note: I am using an old computer I built about 4 years ago with an i7 CPU with 4 cores 4GHz hyper-threading (to get 8 cores), 16GBs of RAM and an overclocked Nvidia 980 GTX.  I have an Adaptec SATA RAID controller with on-board cache and two separate RAID 1 drives.  My system drive is a mirrored dual 1TB SSD and I am running Silent Hill 2 on a separate mirror with dual 8TB WD Red hard drives.  I mirror both my system drive and data drive for data protection.

I am not seeing any slowdown or choppiness on my system.

**Comment by Polymega** [comment] 2020-05-24 21:04
Okay, I'm _really_ confused now. I actually experience it in the vanilla build as well but there's some oddities about this: 

https://youtu.be/sg90IuQ-MuU

What's weird is OBS didn't pick up the jitters I saw on the game screen half the time, and the other half of the time OBS would pick up jitters I wasn't seeing on the game screen. I had OBS to capture at 30 fps.

Then, once I watched it on YouTube, I didn't really see any jitters, but the ones I did I went back to re-watch thosee parts on the YouTube vid and I couldn't see the jitters anymore. Huh?

I think this might have something to do with the monitor's refresh rate then?

**Comment by jreeds26** [comment] 2020-05-24 22:09
Ok thanks.

Going to try that here in a bit. I was going to ask though - I noticed in a lot of videos, if not most, they are all mounting each disc for the game when installing. Not sure, but when I downloaded the game from a link a friend sent me, I didn't have to do any of that disc stuff. At all. I am guessing that has nothing to do with the issue, but thought I would throw that out there.

**Comment by AeroWidescreen** [comment] 2020-05-24 23:52
That "choppiness" has always been there as far as I know. I assumed it was due to the threading issues. 60 FPS seems to greatly alleviate it, but I still get the occasional stutter about every 10 seconds or so.

**Comment by jreeds26** [comment] 2020-05-25 00:33
How do you get 60 fps?

Is it default to 30..or?

**Comment by Polymega** [comment] 2020-05-25 00:49
Info and warnings on 60 fps can be found here:
https://www.resetera.com/threads/silent-hill-2-enhanced-edition-trailer-fan-mod-feb-13-2020-update-4-now-released.63926/page-3#post-29123392

**Comment by jreeds26** [comment] 2020-05-25 01:19
Thanks, that actually seemed to help the issue a little bit.

I am playing on a PS4 controller. I have DS4tool I use. Is there anyway to set controls on this? I tried in the main game option, but there is only keyboard/joypad and it wouldn't seem to let me register any keys on the PS4 controller. 

Nbd just thought i'd ask

**Comment by Polymega** [comment] 2020-05-25 01:23
DS4tool might be why you can't reassign controller inputs in the games' control options menu. We don't really offer guidance to third party software that hooks into controllers. If you want to use the DS4 as a simple plug-and-play device we offer steps to set it up here: http://enhanced.townofsilenthill.com/SH2/install.htm#controllerSetup

**Comment by Polymega** [comment] 2020-05-25 05:55
> Even when using PCSX2's OpenGL (Software) renderer (native resolution and settings) it's still choppy on there, too.

While an emulator, PCSX2 is good at what it does. Since I also see choppiness on the observation deck while using this software, even when using different renderers/resolutions, I _think_ this may be something inherent to the game. Maybe it's not as noticeable on native hardware due to the low resolution?

It's hard to say right now. But my official response to this will go back to that we hope to address the threading issue with this game in the future, and maybe that might also help with situations like this. Thanks for letting us know!

**Comment by Badore90** [comment] 2020-05-25 13:40
> While an emulator, PCSX2 is good at what it does. Since I also see choppiness on the observation deck while using this software, even when using different renderers/resolutions, I think this may be something inherent to the game. Maybe it's not as noticeable on native hardware due to the low resolution?

On Ps2 there isn't any choppiness at all I can guarantee (on CRT you can't avoid to see even the most minimal stutter, if present).

On Xbox there are a few fixed chops I think you know about (the one at the toilet close-up in the first game's cut-scene and some others). But it's all very smooth on the observatory parking area.

**Comment by Polymega** [comment] 2020-05-25 16:15
> On Xbox there are a few fixed chops I think you know about (the one at the toilet close-up in the first game's cut-scene and some others). 

This happens during any cutscene as soon as its corresponding dialogue file is called within `voice.asf`. 

Another easy one to spot for this is upon exiting the beginning bathroom. As soon as James passes the pole is when Mary starts to read her letter. Because this is where the dialogue audio starts/is called, you will seem the momentary pause here. 

This is something that happens and is carried over from the Xbox version. Elisha is aware of this one. I'd like to see if that one could be addressed sometime down the line.

**Comment by Badore90** [comment] 2020-05-25 23:13
> On Xbox there are a few fixed chops I think you know about (the one at the toilet close-up in the first game's cut-scene and some others).
> 
> This happens during any cutscene as soon as its corresponding dialogue file is called within voice.asf.
> Another easy one to spot for this is upon exiting the beginning bathroom. As soon as James passes the pole is when Mary starts to read her letter. Because this is where the dialogue audio starts/is called, you will see the momentary pause here.

Yes, thank you for the info. I didn't knew it was related to the dialog calls.

Aside that the Xbox version is fluid to suck, I tried it before to be sure on the observatory (doing back and forth as in your video). Since James/the camera moves quite slow it gives almost a feeling like the game is running at 60fps.

**Comment by elishacloud** [comment] 2020-05-31 06:00
@jreeds26,

> Not sure, but when I downloaded the game from a link a friend sent me, I didn't have to do any of that disc stuff.

This could be because of the `CheckForAdminAccess` or `AutoUpdateModule` options.  Try disabling these two options and see if this issue still happens.

**Comment by DD-Indeed** [comment] 2020-06-05 08:04
Confirming that the latest update introduced choppiness. With the previous update, the game run butter smooth even with 60fps command, but now it seems to slow down on certain places. Especially on outdoors. Could be related to fog/level load pop in.

**Comment by elishacloud** [comment] 2020-06-05 15:50
@DD-Indeed, try disabling the `FixGPUAntiAliasing` option in the `d3d8.ini` file and let us know if that helps or not.

**Comment by DD-Indeed** [comment] 2020-06-05 16:04
> 
> 
> @DD-Indeed, try disabling the `FixGPUAntiAliasing` option in the `d3d8.ini` file and let us know if that helps or not.

Did that, didn't help. I also tested out with other settings like core affinity, disabling ReShade, disabling anti-aliasing etc. And I did the tests over here at the Parking Lot road, where you have the first battle.

![kuva](https://user-images.githubusercontent.com/58600482/83898311-69fad780-a75f-11ea-82c7-7e10b486bf90.png)

**Comment by Polymega** [comment] 2020-06-05 16:46
On all three PCs I play and test the game on there's always been some degree of choppiness, regardless of settings I adjust. It might be due to the threading issues the game has or could be something else inherent going on.

Do you think there has always been some choppiness for you but it's something you've noticed this time around? Something akin to a placebo effect from before?

Also, what if you decrease the value for `IncreaseNoiseEffectRes`, does that help? Try setting it to default (`512`) to see if that helps any with performance.

**Comment by DD-Indeed** [comment] 2020-06-05 17:00
> 
> 
> On all three PCs I play and test the game on there's always been some degree of choppiness, regardless of settings I adjust. It might be due to the threading issues the game has or could be something else inherent going on.
> 
> Do you think there has always been some choppiness for you but it's something you've noticed this time around? Something akin to a placebo effect from before?
> 
> Also, what if you decrease the value for `IncreaseNoiseEffectRes`, does that help? Try setting it to default (`512`) to see if that helps any with performance.



Funny thing is that it ran butter smooth previosly on me, I didn't notice these at all. WIll try again with the older version, if I can find it still.

NoiseEffect is on default value, 512, has been all the time.

**Comment by Polymega** [comment] 2020-06-05 17:05
My eyes might be playing tricks on me as the noise grain looks very tiny. Are you playing on 4K?

With our most recent update we've instructed users on recommended settings to enable for GPU AA. Is this also your first time using GPU AA for the game? If so, that might be a part of the performance hit you're experiencing, depending on hardware.

**Comment by DD-Indeed** [comment] 2020-06-05 17:13
> 
> 
> My eyes might be playing tricks on me as the noise grain looks very tiny. Are you playing on 4K?
> 
> With our most recent update we've instructed users on recommended settings to enable for GPU AA. Is this also your first time using GPU AA for the game? If so, that might be a part of the performance hit you're experiencing, depending on hardware.


Nope, 1440p resolution on me, because I didn't see any major difference between that and 4K imo.

The noise you see in the picture is through ReShade, the ingame noise is too rough imo, so I added it with ReShade. It's very very tiny, barely noticeable, to mimic real life fog noise (you can actually see the tiny water particles on certain types of fog in real life).
But I tried the game disabling the ReShade, so it wasn't about that either. 

And with AA, I only enabled/disabled it through the config file, should I have put it on or tweak setting on NVidia Control Panel ?


And my hardware should be more than enough to run this game:

CPU - Ryzen 5 1600
GPU - GTX 1070
Hard Drive - 1Tb Samsung QVO 860 SSD
OS: Win x64

**Comment by DD-Indeed** [comment] 2020-06-05 17:41
I got it! I had the Forced Windowed Mode-Enabled and Fullscreen Windowed Mode-Enabled. I changed the Forced Windowed Mode to Disabled, and that did the trick. Now it runs again smooth.

**Comment by jreeds26** [comment] 2020-06-06 04:34
Wow..thanks. That worked for me too. Disabled forced windowed mode and its perfectly smooth now.

Now i can experience this game in awesome graphics!

**Comment by jreeds26** [comment] 2020-06-06 05:13
I don't mean to look a gift horse in the mouth, but thought I would ask. During cut scenes, when people are talking, there is a delay from when they say something and their mouth moving. Is this a common thing? Just curious if it may be a simple fix or something, otherwise nbd.

Thanks

**Comment by DD-Indeed** [comment] 2020-06-06 16:13
By default, the d3d8.ini has the screen settings like this:

; Enables forced windowed mode. (0|1)
EnableWndMode = 1

; Enables window border. Requires EnableWndMode = 1 to work. Game's vertical resolution must be 32 pixels or less than the display's resolution for border to appear. (0|1)
WndModeBorder = 0

; Enables fullscreen windowed mode. Requires EnableWndMode = 1 to work. (0|1)
FullscreenWndMode = 0




Swapping them by putting...:

EnableWndMode to 0

FullscreenWndMode to 1 

...fixes the issue


Why isn't it like that by default ? 

Because the game seems to lag every single time when you go through door, and that has to be related to the issue where the game jumps into Window-mode when going through the doors on the original stock version of the game, and then jumps back to fullscreen. 

So for next update, you should swap those settings.

**Comment by Polymega** [comment] 2020-06-06 16:33
- [`EnableWndMode` must be enabled to use `FullscreenWndMode`.](http://enhanced.townofsilenthill.com/SH2/config.htm#FullscreenWndMode) If you just enable `FullscreenWndMode` it does nothing. Essentially you're just playing in normal fullscreen mode.
- We enable `EnableWndMode` by default [to fix the delay in screen transitions for AMD users, when playing in fullscreen mode while `d3d8to9` is active.](http://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#transition-times-between-navigating-menus-areas-etc-is-noticeably-delayed-or-sluggish)
- We also enable `EnableWndMode` by default so if a user adjusts `ResX` and `ResY` [and sets it to a non-supported resolution by their display, it won't lock the game on launch.](http://enhanced.townofsilenthill.com/SH2/config.htm#ResXResY)
- We don't enable **both** `EnableWndMode` and `FullscreenWndMode` by default because, on Windows 7, if you use a non-native resolution but that's still supported by your display device, [it makes the game have a gray, "washed-out" image.](http://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#the-games-visuals-have-a-gray-washed-out-look-andor-the-games-visuals-are-stretcheddistorted)

I've tested the game in fullscreen mode and still get the choppiness, so I'm unsure if being in windowed mode or not is the actual cause here. If you're playing in 60 fps, that's probably not the best way to test. 60 fps just puts a band-aid over the issue; you need to fix it for 30 fps (where it's more noticeable) and 60 fps would then also benefit from it.

> During cut scenes, when people are talking, there is a delay from when they say something and their mouth moving. Is this a common thing?

If it's just _slightly_ off then, yes, this is normal. Lip syncing was never stellar for this game. Something I've noticed even 19 years ago.

**Comment by DD-Indeed** [comment] 2020-06-06 17:21
> 
> 
>     * [`EnableWndMode` must be enabled to use `FullscreenWndMode`.](http://enhanced.townofsilenthill.com/SH2/config.htm#FullscreenWndMode) If you just enable `FullscreenWndMode` it does nothing. Essentially you're just playing in normal fullscreen mode.
> 
>     * We enable `EnableWndMode` by default [to fix the delay in screen transitions for AMD users, when playing in fullscreen mode while `d3d8to9` is active.](http://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#transition-times-between-navigating-menus-areas-etc-is-noticeably-delayed-or-sluggish)
> 
>     * We also enable `EnableWndMode` by default so if a user adjusts `ResX` and `ResY` [and sets it to a non-supported resolution by their display, it won't lock the game on launch.](http://enhanced.townofsilenthill.com/SH2/config.htm#ResXResY)
> 
>     * We don't enable **both** `EnableWndMode` and `FullscreenWndMode` by default because, on Windows 7, if you use a non-native resolution but that's still supported by your display device, [it makes the game have a gray, "washed-out" image.](http://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#the-games-visuals-have-a-gray-washed-out-look-andor-the-games-visuals-are-stretcheddistorted)
> 
> 
> I've tested the game in fullscreen mode and still get the choppiness, so I'm unsure if being in windowed mode or not is the actual cause here. If you're playing in 60 fps, that's probably not the best way to test. 60 fps just puts a band-aid over the issue; you need to fix it for 30 fps (where it's more noticeable) and 60 fps would then also benefit from it.
> 



Well the funny thing is that when I disable that _EnableWndMode_, it still accept custom resolutions, even the ones beyond the monitor's native one. And the game won't freeze, and runs butter smooth even on 60fps.

**Comment by Badore90** [comment] 2020-06-06 20:59
Done a quick test. I too noticed some differences if playing in full-screen or windowed.

On my old PC, playing at his native screen resolution (1366x768):

full-screen: in the observatory there's pratically no choppiness. However the game seems to be more heavy, like when entering the path with the fog, the PC struggle and frame-rate lowered a lot.

windowed: a lot of choppiness in the observatory. The PC seems to better handle the game though, one the patch with fog the frame-rate remains much higher compared to when playing in full-screen.

**Comment by jreeds26** [comment] 2020-06-07 02:14
Thanks, The first cut scene in the grave yard in the beginning of the game, it starts of normal lip movement. Halfway through the cut scene, when its almost over, the lip sync is really off. Not sure if its just that part for now, but I'll see moving forward.
Also, not sure if anyone knows, but when I connect my laptop via HDMI to my TV to display, it runs smooth, but I see some screen tearing that randomly appears either at the top of bottom on my TV. Almost looks like a old style static TV line or something. Idk if anyone else uses their TV, thought I would point it out.
Thanks!
    On Saturday, June 6, 2020, 11:33:35 AM CDT, Polymega <notifications@github.com> wrote:  
 
 

   
   - EnableWndMode must be enabled to use FullscreenWndMode. If you just enable FullscreenWndMode it does nothing. Essentially you're just playing in normal fullscreen mode.
   - We enable EnableWndMode by default to fix the delay in screen transitions for AMD users, when playing in fullscreen mode while d3d8to9 is active.
   - We also enable EnableWndMode by default so if a user adjusts ResX and ResY and sets it to a non-supported resolution by their display, it won't lock the game on launch.
   - We don't enable both EnableWndMode and FullscreenWndMode by default because, on Windows 7, if you use a non-native resolution but that's still supported by your display device, it makes the game have a gray, "washed-out" image.

I've tested the game in fullscreen mode and still get the choppiness, so I'm unsure if being in windowed mode or not is the actual cause here. If you're playing in 60 fps, that's probably not the best way to test. 60 fps just puts a band-aid over the issue; you need to fix it for 30 fps (where it's more noticeable) and 60 fps would then also benefit from it.


During cut scenes, when people are talking, there is a delay from when they say something and their mouth moving. Is this a common thing?


If it's just slightly off then, yes, this is normal. Lip syncing was never stellar for this game. Something I've noticed even 19 years ago.

**Comment by Polymega** [comment] 2020-06-07 05:31
> The first cut scene in the grave yard in the beginning of the game, it starts of normal lip movement. Halfway through the cut scene, when its almost over, the lip sync is really off. Not sure if its just that part for now, but I'll see moving forward.

The lip syncing should look like this: https://youtu.be/J95MPYCSlLQ?t=323

**Comment by Badore90** [comment] 2020-06-07 11:38
If the video can't follow the audio timing is a problem of computing speed. you should disable Re-Shade (at least the 2 anti-aliasing options) and if it's not enough, lower the resolution.

**Comment by AeroWidescreen** [comment] 2020-06-07 16:16
Yeah, we should really get rid of ReShade. Too power hungry for the small difference we use it for. It seems like this is always an issue for people.

**Comment by Polymega** [comment] 2020-06-07 17:35
Indeed. The plan is to also drop it for next update release. If all goes well, we'll have our own shaders to fix the brightness selector (which breaks when played in windowed mode), to tint the game cool (to better match PS2 color temperature), and possibly include a SMAA shader for those who can't use GPU AA.

**Comment by DD-Indeed** [comment] 2020-06-08 08:18
Yea, I personally think that you could make it ''light'' and leave the people with powerhouses to decide that do they wanna have ReShade etc. At least my PC can handle this game like it's nothing, even on max settings + ReShade. And at least now I know what makes the game jitter on certain places, and can change that setting to get rid of that.



Which brings me to idea, that if you want to, I can share my ReShade config for the game, which is very minor difference, but I personally like it that way, makes colour space cooler etc. Here's the difference image:

![kuva](https://user-images.githubusercontent.com/58600482/84007652-6c387e00-a979-11ea-8abd-03cb6c294a82.png)


I tweaked some of the colour space values to get rid of that dominating greenish hue, and added very fine film noise to the image, since the one in the game is too rough looking imo.

**Comment by Polymega** [comment] 2020-06-08 19:45
Thanks. We'll spend a good amount of time color correcting the game's temperature if/when the time comes that we can add in a shader for that. (I spent a while doing the same for the ReShade shader that also does this, back in the day.)

Do note, for what it's worth, that you can change the game's noise grain size without the use of ReShade. Open the `d3d8.ini` file and set `IncreaseNoiseEffectRes` to a higher value (up to `4096`). 

We default it to `512` (default grain size) as that size is most familiar/comfortable to players, but you can certainly adjust it. Recently I've been using `768` to spice things up a little. It's smaller, but still noticeable for my personal preferences.

**Comment by DD-Indeed** [comment] 2020-06-08 20:45
Ah, good to know, but propably will do that once you settle down with the colour space/hue of the game. That's also quite tricky thing to get correct for the entire game, some scenes might have different hue to suit the mood better etc.

**Comment by Polymega** [comment] 2020-06-08 20:57
Comparing it to PCSX2 it's pretty straight-forward. The PS2 version just has a cool tint over the entire game image. So we could be one-and-done with our own shader, in that regard. But you're correct that, if we want or need to, we can apply different values for the shader to change the tint/temperature in specific areas of the game.

**Comment by DD-Indeed** [comment] 2020-06-08 21:32
Yea and the changes are very subtle, usually people who fiddle with ReShade, go over the top most of the time with bloom and HDR values, that yes, makes the black look dark like it should, but it also loses the details. The sort of semi-hazy look is what makes Silent Hill's so interesting. 

Also, SH2 has quite a lot of desaturation going on, since it's early 00's game, which had that sort of style to them. SH1 was much more vivid, like majority of PS1 games. So it's going to be interesting for you guys to find the best possible solution/sweet spot with those adjustments.

**Comment by Polymega** [comment] 2020-06-08 21:46
I'm an advocate of never going overboard with external, post-processing shaders. A lot of people think piling these shaders on top a game improves them... it often does the opposite.

**Comment by DD-Indeed** [comment] 2020-06-08 21:48
Absolutely. While they can be used to slightly refresh the experience, most of the time people go too far with them.

**Comment by Polymega** [comment] 2020-06-08 21:51
Yeah, here's an example of this situation: https://sfx.thelazy.net/games/screenshot/28486/

While I'm sure the shaders used will make _some_ rooms look good, they will likely negatively affect other rooms in the game.

**Comment by DD-Indeed** [comment] 2020-06-08 21:57
Yea, that is good example. While it looks somewhat okay on that area, it looks terrible on interiors, way too dark for those places.

**Comment by jreeds26** [comment] 2020-06-11 02:21
Now that I have had some time to play, even though after I disabled forced window mode to make it run very smooth, I have noticed that there are indeed certain jerks when progressing through the game. Is that maybe just the game loading in general?

I ran SH2 on my PS and noticed that it definitely does the same thing, except worse at times.

Still kind of new to this, but maybe trying to disable reshade might help that?(unless thats how it is for everyone). If so, how do I disable reshade?

Thanks :)

**Comment by DD-Indeed** [comment] 2020-06-11 05:55
> 
> 
> Now that I have had some time to play, even though after I disabled forced window mode to make it run very smooth, I have noticed that there are indeed certain jerks when progressing through the game. Is that maybe just the game loading in general?
> 
> I ran SH2 on my PS and noticed that it definitely does the same thing, except worse at times.
> 
> Still kind of new to this, but maybe trying to disable reshade might help that?(unless thats how it is for everyone). If so, how do I disable reshade?
> 
> Thanks :)

It does jerk very randomly for one frame every now and then when having that forced window mode disabled, but it won't do that anymore frequently like it did with it enabled. During previous update, this wasn't an issue. It might be related to the game's engine for sure, but this new update to d3d8.ini definitely changed something that made it more frequent.

**Comment by jreeds26** [comment] 2020-06-11 08:45
Thanks.

I did have a really bizarre question about the hang-gun auto equipping. As soon as I obtained the hand-gun from the story-line, I noticed that whenever I equip the wooden plank, and I try to use the plank, it will equip my handgun instead and fire it. No idea..

**Comment by elishacloud** [comment] 2020-06-11 09:20
> It might be related to the game's engine for sure, but this new update to d3d8.ini definitely changed something that made it more frequent.

There is only one section of code that was changed in this update that has to do with `EnableWndMode` or `FullscreenWndMode`.  I created a test build below that disables this code.  If the issue is related to the new update then this test build will fix it.

It is possible that the issue has to do with an update with either in Windows or your graphics driver that happened to coincide with this update.  The issues you are seeing is known to have been caused by Windows or a graphics driver.  You can test this by reverting back to the [old build](https://github.com/elishacloud/Silent-Hill-2-Enhancements/releases/tag/v1.5.1700.0) and seeing if the problem remains.

Here is the test build:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4763798/d3d8.zip)

**Comment by Polymega** [comment] 2020-06-13 17:46
> As soon as I obtained the hand-gun from the story-line, I noticed that whenever I equip the wooden plank, and I try to use the plank, it will equip my handgun instead and fire it.

Double check your key binds in the Control Options menu. You might have multiple actions assigned to one input.

**Comment by jreeds26** [comment] 2020-06-14 02:10
That is exactly what it was, thank you.

**Comment by DD-Indeed** [comment] 2020-06-14 10:22
> 
> 
> > It might be related to the game's engine for sure, but this new update to d3d8.ini definitely changed something that made it more frequent.
> 
> There is only one section of code that was changed in this update that has to do with `EnableWndMode` or `FullscreenWndMode`. I created a test build below that disables this code. If the issue is related to the new update then this test build will fix it.
> 
> It is possible that the issue has to do with an update with either in Windows or your graphics driver that happened to coincide with this update. The issues you are seeing is known to have been caused by Windows or a graphics driver. You can test this by reverting back to the [old build](https://github.com/elishacloud/Silent-Hill-2-Enhancements/releases/tag/v1.5.1700.0) and seeing if the problem remains.
> 
> Here is the test build: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4763798/d3d8.zip)

Okay, this is what I came up with:

- When using custom resolution beyond monitor's native one (in this case, my default is 1080p/FullHD), you have to disable _EnableWndMode_, otherwise the game will jerk when the camera changes to different angle.

Also, the test build doesn't work with custom resolution with _EnableWndMode_ disabled.

**Comment by elishacloud** [comment] 2020-06-20 04:55
> When using custom resolution beyond monitor's native one (in this case, my default is 1080p/FullHD), you have to disable _EnableWndMode_, otherwise the game will jerk when the camera changes to different angle.

Yes, I noticed this a while ago, but did not look into it at that time.  However, I fixed the issue in the latest test build.

> Also, the test build doesn't work with custom resolution with EnableWndMode disabled.

Yes, that is normal.  When using fullscreen (i.e. EnableWndMode disabled) you always need to use a resolution that both your video card and monitor can support.

Testing build:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4807361/d3d8.zip)

**Comment by Polymega** [comment] 2022-04-24 00:14
Gemini is working on a total overhaul of the game's audio engine/handling and it's looking to also noticeably improve the stutters throughout the game. 

There may be some "residual" stutters here-and-there (likely caused by other factors of the game) but, for example, running side-to-side at the beginning the observation deck trees are _very_ smooth now. (Refer to the top-most posts in this ticket.) There might be a tiny hiccup every once and a while, but through my tests so far, it's quite smooth overall.

**Comment by Polymega** [comment] 2022-04-27 14:17
Gemini's Criware audio reimplementation seems to greatly reduce stuttering/choppiness in the game. There may still be some stuttering/lag here-and-there due to other factors with the game, but this new audio solution makes for a marked improvement. As such, I'm going to say this has been addressed and will close the ticket. You can use a test build with this feature until the next official update: https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8568012/d3d8.zip

**Closed by Polymega** 2022-04-27 14:17 UTC
