### ISSUE TITLE
Problems with the installation of the files

### ISSUE THREAD

**Issue by LuniqueStar** [elishacloud/Silent-Hill-2-Enhancements#558] opened 2022-07-06 20:48 UTC
I first want to say that i have already downloaded the mod when there wasn't a SetupTool, but from the update video of The town of Silent Hill channel they said it was fine to re-download the files using the setup tool. When i try to download the files an error popup and say "Runtime  Error (At 134:426) Failed to check free space". What went wrong? Do i need to not redownload some files?

**Comment by Polymega** [comment] 2022-07-06 20:54
Thank you very much. @nipkownix could I bother you to help with the troubleshooting?

**Comment by nipkownix** [comment] 2022-07-07 04:56
Hmm, it is failing [here](https://github.com/nipkownix/SH2EE-web-installer/blob/4d3a1fa0d9e2b4be16e9f30c07805ec37f0e17e5/includes/Util.iss#L26), but this is a native Inno Setup function, so it should be working with no problems?

@LuniqueStar, could you share some info about your system? What version of Windows are you using? Is it 32 bits?

**Comment by LuniqueStar** [comment] 2022-07-07 09:47
> Collaborator



> Hmm, it is failing [here](https://github.com/nipkownix/SH2EE-web-installer/blob/4d3a1fa0d9e2b4be16e9f30c07805ec37f0e17e5/includes/Util.iss#L26), but this is a native Inno Setup function, so it should be working with no problems?
> 
> @LuniqueStar, could you share some info about your system? What version of Windows are you using? Is it 32 bits?

i am using windows 7 and my system is 64 bits

**Comment by vanyalism** [comment] 2022-07-08 01:56
hello i'm also having the same issue. I'm using windows 10 64bits. I have a space of 10.1GB in my C:\ but I would prefer it in my back up drive D:\ if that doesnt work I'm fine with it in the C drive. Thanks :)

**Comment by vanyalism** [comment] 2022-07-08 01:56
> Thank you. Are you trying to install it in the regular C:\ drive, or do you use something different?

hello i'm also having the same issue. I'm using windows 10 64bits. I have a space of 10.1GB in my C:\ but I would prefer it in my back up drive D:\ if that doesnt work I'm fine with it in the C drive. Thanks :)

**Comment by nipkownix** [comment] 2022-07-08 02:02
The issue happens regardless of the drive of choose? What's the path of the folder you're trying to use for installation? Does changing it make the issue go away?
Sorry for asking so many questions, but I'm trying to reproduce the issue to find out what is wrong.

**Comment by vanyalism** [comment] 2022-07-08 02:10
> The issue happens regardless of the drive you choose? What's the path of the folder you're trying to use for installation? Does changing it make the issue go away? Sorry for asking so many questions, but I'm trying to reproduce the issue to find out what is wrong.

changing it either C drive or D drive doesn't help. I tried re-downloading the setup tool but it still show the same message. This is the path where I download it the first time C:\Program Files (x64)\Konami\Silent Hill 2 and got the error then I tried to change it to the D drive and just added a new folder but the issue still persist.

**Comment by vanyalism** [comment] 2022-07-08 02:20
I figured it out! I tried to redownload the setup tool then I install the game together from my separate Games folder in this path D:\Games\Silent_Hill_2 and it worked like a charm haha but I don't know why it won't install in this path though C:\Program Files (x64)\Konami\Silent Hill 2 anyway thanks for replying :)

**Comment by vanyalism** [comment] 2022-07-08 02:20
I figured it out! I tried to redownload the setup tool then I install the game together from my separate Games folder in this path D:\Games\Silent_Hill_2 and it worked like a charm haha but I don't know why it won't install in this path though C:\Program Files (x64)\Konami\Silent Hill 2 anyway thanks for replying :)

**Comment by nipkownix** [comment] 2022-07-08 03:17
Thanks for the detailed info! I'll have a better look at this issue soon. I'm glad you managed to work around it.

**Comment by Polymega** [comment] 2022-07-08 03:37
> I don't know why it won't install in this path though C:\Program Files (x64)\Konami\Silent Hill 2

Could this be due to a lack of admin privileges to install to an admin-protected directory?

**Comment by nipkownix** [comment] 2022-07-08 04:13
Just figured out the reason: I'm passing the _desired_ installation directory to Inno's ``GetSpaceOnDisk64`` function, but that function apparently expects the folder to exists when doing to checking, instead of just checking the root drive where that location is pointing to. Pretty weird, but I imagine they did it like this for a reason.

Should be a simple fix.

**Comment by reverie3333** [comment] 2022-07-11 23:57
> I first want to say that i have already downloaded the mod when there wasn't a SetupTool, but from the update video of The town of Silent Hill channel they said it was fine to re-download the files using the setup tool. When i try to download the files an error popup and say "Runtime Error (At 134:426) Failed to check free space". What went wrong? Do i need to not redownload some files?

I'm having this same problem.

**Comment by reverie3333** [comment] 2022-07-11 23:57
Any way to fix it?

**Comment by Polymega** [comment] 2022-10-28 21:44
Server migration is done and distribution for the project's file packages has been changed to a more stable solution.

I am going to close this ticket out . For sake of management/consolidation, if you run into any troubles still with the Setup Tool, [please report them here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/647).

**Closed by Polymega** 2022-10-28 21:44 UTC
