### ISSUE TITLE
Windows XP?

### ISSUE THREAD

**Issue by xpretrogamer** [elishacloud/Silent-Hill-2-Enhancements#312] opened 2020-09-09 11:23 UTC
Hi guys ty for working on this!
i know XP is not your focus at all, but i would like to ask this.
i have a wxp reto pc for all those 360 era games (and older)
hardware
xp 32 sp3 (dual boot w7x64)
C2D 8400
amd hd 4850
SB XFI
8gb ddr2 ram (because of dual boot)

i have install the game as per instructions, and it doesnt work , i downloaded some xp files form another thread here (d3d8) and used those ones.
now the game gives an error something like this( No entry point, initializecriticalsectionex,  dynamic KERNEL32.DLL) 

Now on the same PC on the windows7x64 using that same game instalation, (using d3d8 files from the guide) the game runs fine!

now i know i could run the game on windows 7 and deal with it, but im just wondering why it doesn't work on Wxp ?
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5194759/d3d8.log)

FORGOT to mention Wxp is in spanish and W7 in english (i would love to use xp on English but i don't have that disk anymore)

**Comment by elishacloud** [comment] 2020-09-09 17:56
```txt
3024 04:19:02.875 Starting Silent Hill 2 Enhancements! v1.3.1395.0
```

It looks like you are using an old version of the update.  Try using [the latest](https://github.com/elishacloud/Silent-Hill-2-Enhancements/releases).

Also, on Windows XP I would recommend removing ReShade and IndirectSound.  You can do that by removing the following (if they exist):
* d3d9.dll
* d3d9.ini
* d3d9.log
* ReShade.ini
* ReShade_sh2pc.ini
* reshade-shaders _(folder)_
* dsound.dll
* dsound.ini
* dsound.log

**Comment by xpretrogamer** [comment] 2020-09-10 07:47
hi, ty for your response, i tried the new files you linked, but i still get the same error.
about the file names you posted, i did not installed reshade or indirect sound.

i read that some guy made it run on xp, i wonder if he had to make any changes.

**Comment by mirh** [comment] 2022-06-09 12:41
Duplicate of #146?

**Comment by elishacloud** [comment] 2022-07-01 19:41
This issue has been fixed with the latest release.

**Closed by elishacloud** 2022-07-01 19:41 UTC
