### ISSUE TITLE
Camera Clipping Fix

### ISSUE THREAD

**Issue by AeroWidescreen** [elishacloud/Silent-Hill-2-Enhancements#17] opened 2018-07-18 19:37 UTC
[A continuation of this discussion.](https://github.com/ThirteenAG/WidescreenFixesPack/issues/340)

To summarize, it was found that with 16:9 widescreen you could see through objects or parts of a location that weren't intended to be visible. In addition, we found a vanilla bug that causes the camera to stutter in Brookhaven Hospital Room S3 (hp121.cam).

Examples provided by @polymega
![Example](https://user-images.githubusercontent.com/27395260/37620007-72aa2652-2b91-11e8-88ba-bca9ffe2380f.png)

![Example](https://user-images.githubusercontent.com/27395260/37559736-48c4b6e0-2a01-11e8-9104-6777fa7088f4.jpg)

Editing the camera was found to be the most practical solution. Normally we would do this in memory, but it was found to be too difficult with the game overwriting the previous cam data whenever you enter a new room, so we decided to replace the cam files instead.

@Bigmanjapan has been generously providing cam files with these issues patched. He's the guy to ask if you have any questions or requests, as my own involvement has been minimal.

[Download](https://mega.nz/#!9GZQVS7A!HftLWw7YdUWIWHS4EuASPwZ5UWQxjzbDIZwOLPVRASc)

**Comment by Polymega** [comment] 2018-07-18 19:54
And to put people's minds at ease: The white window you see in the photo above is **not** part of the [white shaders bug](https://youtu.be/878F2cbLAXo?t=2m39s). It's simply a solid white texture used in this spot because we were never meant to see the window from this room so the devs never bothered to model geometry outside the window's pane. Bigmanjapan simply moved the camera over to replicate how it would look in this spot when playing in 4:3.

**Comment by Polymega** [comment] 2018-07-18 20:05
@AeroWidescreen I don't believe "er01.cam" was included in your packaged download which was found here:
ThirteenAG/WidescreenFixesPack#340 (comment)

I included it in the following download link:
2018-07-18 SH2 - Cam Clipping Fix.zip

**Comment by elishacloud** [comment] 2018-07-18 21:54
So all we need to do is update these cam files?  No changes to the actual SH2 code?

If that is the case we can use the custom folder feature I am creating for this.  The only question is how we want to distribute these cam files.

My suggestion is to have all the custom cam, map, tex, sound and video files stored in a single package (zip file).  Then users can just download one file and unzip it into the `sh2e` folder.  The sh2-enhce module can make sure that any files in the `sh2e` folder will take precedence over files in the `data` folder.

@Polymega, is that ok with you?

**Comment by Polymega** [comment] 2018-07-18 22:12
> So all we need to do is update these cam files? No changes to the actual SH2 code?

Yes, sir. Just place these .cam files in your custom folder the same as we'll do for the Eddie boss .map files. 

> My suggestion is to have all the custom cam, map, tex, sound and video files stored in a single package (zip file). [...] @Polymega, is that ok with you?

Yeah, I'm in favor of less things someone has to download, too. What I'll probably do then is make the original FMV Enhancement videos the default files for the download package. And if people would rather download the 16:9 variants they can do so at their own discretion. 

Also, @elishacloud , if we do this, I'll include the "[all original sounds](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/12#issuecomment-404677917)" sddata.bin as part of the default Enhanced Audio package and make the [edited sounds version](https://www.youtube.com/watch?v=yy_IqgDX2fc) a variant they can download separately, as well.

**Comment by Storm3000** [comment] 2018-07-20 12:40
All my respect to angular graphics, but I think that the 16:9 FMV pack is better. It's more popular than 16:10 aspect ratio. Besides, 16:9 fixes the corrupt image on the cemetary video.

**Comment by Polymega** [comment] 2018-07-20 12:47
I actually woke up this morning thinking about this: If we ever add, for example, an additional .cam file to the package at a later date, a user would have to re-download gigabytes worth of data to get that one, new .cam file that's only a few kilobytes large, unless I offer patch downloads to go alongside the main download package. 

I'm trying to weigh the pros and cons to different approaches for this. Ultimately I want it to be as user-friendly (in terms of download sizes/times) and intuitive as possible.

**Comment by elishacloud** [comment] 2018-07-23 05:39
I implemented a new custom mod folder feature for this.  It allows users to place all custom files into a folder called 'sh2e' rather than the 'data' folder.  So for instance if you want to replace the 'data\pic\etc\start00.tex' file then you would put the new file into the 'sh2e\pic\etc\start00.tex' folder.  This allows you to update any file in the 'data' folder without actually touching the 'data' folder.

New option created for this called `UseCustomModFolder`.

Fix for this is implemented in [abbcf2c](https://github.com/elishacloud/Silent-Hill-2-Enhancements/commit/abbcf2c3e5162cb3f14ca1125b485af5b9dd2abd) and [07c40bb](https://github.com/elishacloud/Silent-Hill-2-Enhancements/commit/07c40bb1d7330ce3e4a2b28fa8542867d36614a0).

**Comment by Polymega** [comment] 2018-07-25 20:36
@elishacloud The .cam files are confirmed working with your new `UseCustomModFolder` feature. :) Unless you imagine the process of using the .cam files may change in the future, this issue can be closed.

**Comment by elishacloud** [comment] 2018-07-26 01:04
Issue fixed.  Closing.

**Closed by elishacloud** 2018-07-26 01:04 UTC

**Comment by Polymega** [comment] 2018-07-28 20:12
@Bigmanjapan May I ask for another adjustment? Best to shift the camera to the left some? 

![sh2pc 2018-07-28 15-44-22](https://user-images.githubusercontent.com/27395260/43360277-0ba05a06-9281-11e8-9cd4-23b93b6da122.png)

**Comment by Bigmanjapan** [comment] 2018-07-29 04:51
[ap58.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/2238522/ap58.zip)

**Comment by Polymega** [comment] 2018-07-29 06:16
Perfectly done as always! Thank you, sir.

![sh2pc 2018-07-29 02-16-23](https://user-images.githubusercontent.com/27395260/43363561-6f21f1c6-92d5-11e8-8d5b-84065e970491.png)
