### ISSUE TITLE
Soft Shadows glitch

### ISSUE THREAD

**Issue by Arikkusu** [elishacloud/Silent-Hill-2-Enhancements#671] opened 2022-11-14 00:07 UTC
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9998561/d3d8.log)

So unfortunately it seems shadows are busted for me, at least in the Hotel. When "Restore Soft Shadows" is applied, the environment is pitch-black in most spots! Some spots (like a corner of the stairway at the entrance) seem to disable shadows when walking near them, and at least when entering the hallways James is invisible in all that darkness. So it seems for me things are at least visible an somewhat dark when I disable Soft Shadows (or shadows entirely in the game's menu)...but it takes me out of the experience since the flashlight now is somewhat redundant. I guess I can at least keep playing until something shakes out.

**Comment by Polymega** [comment] 2022-11-14 00:13
Are you able to take a snapshot of some of the affected areas? If you press the "Print Screen" button, it'll take a snapshot of the game and save it to `<path-to-game>\imgs\`

**Comment by Arikkusu** [comment] 2022-11-14 00:23
![Screenshot 2022-11-13 19-19-36](https://user-images.githubusercontent.com/118141672/201552491-a7e17627-f2f1-49a7-b979-5ac81fa92330.png)
![Screenshot 2022-11-13 19-19-48](https://user-images.githubusercontent.com/118141672/201552493-ff545435-ca41-4a69-8f46-6389a169ac6a.png)
![Screenshot 2022-11-13 19-20-03](https://user-images.githubusercontent.com/118141672/201552496-10b0b304-32d7-48f4-8713-043ed23fb40e.png)
![Screenshot 2022-11-13 19-20-49](https://user-images.githubusercontent.com/118141672/201552500-1ba8dc68-42c4-4637-85ef-7a5a225c7f06.png)
![Screenshot 2022-11-13 19-20-52](https://user-images.githubusercontent.com/118141672/201552503-17de838b-17a5-4f57-9f8e-e8eccdc5e1c9.png)
![Screenshot 2022-11-13 19-21-00](https://user-images.githubusercontent.com/118141672/201552509-479762a0-841d-4e76-90d7-0be4aa3751fd.png)
So the first three or so are with the setting disabled, the latter enabled. I can try more specific tests if you need?

**Comment by Arikkusu** [comment] 2022-11-14 00:26
![Screenshot 2022-11-13 19-25-09](https://user-images.githubusercontent.com/118141672/201552708-e819d6a1-31c5-4907-8b7e-439d983c5000.png)
![Screenshot 2022-11-13 19-25-13](https://user-images.githubusercontent.com/118141672/201552712-1df7ed83-4361-48c8-b1cf-cd212c8e4bc5.png)
![Screenshot 2022-11-13 19-25-24](https://user-images.githubusercontent.com/118141672/201552714-0359ce85-7452-427d-b015-e27e77260630.png)
![Screenshot 2022-11-13 19-25-26](https://user-images.githubusercontent.com/118141672/201552716-8e75b5ee-4be4-4a77-b3c3-d4b889be08cd.png)
ACTUALLY! Better examples a few steps into this same room...

**Comment by Arikkusu** [comment] 2022-11-14 00:27
Maybe it's hard to tell from the screenshots, but with the flashlight off some objects (like the papers) are a bit glowy in the darkness, yet I believe on the entrance the light through the windows may have been invisible (I can check)

**Comment by Polymega** [comment] 2022-11-14 00:32
If you open the Configuration Tool (SH2EEconfig.exe) and go to the Advanced tab and uncheck "Fix GPU anti-aliasing", does it fix this issue?

**Comment by Arikkusu** [comment] 2022-11-14 00:47
Well basically everything was enabled by default (I believe thanks to the installer), but now I've disabled the GPU AA fix and reenabled the shadow fix and...it works so far?! Not only that, but the status window now shows green and red tints (I was wondering if I misremembered...)!

**Comment by Arikkusu** [comment] 2022-11-14 00:48
![Screenshot 2022-11-13 19-45-06](https://user-images.githubusercontent.com/118141672/201554026-758ea202-ab53-463f-a64a-460c3e92bc37.png)
![Screenshot 2022-11-13 19-45-09](https://user-images.githubusercontent.com/118141672/201554031-27172540-afc1-490e-a6a4-b460e3127dfb.png)
![Screenshot 2022-11-13 19-45-23](https://user-images.githubusercontent.com/118141672/201554036-e91517f9-01ea-4088-9820-255df91d0709.png)

Here they are, they seem aight to me, although I can keep ya posted if something goes wrong

**Comment by Arikkusu** [comment] 2022-11-14 01:30
Well it's a much better balance of dark and navigable at least!

**Comment by Polymega** [comment] 2022-11-14 01:39
Great. The `FixGPUAntialiasing` feature is to fix shadow rendering issues if you decide to force enable anti-aliasing for the game through your Nvidia GPU control panel. So long as you don't enable force AA through your Nvidia control panel, you should be fine to leave that option disabled.

I'll close this ticket as resolved then. You can re-open this ticket if the issue isn't resolved.

**Closed by Polymega** 2022-11-14 01:39 UTC
