### ISSUE TITLE
Setup won't finish downloading

### ISSUE THREAD

**Issue by Mobeeuz** [elishacloud/Silent-Hill-2-Enhancements#549] opened 2022-07-03 23:32 UTC
Installer continually fails to download the files, asking for a retry, before failing again. I know this is supposed to be easier for noobs, but can we have a download location of the packages for those not wanting to go through this a dozen times before giving up?

**Comment by Polymega** [comment] 2022-07-03 23:42
Is it failing on all files for you? Or specific ones?

**Comment by Mobeeuz** [comment] 2022-07-03 23:54
Not sure, the 4.2GB one was where I gave up - six times and I'm out.

**Comment by Darthagnon** [comment] 2022-07-04 02:29
I'm also interested in doing offline installation - I don't have reliable internet.

Where can I download and place the components so they'll be detected by the new installer?

**Comment by AeroWidescreen** [comment] 2022-07-04 04:28
> Some worked fine, the 4.2GB one was where I gave up - six times and I'm out. It slows down to a crawl, then gives up - not always at the same point but before 75%.

There is no individual file that is 4.2 GB; that would be the total size of all files downloaded. The largest files would be the Audio and FMV packs, which creates a total of 3.8 GB, with most of the remaining data coming from the Image pack.

You should be able to use the installer multiple times to download the archives you need. Just make sure it's all installed at the same location each time you do this. I would download the smallest files first, then do the big ones (Audio, FMV, and Images) individually until everything has been installed.

![Example](https://i.imgur.com/6KDhOf3.png)

**Comment by Mobeeuz** [comment] 2022-07-04 05:17
I was looking at the total amount, it's an installer so my attention was minimal at first post. It was the FMV pack failing during download.

The above solution eventually worked, but it took me hours to get the FMV's and Audio downloaded - slowing down to a crawl and then failing. Too many people downloading? Server giving up? Just guesswork from my end.

If offline files are not going to be provided, perhaps switch from Inno to something that resumes broken downloads?

**Comment by UserGit-2021** [comment] 2022-07-04 21:01
I demand to return the offline installer.

**Comment by Polymega** [comment] 2022-07-04 21:07
Demanding is not how this works. Put that to the curb.

**Comment by UserGit-2021** [comment] 2022-07-04 21:11
> 

Because it reminded me of the situation with Denuvo. And I wrote on emotion.

**Comment by UserGit-2021** [comment] 2022-07-04 21:11
> Demanding is not how this works. Put that to the curb.

Because it reminded me of the situation with Denuvo. And I wrote on emotion.

**Comment by Polymega** [comment] 2022-07-04 21:15
What on Earth would possess you to think we have DRM in this tool or our project in general?

Here's what I can confirm: This project is free in every sense of the word. You haven't paid anything to use it. We owe you nothing, so you cannot demand anything.

Talking this way to us won't get you anywhere, I assure you.

**Comment by smoothbrainnn** [comment] 2022-08-21 17:34
I created an account to bump this issue up. The server cionnection keep resetting on me so I can't finish downloading all the files, especially the bigger ones.

**Comment by Polymega** [comment] 2022-08-21 23:04
Until we look further into this, you can read over notes and follow this approach to download the files: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/580#issuecomment-1219765965

**Comment by nipkownix** [comment] 2022-08-24 03:08
> I created an account to bump this issue up. The server connection keeps resetting on me so I can't finish downloading all the files, especially the bigger ones.

The connection resets after how much time? Are the download speeds slow? If the server is terminating the connection, I'm afraid I can do nothing to avoid it in the installer :/

**Comment by smoothbrainnn** [comment] 2022-08-27 20:01
> The connection resets after how much time? Are the download speeds slow? If the server is terminating the connection, I'm afraid I can do nothing to avoid it in the installer :/

I don't why, but I have a friend who lives in the Detroit area, who had 0 issues downloading the files online. When I used a VPN to connect to a Chicago server, the nearest server to the person, the issues went away.

Hopefully that info helps?

**Comment by Polymega** [comment] 2022-10-28 21:45
Server migration is done and distribution for the project's file packages has been changed to a more stable solution.

I am going to close this ticket out . For sake of management/consolidation, if you run into any troubles still with the Setup Tool, [please report them here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/647).

**Closed by Polymega** 2022-10-28 21:45 UTC
