### ISSUE TITLE
4K resolution and Render resolution x2:  Last frame before screen transition persists when loading other screens

### ISSUE THREAD

**Issue by Nicolas-Miranda** [elishacloud/Silent-Hill-2-Enhancements#1027] opened 2024-09-01 02:27 UTC
As the title states, while playing in 4K resolution and using render resolution x2, the last frame before a screen transition persists when loading other screens like opening a door or opening the map/inventory. So instead of fading to black when loading a new screen, it displays a remnant frame.

When the render resolution is switched back to x1 the screen transition works normally by fading to black instead of displaying a remnant frame.

No errors or crashes, just the visual bug. 

Probably it's related to a buffer issue due to the high resolution.

UPDATE: Bug also happens with default x1 render resolution.

**Comment by Polymega** [comment] 2024-09-01 02:55
When using a render resolution other than 1x, can you find a way to consistently make this happen? If we can readily test, we can then find a solution for the issue.

**Comment by Nicolas-Miranda** [comment] 2024-09-01 03:00
I just turned on my PC, will record the issue.

**Comment by Polymega** [comment] 2024-09-01 03:06
We've seen footage of it happening; we just don't know how to consistently and easily make it happen.

**Comment by Nicolas-Miranda** [comment] 2024-09-01 03:14
I got it recorded, uploading the video now

**Comment by MilkManEX** [comment] 2024-09-01 03:15
In my case:

Be in fullscreen windowed mode
Be in 4K
Have resolution set to 2x
Go through any door in the apartments or load into a saved game in the apartments

Doesn't happen in exclusive fullscreen so far.

**Comment by Nicolas-Miranda** [comment] 2024-09-01 03:17
> In my case:
> 
> Be in fullscreen windowed mode Be in 4K Have resolution set to 2x Go through any door in the apartments or load into a saved game in the apartments
> 
> Doesn't happen in exclusive fullscreen so far.

I tested it last night and it happens in all display modes. For some it takes a while but the issue ended up showing anyways.

**Comment by Nicolas-Miranda** [comment] 2024-09-01 03:23
> We've seen footage of it happening; we just don't know how to consistently and easily make it happen.

Here it is the video, I recorded how to trigger the issue:

https://youtu.be/KtELzXFQhmQ

Even if you set the render resolution to x2 and restart the game, the issue happens in the same way randomly when opening a door or loading any map/inventory screen.

Wait some minutes for the video to finish processing.

**Comment by Nicolas-Miranda** [comment] 2024-09-01 03:27
Attached save file to help on testing: 

[Folder 01.zip](https://github.com/user-attachments/files/16827146/Folder.01.zip)

**Comment by AeroWidescreen** [comment] 2024-09-01 03:33
I wasn't able to reproduce this following the exact same steps and settings shown in the video. Could you please upload your **d3d8.log** file, located in your install folder? Do this immediately after the bug occurs.

**Comment by Nicolas-Miranda** [comment] 2024-09-01 03:36
This is the d3d8.log for the video session:

[d3d8.zip](https://github.com/user-attachments/files/16827153/d3d8.zip)

**Comment by Nicolas-Miranda** [comment] 2024-09-01 03:38
You can find the following logs when enabling render resolution to x2:

7096 23:10:36.175 Silent Hill 2 engine resolution set to: 7680x4320
7096 23:10:36.175 Setting Hotel Room 312 Resolution Fix...
7096 23:10:36.175 Redirecting IDirect3DDevice9::Reset(this = 15B5ADB8, pPresentationParameters = 0019FD20) ...
7096 23:10:36.175 Destroyed runtime environment on runtime 15B5C3F8.
7096 23:10:36.189 Recreated runtime environment on runtime 15B5C3F8.
7096 23:10:36.192 Silent Hill 2 display resolution set to: 3840x2160
7096 23:10:36.499 Successfully loaded LiftGammaGain.fx
7096 23:10:36.499 Enabling technique: LiftGammaGain
7096 23:10:36.774 Loading image files for textures ...
7096 23:10:46.864 m_IDirect3DDevice8::CreateImageSurface Error: Failed to create image surface! 7680x4320
7096 23:10:49.350 m_IDirect3DDevice8::CreateImageSurface Error: Failed to create image surface! 7680x4320
7096 23:10:51.067 m_IDirect3DDevice8::CreateImageSurface Error: Failed to create image surface! 7680x4320
7096 23:10:52.620 m_IDirect3DDevice8::CreateImageSurface Error: Failed to create image surface! 7680x4320
7096 23:10:54.987 m_IDirect3DDevice8::CreateImageSurface Error: Failed to create image surface! 7680x4320
7096 23:10:58.094 m_IDirect3DDevice8::CreateImageSurface Error: Failed to create image surface! 7680x4320
7096 23:10:59.377 m_IDirect3DDevice8::CreateImageSurface Error: Failed to create image surface! 7680x4320
7096 23:11:00.927 m_IDirect3DDevice8::CreateImageSurface Error: Failed to create image surface! 7680x4320
7096 23:11:04.044 m_IDirect3DDevice8::CreateImageSurface Error: Failed to create image surface! 7680x4320
7096 23:11:06.811 m_IDirect3DDevice8::CreateImageSurface Error: Failed to create image surface! 7680x4320
7096 23:11:08.877 m_IDirect3DDevice8::CreateImageSurface Error: Failed to create image surface! 7680x4320
7096 23:11:10.910 m_IDirect3DDevice8::CreateImageSurface Error: Failed to create image surface! 7680x4320
7096 23:11:14.110 m_IDirect3DDevice8::CreateImageSurface Error: Failed to create image surface! 7680x4320
7096 23:11:17.994 m_IDirect3DDevice8::CreateImageSurface Error: Failed to create image surface! 7680x4320
7096 23:11:20.545 m_IDirect3DDevice8::CreateImageSurface Error: Failed to create image surface! 7680x4320
7096 23:11:33.900 m_IDirect3DDevice8::CreateImageSurface Error: Failed to create image surface! 7680x4320

**Comment by AeroWidescreen** [comment] 2024-09-01 04:01
Thanks. One last thing.

1. Open **SH2EEconfig.exe**
2. Towards the right of the first tab, above the SMAA option, you should see "Front buffer data capture method". Change this from **Auto** to **Use DirectX**. 

Does the bug still occur?

**Comment by Nicolas-Miranda** [comment] 2024-09-01 04:07
> Thanks. One last thing.
> 
>     1. Open **SH2EEconfig.exe**
> 
>     2. Towards the right of the first tab, above the SMAA option, you should see "Front buffer data capture method". Change this from **Auto** to **Use DirectX**.
> 
>     3. Save and Launch Game.
> 
> 
> Does the bug still occur?

Testing it now

**Comment by Nicolas-Miranda** [comment] 2024-09-01 04:11
> Thanks. One last thing.
> 
>     1. Open **SH2EEconfig.exe**
> 
>     2. Towards the right of the first tab, above the SMAA option, you should see "Front buffer data capture method". Change this from **Auto** to **Use DirectX**.
> 
>     3. Save and Launch Game.
> 
> 
> Does the bug still occur?

I just did the same steps from the video using DirectX and the issue still happens.

**Comment by Polymega** [comment] 2024-09-01 04:19
Are you using Nvidia DSR (or AMD's equivalent) with the game?

**Comment by Nicolas-Miranda** [comment] 2024-09-01 04:22
> Are you using Nvidia DSR (or AMD's equivalent) with the game?

No, Nvidia DSR is disabled in my control panel.

**Comment by AeroWidescreen** [comment] 2024-09-01 04:22
I just experienced the bug. It doesn't always immediately occur, but it eventually happens with the same error in the log.

> 6060 21:18:32.945 m_IDirect3DDevice8::CreateImageSurface Error: Failed to create image surface! 7680x4320

And I'll take his word that it occurs with DirectX as well. We'll have to forward this one to Elisha... 

> Are you using Nvidia DSR (or AMD's equivalent) with the game?

I'm not. And we're both using Nvidia cards. I'm on Windows 11, he's on Windows 10.

**Comment by Nicolas-Miranda** [comment] 2024-09-01 04:30
> I just experienced the bug. It doesn't always immediately occur, but it eventually happens with the same error in the log.
> 
> > 6060 21:18:32.945 m_IDirect3DDevice8::CreateImageSurface Error: Failed to create image surface! 7680x4320
> 
> And I'll take his word that it occurs with DirectX as well. We'll have to forward this one to Elisha...
> 
> > Are you using Nvidia DSR (or AMD's equivalent) with the game?
> 
> I'm not. And we're both using Nvidia cards. I'm on Windows 11, he's on Windows 10.

Thanks so much!!

Please let me know if you need for me to test any configuration change as at least on my side it happens consistently.

**Comment by danmons** [comment] 2024-09-01 09:25
Reporting that this happens for me on Linux/WINE as well. Same methods as above in use, setting render resolution to 2.0x and playing back on my 1920x1080 screen with display resolution also set to 1920x1080. 

OS / software versions:
Arch Linux, kernel 6.10.7
KDE Plasma 6.1.4 running on Wayland (X11 native applications via XWayland) 
Mesa 24.2.1
WINE 9.16
CPU and iGPU: AMD Ryzen 7 4800H with Renoir graphics. 

Tested on a clean WINE prefix with no modifications.

**Comment by MrPunished** [comment] 2024-09-01 19:39
This has happened to me too. I'm not even using the resolution scale, just fullscreen at 4K with a 3080. I'm not certain of the exact cause, but it does seem to kick in after messing around in the menus. Perhaps going into the settings menu might be the culprit? Not certain though.

**Comment by Nicolas-Miranda** [comment] 2024-09-02 07:38
> I just experienced the bug. It doesn't always immediately occur, but it eventually happens with the same error in the log.
> 
> > 6060 21:18:32.945 m_IDirect3DDevice8::CreateImageSurface Error: Failed to create image surface! 7680x4320
> 
> And I'll take his word that it occurs with DirectX as well. We'll have to forward this one to Elisha...
> 
> > Are you using Nvidia DSR (or AMD's equivalent) with the game?
> 
> I'm not. And we're both using Nvidia cards. I'm on Windows 11, he's on Windows 10.

After playing for a while using render resolution x1, the issue also happens with that configuration. I just experienced the error.

**Comment by Nicolas-Miranda** [comment] 2024-09-02 07:45
Logs from the last bug occurrence:

[d3d8.zip](https://github.com/user-attachments/files/16833852/d3d8.zip)

**Comment by AeroWidescreen** [comment] 2024-09-02 15:00
Quick update on the situation: we believe we've identified the problem and it shouldn't be too long before we release an update for this, assuming our testing continues to show positive results. Cross your fingers and bear with us. Thanks.

**Comment by Nicolas-Miranda** [comment] 2024-09-05 01:49
Hi @AeroWidescreen  and @Polymega, I started the game multiple times and there is no update prompt for the hotfix. How can I apply it? Do I need to download it and install it manually?

I'm also ran the SH2EEsetup.exe and there is no updates.

**Comment by AeroWidescreen** [comment] 2024-09-05 04:32
@Nicolas-Miranda 
1. Open SH2EEsetup.exe
2. Select "Install or Repair Packages"
3. Select the "Enhanced Executable" and "Essential Files"
4. Wait for the download to finish and you should be good to go.

**Comment by AeroWidescreen** [comment] 2024-09-13 17:14
> Chiming in to say I installed the most up to date stuff today on Linux and am still getting this issue

We have another update coming that will hopefully solve this issue once and for all. Basically, there was a memory leak. Our last patch raised the memory ceiling but did not fix the actual leak. We now believe we've successfully patched the leak, so we're currently having it tested to ensure that this is the case.

**Comment by chloyster** [comment] 2024-09-13 18:02
Great to hear! Willing to test anything if need be as well

**Comment by Polymega** [comment] 2024-10-08 02:44
I'm not sure what was last discussed in this thread, but we found the issue to be a memory overflow problem due to d3d8to9. We've since put in a fix for this. Be sure to update your project files. Thanks

**Closed by Polymega** 2024-10-08 02:44 UTC
