### ISSUE TITLE
Silent Hill 2 crashes

### ISSUE THREAD

**Issue by Joseto3011** [elishacloud/Silent-Hill-2-Enhancements#717] opened 2023-02-23 12:13 UTC
Sometimes when I'm playing Silent Hill 2, many times the game crashes, this happens when I go from one room or scene to another, it doesn't always happen and it fixes itself after several minutes, but I really don't know how to fix it, I had to reinstall the game but the problem is still there.

**Comment by Joseto3011** [comment] 2023-02-23 12:14
![image](https://user-images.githubusercontent.com/126119564/220902392-dc104a67-00c7-48d7-9670-ea5e873d79ac.png)
![image](https://user-images.githubusercontent.com/126119564/220902449-0763207b-093b-4959-ad10-f98c6dc4dce7.png)

**Comment by Joseto3011** [comment] 2023-02-23 12:29
To describe more, the game freezes and the audio freezes too, repeating itself over and over again.

**Comment by Polymega** [comment] 2023-02-23 14:04
To start, please enable the option to shown known file extensions in your Windows Explorer. This guide explains it for Windows 7-10, but it should hopefully be similar for Windows 11.

Next, go back to the Silent Hill 2 folder and locate a `d3d8.log` file. Please drag & drop that file into your response here.

**Comment by Joseto3011** [comment] 2023-02-24 01:53
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/10819948/d3d8.log)
I'm sorry for replying so late, I wasn't at home.

**Comment by Polymega** [comment] 2023-02-24 02:10
Did you follow my important note [from this post?](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/716#issuecomment-1441005538) If you're using the vanilla `sh2pc.exe` this will likely happen every time you play.

**Comment by Joseto3011** [comment] 2023-02-24 02:12
Yes, in fact I completely reinstalled the game.

**Comment by Joseto3011** [comment] 2023-02-24 02:15
Even a few minutes ago I checked a forum on the same page where the same problem was discussed. I decided to repair the "brains" of the game, but still as soon as I start playing and James comes out of the bathroom at the beginning of the game, he freezes preventing me from playing.

**Comment by Polymega** [comment] 2023-02-24 02:15
Please try [this build](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/10798848/d3d8.zip) and see if the issue persists. Replace files in the game's main folder with what's in this build.

**Comment by Joseto3011** [comment] 2023-02-24 02:21
I already replaced the files, I'll do a game test.

**Comment by Joseto3011** [comment] 2023-02-24 02:32
the problem is not solved, the game keeps freezing but now when i go to pick up the map from james car.

**Comment by Polymega** [comment] 2023-02-24 02:46
I'm not sure what the issue is. You can open `SH2EEConfig.exe` and start disabling features to see if anything in there is causing your issues. You can disable _everything_ within one of the tabs then launch the game to test. 

If the issue persists, you can re-open `SH2EEconfig.exe` and disable _everything_ on the next tab and re-test. Repeat this process in the hopes that disabling something will resolve your issue. If the issue is resolved, you will then know which tab the issue in on, then go from there to pin-point what specific issue is causing the problem.

**Comment by Joseto3011** [comment] 2023-02-24 02:57
You are probably not understanding my problem very well since I do not speak English, I am using the translator to communicate.

**Comment by Joseto3011** [comment] 2023-02-24 03:01
At the moment I have not made any configuration that you mentioned, but I suspect that the problem has to do with changing the language of the game. I played for a while with the "English" language, it was going great, now I'm trying another game with the "Spanish" language.

**Comment by Polymega** [comment] 2024-10-08 03:28
Closing ticket. Feel free to re-open if you'd like further assistance.

**Closed by Polymega** 2024-10-08 03:28 UTC
