### ISSUE TITLE
Extreme Slowdown During Gameplay 

### ISSUE THREAD

**Issue by AnEternalEnigma** [elishacloud/Silent-Hill-2-Enhancements#670] opened 2022-11-10 01:07 UTC
Game engine slows to a crawl after most recent updates. Using Windows 11 Pro updates as of November 9, 2022 and the latest Nvidia driver 526.47. The issue alleviates temporarily when I alt-tab and then return but initiates again. I have enclosed a video of the issue and a d3d8.log.

Video enclosed: https://www.youtube.com/watch?v=z8zxu9EJjUc

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9976232/d3d8.log)

**Comment by AnEternalEnigma** [comment] 2022-11-10 05:00
No, this is not fix the issue.

**Comment by Polymega** [comment] 2022-11-10 18:23
I did a quick Google search and it looks like Sonic Studio/Sonic Radar can cause all sorts of issues with various PC games.

**Comment by AnEternalEnigma** [comment] 2022-11-10 18:33
None of the options changed worked and made things worse. None of the splash screens loaded and all I saw was a blank black screen with the original SH2 mouse cursor (the bloody knife) on the screen. I started the game by hitting enter repeatedly and the game's performance was even slower. The menus were so laggy I just had to Alt+F4. Uninstalled Sonic Studio also had no effect.

**Comment by Polymega** [comment] 2022-11-10 18:49
Do you have any special Nvidia filters being applied to the game? I noticed the dark/black levels are still crushed for you, and am wondering if there's an external program running filters/effects on the game that might be affecting performance?

**Comment by AnEternalEnigma** [comment] 2022-11-10 18:53
I'm not really familiar with Nvidia filters, so I'm going to say no. I don't really mess with the Control Panel either.

**Comment by elishacloud** [comment] 2022-11-10 19:07
Try disabled each of these options individually rather than all at once, such that only one of these are disabled at a time.  I suspect that at least one of these options should make a difference.

```ini
ScreenMode = 3
d3d8to9 = 0
EnableSoftShadows = 0
UseCustomModFolder = 0
FixGPUAntiAliasing = 0
PauseScreenFix = 0
```

**Comment by AnEternalEnigma** [comment] 2022-11-10 19:16
Having each one disabled at a time had no effect. Still slowdown.

**Comment by Polymega** [comment] 2022-11-10 19:27
Elisha thinks he might know what is causing the issue is and is taking a look. In the meantime, this won't help with the slowdown, but if you'd like to do some spring cleaning you can also remove these files from the game's directory:

```
d3d9.log
_README.txt
```

**Comment by AnEternalEnigma** [comment] 2022-11-10 19:30
Do you think it would be beneficial to do a clean install of everything? I've had versions of the Enhanced Edition on my computer since February 2021.

**Comment by elishacloud** [comment] 2022-11-10 19:40
You could try that.   Also, can you try with a smaller resolution?  Ideally you would try with the same resolution you were using when you removed d3d8.dll.  This way we can test to see if at the same resolution it works the same with and without d3d8.dll.

**Comment by AnEternalEnigma** [comment] 2022-11-10 19:45
Lowering to 1920x1080 did not work.

**Comment by elishacloud** [comment] 2022-11-10 19:51
Ok, can you try with this ini file?  Just replace your existing ini with this one.

[d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9984189/d3d8.zip)

**Comment by AnEternalEnigma** [comment] 2022-11-10 19:57
It changed it to the regular PC version of the game

**Comment by elishacloud** [comment] 2022-11-10 20:01
Yes.  That just disables every feature of the Enhanced Edition.  Can you try re-enabling these settings tab-by-tab using the SH2EEconfig.exe tool to see which tab's settings has the issue?

**Comment by AnEternalEnigma** [comment] 2022-11-10 20:40
I am noticing that after the Konami and Team Silent splash screens, the game crashes to desktop when all of this tab is unchecked 
![image](https://user-images.githubusercontent.com/79077499/201201351-8b12f30b-16b1-4192-8ced-73faa61bc596.png)

**Comment by AnEternalEnigma** [comment] 2022-11-10 20:41
I re-enabled "Allow for high quality images" and the game worked again but the slowdown still happens

**Comment by AnEternalEnigma** [comment] 2022-11-10 20:43
Also, when I have "Allow for high quality audio" unchecked, the .exe just launches a frozen black screen and I have to kill in task manager.

**Comment by Polymega** [comment] 2022-11-10 20:45
> I re-enabled "Allow for high quality images" and the game worked again but the slowdown still happens

The reason for this is that the high resolution textures (from the Image Enhancement Pack) are stored in the `sh2e` folder and, when this option is unchecked, the game still pulls these texture but can't handle them, since they're larger than the vanilla file sizes/dimensions.

> Also, when I have "Allow for high quality audio" unchecked, the .exe just launches a frozen black screen and I have to kill in task manager.

The same is true for this and the high quality audio (from the Audio Enhancement Pack).

--------------

> It changed it to the regular PC version of the game

When Elisha gave you that test `d3d8.ini` file it basically disabled everything in our project. When you tested this, did the game run at full speed, at least? If so, that can help confirm it's a particular setting in the project causing the issue.

**Comment by AnEternalEnigma** [comment] 2022-11-10 20:46
Yeah, the default d3d8.ini did make everything run normally. I have a separate, unmodded version of Silent Hill 2 as well on my computer that I use for speedrunning and that also runs fine.

**Comment by AnEternalEnigma** [comment] 2022-11-10 20:50
Don't know if this is relevant or not, but I've noticed that if I skip the cutscene in the mirror, the game runs fine. But when I leave the bathroom and it loads the next in-engine scene of James walking to the barrier outside, it slows down again.

**Comment by Polymega** [comment] 2022-11-10 20:51
To maybe make things easier:

_Temporarily_ rename the `sh2e` folder to anything else. This will prevent our project from pulling any of our modified files that would otherwise freeze/hang the game when center features aren't enabled (like you experienced/described right above).

Then, disable all the features on a per-tab basis, with testing/launching the game between disabling each tab, as Elisha suggested. Hopefully, when disabling everything on a tab, the game will eventually run correctly. This will then tell us if a particular feature on whatever the last tab you disabled is the culprit. From there, you can re-enable things on that tab, one-by-one, until you hone in on the specific offender.

----------------

Perhaps before doing any of that, if you play in windowed mode (Display > Display > Screen Mode) and make the resolution very small, does it run at 'full speed'?

**Comment by AnEternalEnigma** [comment] 2022-11-10 20:52
I have tested windowed mode and it still slows down. I also experimented with taking my Windows 11 desktop scale back down to 100% since I am on a 4K monitor and it still slowed down.

**Comment by AnEternalEnigma** [comment] 2022-11-10 20:53
Just took it down to 640x480 on windowed and still slowed down

**Comment by Polymega** [comment] 2022-11-10 20:54
Thanks for testing that. Try disabling everything available on a per-tab basis found in the Configuration Tool if you haven't done a full sweep on that yet, please.

**Comment by elishacloud** [comment] 2022-11-10 20:57
It seems like the issues may be on the "Display" or "Advanced" tabs.  Can you try clicking the "Default" button to set all default settings and then disabling all settings on the "Display" and "Advanced" tabs?

**Comment by AnEternalEnigma** [comment] 2022-11-10 21:00
I found the culprit. It's 100% the "custom streaming audio engine" setting. Works perfectly when it's unchecked.

**Comment by Polymega** [comment] 2022-11-10 21:04
Can you re-enable that and temporarily remove these files from the game's directory, and see if it still fixes things?

```
dsoal-aldrv.dll
dsound.dll
```

**Comment by AnEternalEnigma** [comment] 2022-11-10 21:08
It slowed down with the custom audio streaming engine enabled and those two files removed from the folder

**Comment by Polymega** [comment] 2022-11-10 21:15
Thanks for testing that. I was curious if DSOAL was conflicting with the custom streaming audio engine. You can place those files back in; those files are for DSOAL which restores 3D audio for the game.

We'll take a look into this. In the meantime, you can click the "Default" button in the Configuration Tool to restore everything back then re-disable "Use custom streaming audio engine."

And just a heads-up: When this feature is disabled, it'll use the vanilla game's bugged audio engine. This will eventually make the game's background music start to skip infinitely until it stops playing altogether then most likely crash your game. When this feature is disabled, you'll need to run the game on a single core to mitigate the issue (found on the last tab).

If there's no rush to play the project, I'd recommend just keeping the default settings enabled until we can come up with a solution for you to test.

**Comment by Polymega** [comment] 2022-11-10 21:18
Oh, and can you attach a newer copy of your `d3d8.log` file? You can have the "Use custom streaming audio engine" enabled or disabled for this log; we just need you to boot up the game then exit it to generate a new log file.

**Comment by elishacloud** [comment] 2022-11-10 23:42
@AnEternalEnigma, can you try with this update?   I am hoping this will fix the issue with the custom audio streaming engine.

Here is the testing build:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9985324/d3d8.zip)

**Comment by AnEternalEnigma** [comment] 2022-11-11 00:33
Here is my newer copy of d3d8.log. Sorry, had to leave the house for some errands.
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9985502/d3d8.log)

Will try the updated one now.

**Comment by AnEternalEnigma** [comment] 2022-11-11 00:35
The newer d3d8 did not work. It put some weird RGB pattern over my screen and the slowdown still happened. 
![image](https://user-images.githubusercontent.com/79077499/201234889-b237af30-549f-4aab-b6e7-0d12ab1c5d38.png)

**Comment by Polymega** [comment] 2022-11-11 01:08
Do you have a piece of software called something like "[Nahimic](https://steelseries.com/nahimic)" on your computer? It looks like this might've been included/installed if you used a SteelSeries headset before? If so, can you make sure the software is closed and not running? If you quit the software, does it fix this problem?

**Comment by AnEternalEnigma** [comment] 2022-11-11 01:14
I didn't have any software running, but I found three instances of it in Task Manager. I ended all three tasks. After, it looks better but still faulty. The slowdown also happens. This is still with the new d3d8 provided.

**Comment by AnEternalEnigma** [comment] 2022-11-11 01:15
![image](https://user-images.githubusercontent.com/79077499/201239467-87d4002e-f56e-49c1-a9dd-95a3c2e43481.png)

**Comment by AnEternalEnigma** [comment] 2022-11-11 01:16
I am about to start streaming on Twitch so my troubleshooting will have to wait until tomorrow.

**Comment by Polymega** [comment] 2022-11-11 01:23
>> Do you have a piece of software called something like "[Nahimic](https://steelseries.com/nahimic)" on your computer?
>
> I didn't have any software running, but I found three instances of it in Task Manager.

That's interesting; I wonder what possibly installed Nahimic and is making it run. I suggested it as I found these modules, which are not typical (and related to audio), are still being ran when you launch the game:

```
C:\ProgramData\A-Volute\A-Volute.28054DF1F58B4\Modules\ScheduledModules\AudioDevProps2.dll
C:\ProgramData\A-Volute\A-Volute.28054DF1F58B4\Modules\ScheduledModules\NahimicOSD.dll
C:\ProgramData\A-Volute\A-Volute.28054DF1F58B4\Modules\ScheduledModules\ProductInfo.dll
```

> It put some weird RGB pattern over my screen

That's a CRT shader we'll be introducing in the next project release. We still have a few kinks to iron out with it (the shader becomes messed up when resizing the game's resolution through the Options menu). I'm not sure how it became enabled, but you can set `CRTShader = 0` in the `d3d8.ini` file for the time being to disable it.

**Comment by Polymega** [comment] 2022-11-11 18:27
When you run the game with our project, can you also open up Task Manager and show your CPU usage per core used? If you don't see the cores as separate graphs, right click in the area and select Change graph to > Logical processors. 

![image](https://user-images.githubusercontent.com/27395260/201405324-501e8a23-25bf-4ad5-887f-eb89238e3731.png)

We're wondering if some outside compatibility setting is forcing the game to run on a single core, bottlenecking things.

**Comment by AnEternalEnigma** [comment] 2022-11-12 02:55
You may be on to something 
![image](https://user-images.githubusercontent.com/79077499/201453340-74432a50-6cff-44d7-a097-9625ab4a6ac8.png)

**Comment by AnEternalEnigma** [comment] 2022-11-12 02:56
I have a program called Process Lasso that I use when I'm speedrunning SH2 on a separate .exe to force it to one core. But this program does not launch at startup and I only use it when I'm using my speedrunning (aka unmodified) install of SH2.

**Comment by AnEternalEnigma** [comment] 2022-11-12 03:00
Well, that solves the problem. It was still somehow running in the background even without me opening the program. I spotted some tasks in Task Manager. I uninstalled the program and it now works without slowdown. I wonder why it started doing that? It didn't do that when I last played this and I've had Process Lasso on my computers since 2020 or so.

**Comment by Polymega** [comment] 2022-11-12 03:42
There might have been a profile made in Process Lasso to detect _any_ instance of "sh2pc.exe" running and force it to a single core. So to Process Lasso, it didn't matter what folder you launched the game from; so long as it saw "sh2pc.exe" it did its thing.

One way to get around this while still using Process Lasso is to rename the sh2pc.exe in your EE folder. That'd work, but we don't recommend doing it.

**Comment by Polymega** [comment] 2022-11-12 04:46
Now the next thing I'd love to solve for you is the crushed levels:

<img width="640" alt="001" src="https://user-images.githubusercontent.com/27395260/201456210-853149fc-10be-4a5e-b357-012d2d401916.png">
<img width="640" alt="002" src="https://user-images.githubusercontent.com/27395260/201456212-c4f1d3ad-027a-4820-887d-5716d13f9697.png">

Can you check two things for me?

Even though you don't use Nvidia filters, it might have accidentally gotten enabled for SH2. If you use Nvidia Freestyle, press Alt + Z and go to Game Filters. Do you have a filter profile set for SH2?

Another thing to check: Do you have custom filters for SH2 made through your OBS? Perhaps "[Limited RGB Color](https://www.benq.com/en-us/knowledge-center/knowledge/full-rgb-vs-limited-rgb-is-there-a-difference.html)" mode is set for SH2 in OBS? (Or maybe it isn't and needs to be?)

![image](https://user-images.githubusercontent.com/27395260/201457530-8126a88a-8529-4c59-8ef8-fe1eba6e55e2.png)

**Comment by Polymega** [comment] 2022-11-21 18:05
I'll close this ticket as resolved. If you'd like to troubleshoot why the game has crushed blacks in the future, I'd be happy to try and further troubleshoot this with you.

**Closed by Polymega** 2022-11-21 18:05 UTC
